### ISSUE TITLE
Icon, zsh

### ISSUE THREAD

**Issue by Spuxy** [gh0stzk/dotfiles#1]
Hello nice dots, btw. could u provide icons for ur polybar ? 
Is there anychance to showup dotfiles for zsh?

**Comment by gh0stzk** [comment]
> Hello nice dots, btw. could u provide icons for ur polybar ?
> Is there anychance to showup dotfiles for zsh?

Icons are from materialdesignsfont https://www.nerdfonts.com/
My .zsh is the default config file, there is nothing different.
