### ISSUE TITLE
Cannot change defualt terminal to alacritty 

### ISSUE THREAD

**Issue by Jayy001** [gh0stzk/dotfiles#10]
I've edited the `sxhkdrc` file to 

```
#
# wm independent hotkeys
#

# terminal emulator
super + Return
        alacritty
```

As well as my `~/.zshrc` to

```
export TERMINAL=alacritty;
```

And reloaded the configuration, as well as rebooting - running `super + enter` still opens termite and doesn't open anything if I uninstall termite

**Comment by gh0stzk** [comment]
Yes remember to reload sxhkdrc with super + esc. You close issue so i assume you fix it.
