### ISSUE TITLE
I have an icon missing on my polybar

### ISSUE THREAD

**Issue by 0x8slash** [gh0stzk/dotfiles#100]
![issue](https://github.com/gh0stzk/dotfiles/assets/17785032/9ba5b1e5-47be-496c-b01b-d946cdd08a56)

**Comment by 9lfayez** [comment]
this is for the media control , u can fix this by going to /path/to/rice/module.ini   , you will find the icons under line 312 ,if icons are already there i think u have a problem with mpd  solution is already solved in the issues section

**Comment by gh0stzk** [comment]
Yes, is the mpd media control module, there are 3 reason you dont see the module in action, first, is all configured but you need to start playing a song, to show for first time the module.
Two, you have no configured the music dir, check the link, https://github.com/gh0stzk/dotfiles/wiki/Firsts-steps-after-installing#the-album-covers-in-notifications-and-widgets
3. There is an error with mpd in your system, you should send the logs here to find out what happens.
