### ISSUE TITLE
cursor theme 

### ISSUE THREAD

**Issue by 9lfayez** [gh0stzk/dotfiles#101]
on login i have to manually set my cursor theme for the desktop only , where can i configure it ,

**Comment by gh0stzk** [comment]
Most people with a WM use the "lxappearance" app to configure their cursor theme, system font, gtk theme, etc.

`sudo pacman -S lxappearance`

**Comment by 9lfayez** [comment]
![ShoT_2023-08-14-01-40-02_1366x768](https://github.com/gh0stzk/dotfiles/assets/127036657/c4b1262f-3d3c-43f4-9e62
![ShoT_2023-08-14-01-40-17_1366x768](https://github.com/gh0stzk/dotfiles/assets/127036657/f4d35f0a-2763-4e39-b246-059e2f9a858d)
-65715819679b)
i already use lxappearance  , when i reboot my system  the cursor theme doesnt appear on desktop i have to manually open lxappearance change the theme twice for it to change there every time

**Comment by 9lfayez** [comment]
i am already using lxappearance , at first i thought it could be an icon cache problem but it isnt , still looking for a solution

**Comment by 9lfayez** [comment]
found it : in bspwmrc uncomment xsetroot -cursor_name left_ptr on line 93

**Comment by 9lfayez** [comment]
Solved
