### ISSUE TITLE
Como puedo quitar las imagenes de mario,kaisen,etc de la terminal?

### ISSUE THREAD

**Issue by ppsegura** [gh0stzk/dotfiles#103]
Hola gh0stzk

Tengo una consulta, soy muy nuevo en linux, es de hecho mi primer distro, pero estoy aprendiendo. Me gustaría quitar las imagenes que aparecen en la terminal cuando la abres, que archivo tendria que modificar? vi que las "imagenes" estan en asciiart, y hay un archivo zfetch, pero nose si ahi deberia de modificar algo o no, gracias de antemano.

Saludos

**Comment by gh0stzk** [comment]
Claro, abre el archivo oculto en tu home, llamado .zshrc y la ultima linea `$HOME/.local/bin/colorscript -r` comentala o borrala y guarda, eso es todo.

**Comment by ppsegura** [comment]
Muchas gracias, funcionó.
