### ISSUE TITLE
Hey, firstly, thx for the installer, you did a great job, but there is something i need to figure out.

### ISSUE THREAD

**Issue by qbnil** [gh0stzk/dotfiles#104]
1) There is a problem with picom, i always have to configure it all over again when booting the system, i checked bspwmrc file but the path to exec file seems to be correct
2) How can i configure the weather info in my polybar? (z0mbie theme)
3) There is no action or pop up window when i click on wifi button in my polybar (is it normal and if it is, how can i configure it so that it spins up the wifi configuration window)

**Comment by qbnil** [comment]
+ there is one more issue with the lock screen, it doesnt get activated at all when clicking on it in polybar, it makes my lenovo logo appear and it just freezes like that

**Comment by gh0stzk** [comment]
Hello. the weather, you need to specify your city or countr here is a link in the wiki how to do it https://github.com/gh0stzk/dotfiles/wiki/Weather-module

The wifi module, yes thats the normal behavior but you can add a click bahavior for example inside rice dir, open modules.ini file, search for `label-connected = "%netspeed%"`
modify it like this `label-connected = "%{A1:nm-cli:}%netspeed%%{A}"` where nm-cli is the app you wanna launch to manage your connection.

About thunar, open ~/.config/bspwm/scripts/ExternalRules
delete or modify from line 46 to 49, you cant move it because that rule specify thunar to open in pseudo_tiled state, you can modify to `floating` or `tiled` or `full_screen` or just remove that lines and will start in tiled.

about lock screen you in z0mbi3 theme? but if lock screen doesnt work, you need to give me logs about error, to try help u, because thats a system error, not referring my dotfiles.

and about picom, you change transparency and then you reboot and transparency is defautl values again? thats normal behavior, if you wanna change permanently the transparency edit ~/.config/bspwm/picom.conf and edit line 81 to 84. 
100 is no transparency.

**Comment by qbnil** [comment]
i just figured the transparency issue, i just moved the config file from one place to another, it somehow worked out for me, i also found out the way about lockscreen problem, i configured betterlockscreen to pop up when clicking on lock icon in polybar

**Comment by qbnil** [comment]
thx for the thunar solution, it worked flawlessly

**Comment by qbnil** [comment]
considering the wifi module you mean which is located at: /rices/z0mbie/bar/eww.yuck ??

**Comment by qbnil** [comment]
;; Network
(defpoll WIFIICON :interval "10s" `scripts/wifi --icon`)
(defpoll NETSTAT :interval "10s" `scripts/wifi --stat`)
there is only that config there

**Comment by qbnil** [comment]
thx for the Weather solution, should've read the wiki first lol

**Comment by qbnil** [comment]
btw, i want to configure some rules for vscode like that: 
 code)
        eval "$consequences"
        [ "$state" ] || echo "desktop=^4 state=fullscreen center=on"
        ;; (but that doesnt seem to work after restarting bspwm)

**Comment by qbnil** [comment]
also for opera: 
opera)
	    eval "$consequences"
	    [ "$state" ] || echo "desktop=^2 follow=on"
	    ;;

**Comment by qbnil** [comment]
because that gets irritating when all the windows get opened on the same workspace lol

**Comment by qbnil** [comment]
and one more question :), i hope you alright spending time for that:)), i want zombie-fetch to always start on boot when i open alacritty (modifying zshrc file), i took a look at neofetch conf but it has nothing to do with a zombie one, how can i do that?

**Comment by qbnil** [comment]
btw, i hope you're okay answering that many questions :) , what's the command for zombie-fetch (neofetch) not the ordinary one, but the one you configured for z0mbie theme

**Comment by qbnil** [comment]
and there is another one bruh: some apps take too long to open up like thunar or firefox, when switched it up with dolphin and opera this issue wasn't the case, do you have any ideas?

**Comment by gh0stzk** [comment]
Hello, the command is zfetch
I dont know the class of vscode and opera but you can get it with the command `xprop`, look for `WM_CLASS(STRING) =` click on the opened vscode window.

For the bar in z0mbi3 rice, search for this part of code in ~/.config/bspwm/rices/z0mbi3/bar/eww.yuck
```
;; Wifi Widgets ;;
(defwidget wifi []
	(box		:orientation "v"  			
	(button		:style "background-image: url('${WIFIICON}');"
				:class "trayicon"
				:tooltip "${NETSTAT}")))
```
Now add this line **:onclick "nm-cli"** and should look like this

```
;; Wifi Widgets ;;
(defwidget wifi []
	(box		:orientation "v"  			
	(button		:style "background-image: url('${WIFIICON}');"
                                :onclick "nm-cli"
				:class "trayicon"
				:tooltip "${NETSTAT}")))
```
Change nm-cli for whatever app you wanna start

**Comment by gh0stzk** [comment]
I have no problem answering your questions.

If you want to use my dots daily it is ok, but my intention is that they are a starting point to learn something new and create or modify the themes

**Comment by qbnil** [comment]
Thx, i've been able to configure the wifi menu to appear on click now, awesome

**Comment by qbnil** [comment]
Thx for helping me out a bunch, you are really an inspiration, i've now made everything work, thx again

**Comment by qbnil** [comment]
but i really forgot to ask one more thing lol, when i run zfetch command it doesnt draw me that zombie, instead it's simple mini-arch logo, must be something with the config, should find yours

**Comment by qbnil** [comment]
i can't lol, there is another question now lol, prolly it's not really about your configs but anyway, when i try running ncmpcpp the music player ig, i get a couple of errors: Reading configuration from /home/archi/.config/ncmpcpp/config...
Reading configuration from /home/archi/.ncmpcpp/config...
Error while processing option "lyrics_directory": option already set (is there any way to fix that?)

**Comment by gh0stzk** [comment]
Oh yes sorry, i forgot i move that script to ascii art just write `colorscript -e zfetch`
Just create a dir called **lyrics** in the ~/.config/ncmpcpp/ directory

**Comment by qbnil** [comment]
zfetch now working as it should be haha thx

**Comment by qbnil** [comment]
about the second one. I still get this error tho: Reading configuration from /home/archi/.config/ncmpcpp/config...
Reading configuration from /home/archi/.ncmpcpp/config...
Error while processing option "lyrics_directory": option already set

**Comment by qbnil** [comment]
probably the problem is that i have two configs for that?

**Comment by qbnil** [comment]
mpd_music_dir = ~/Music
lyrics_directory  = ~/.config/ncmpcpp/lyrics
what's the difference between two of them? (the only one is that in Music dir i got some files but in another one it's blank lol)

**Comment by gh0stzk** [comment]
> probably the problem is that i have two configs for that?

probably yes.

**Comment by gh0stzk** [comment]
> mpd_music_dir = ~/Music lyrics_directory = ~/.config/ncmpcpp/lyrics what's the difference between two of them? (the only one is that in Music dir i got some files but in another one it's blank lol)

mpd music is the dir where your songs are located, that ~/Music dir must be the same in ncmpcpp cnfing file and in mpd config file.

**Comment by gh0stzk** [comment]
mpd is the music player daemon, ncmpcpp is just the music player

**Comment by qbnil** [comment]
alr, i just fixed this renaming the second folder's config

**Comment by qbnil** [comment]
but the problem is that i got no music in it and i can't quit it except just pressing super + q

**Comment by gh0stzk** [comment]
https://github.com/gh0stzk/dotfiles/wiki/Firsts-steps-after-installing#the-album-covers-in-notifications-and-widgets

After you have configured the directories as it says in the link, open ncmpcpp with shift + alt + k then press "u" to update the database and then press "2" your songs should appear and play one. The polybar module should be enabled as well.

**Comment by gh0stzk** [comment]
If there are no songs on that dir nothing will appear.

**Comment by qbnil** [comment]
alr, they all appeared, now how can i quit it back to terminal in another way except pressing the keybind super + q

**Comment by qbnil** [comment]
alr, just pressing q works lol

**Comment by qbnil** [comment]
but do i need to always do those things like updating the db and then pressing 2

**Comment by qbnil** [comment]
i quit and got in again and i had to do that all over again

**Comment by qbnil** [comment]
and i don't get any dunst notifications somehow..

**Comment by qbnil** [comment]
and how can i get rid of no song picture in eww widget, i just want to loop again through the same songs and not get back to music player and play the song

**Comment by qbnil** [comment]
in polybar it says: play something, artist and i can't play next or previous song

**Comment by qbnil** [comment]
alr, i figured everything out, sorry lol, hopefully the last question, is there a way to make switching between songs using that eww widget in polybar smoother because sometimes when i click on the next song arrow it just wont do that, i have to do it twice or even more times in a row

**Comment by qbnil** [comment]
just had to create my own playlist to get rid of updating and pressing 2 everytime haha

**Comment by gh0stzk** [comment]
Open ncmpcpp it should start on window 1 with your played songs, you dont need to press U everythime. From 1 to 8 number keys are different options. in window "2" you can add songs to play list.

In ~/.config/mpd/ mpstate file, that file saves your current play song, time etc.... in ncmpcpp press "r" key and you can activate replay option.

**Comment by gh0stzk** [comment]
> alr, i figured everything out, sorry lol, hopefully the last question, is there a way to make switching between songs using that eww widget in polybar smoother because sometimes when i click on the next song arrow it just wont do that, i have to do it twice or even more times in a row

about that, is eww bug, i cant do anything

**Comment by qbnil** [comment]
alr, that seems to be it then you can close the "issue" (issues lol), if some problems arise, i'll let you, and btw, let me know too if you figure out any ways for fixing that bug
