### ISSUE TITLE
polybar missing on andrea and z0mbi3 rice

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#107]
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/8fbc6eb6-1b8c-423c-be0c-873246f791ad)
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/50c885c2-5520-4120-b15c-7ee57d8707c4)

**Comment by gh0stzk** [comment]
Sure, the eww package failed to install, follow these steps:
Open a terminal and type 
`curl -sS https://github.com/elkowar.gpg | gpg --import -i -`
`curl -sS https://github.com/web-flow.gpg | gpg --import -i -`
finally 
`paru -S eww-x11`

**Comment by 0xN1nja** [comment]
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/4e102e76-dccd-47a2-bc88-bc9b0faacadf)
everything works fine now... thanks!
