### ISSUE TITLE
Reinstalling Firefox CSS

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#108]
Hi, my issue is that I need a hand reinstalling the CSS of Firefox given with this Rice.

When I first installed the dotfiles, I didn't wanted to use the CSS because it removed the icons of the tabs and the pinned tabs, but now I kind of want to get it back to use it myself. Problem is, I can't manage to reinstall it even when putting the folder inside the mozilla folder. 

Do you mind telling me how I can reinstall it ? thanks in advance.

**Comment by gh0stzk** [comment]
Of course, there must be a dotfiles dir in your home, if u deleted, just clone my repo again. Navigate to `~/dotfiles/misc/firefox/ `and copy chrome dir and user.js to **~/.mozilla/firefox/**xxx**.default-release/** directory.

Where **xxx** is random numbers, is different for every user. close firefox and open again.

**Comment by AzhamProdLive** [comment]
Gotcha gotcha, it works now, thanks for the help :+1:
