### ISSUE TITLE
How the hell do i change the keybinds 

### ISSUE THREAD

**Issue by Giuszm** [gh0stzk/dotfiles#109]
No sorry i don't want to press simultaneously 5 keys just to shutdown my pc, i would like to press "Super + P" for shutdown. I would like to open the terminal with just "Super + T" and same goes for closing an app which i want it to be "Super + c". How can i modify this?

**Comment by AzhamProdLive** [comment]
Have you read the wiki, I think you didn't, because as it's explained in the first lines in the "Keyboard shortcut" section : 
``Here is a list of all the hotkeys configured in my dotfiles so you can manage and use bspwm like a pro. Remember that are all configured in the sxhkdrc file.``

**Comment by AzhamProdLive** [comment]
file path is `/home/[yourname]/.config/bspwm/shhkdrc`

**Comment by Giuszm** [comment]
Oh ye indeed I already did and rebooted right after but nothing was changed, even in the shortcut info menu (alt + f1) the shortcuts were the same

**Comment by AzhamProdLive** [comment]
Stupid question ik but have you saved before rebooting ? might be that (taking random guesses ik but if that can help)

**Comment by Giuszm** [comment]
I made sure of saving before rebooting

**Comment by AzhamProdLive** [comment]
There is a wiki page about the Weather Module, you need to make smth with OpenWeather website, I don't know what exactly as I can't check but I can check in some time

**Comment by AzhamProdLive** [comment]
https://github.com/gh0stzk/dotfiles/wiki/Weather-module
This

**Comment by gh0stzk** [comment]
What is your location, and how you put in the conf file that location?

**Comment by Giuszm** [comment]
Ok thanks, i copied the location name using https://openweathermap.org/ .  As for the keybinds, only the super + c change took effect, as for the rest i modified the menu applications to launch with "Super" instead of "Super + @space" and it didn't work. Also if i want to open the terminal with Super + t how can i modify the command correctly?

**Comment by AzhamProdLive** [comment]
Super + t is already a keybind for another feature, so you need to modify the original keybind of Super + t to smth else, and change the command to open the terminal to Super + t

**Comment by gh0stzk** [comment]
You need two keys for sxhkd to work.
super + t is already taken, modify it to make it work

**Comment by Giuszm** [comment]
I see now, thanks for the help both. Your rices are cool but i don't like some of the asciis that show in the terminal, how can i remove/modify them?

**Comment by gh0stzk** [comment]
if u want to remove all the ascii just open the .zshrc file in your home and delete the last line `$HOME/.local/bin/colorscript -r`

If you want to delete only the one you dont like, the ascii aart is in your home/.local/share/asciiart/   just delete de files you want.
