### ISSUE TITLE
Adding Flatpak updates to the Update Module in the rices

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#110]
Hi, i'm making another issue yet again to ask if there is a way to make Flatpak updates thru the update module, as I use flatpak for Steam (because Runtime doesn't work for me lmao)

the command for a Flatpak update is "flatpak update", so i figured that if there is an easy way to do it, that would be nice

**Comment by AzhamProdLive** [comment]
and so if I want to add the line "flatpak update available" in here (cf screenshot), what should I add in the file ?
![ShoT_2023-08-28-06-10-52_1920x1080](https://github.com/gh0stzk/dotfiles/assets/73955243/f47adecf-555a-4c9f-b22a-13f53e555218)

**Comment by gh0stzk** [comment]
its easy to implement, but i never used flatpak, you need de command to list available updates like for example the command "checkupdates" that command will list the available updates. You need the equivalent for flatpak.
