### ISSUE TITLE
Colores de la zsh

### ISSUE THREAD

**Issue by ciggyx** [gh0stzk/dotfiles#111]
Hola buenas tardes, quería preguntarle el como puedo cambiar los colores de mi zsh, ya que cambie la consola a una kitty la cual dentro del archivo $HOME/.config/kitty tengo mis archivos de configuración y no me los toma. Intente borrando zshrc y solo logre que todo se viera feo :( muchisimas gracias por el entorno hermoso!!

**Comment by gh0stzk** [comment]
Hola, el archivo zshrc no tiene nada que ver con los colores de tu terminal. la terminal toma los colores de la configuracion de la  propia terminal, mi configuracion como lo notaste usa alacritty, y cuando cambias un tema todo esta diseñado para que tome nuevos valores y cambie el tema de colores acorde al tema, sin embargo, si tu abres kitty de la forma que sea, y tienes tu configuracion adecuada de esta, deberia tomar tu configuracion. Podrias intentar abrir cualquier otra terminal, y desde esa terminal abrir kitty, y mirar si te arroja algun error..
Los colores que miras en la terminal, los da la terminal y su configuracion, no zsh.

**Comment by ciggyx** [comment]
Pude cambiarlos bien al final. Había visto que en el .zshrc en la parte de prompt se le agregaba un par de iconos y colores para los mismos (por eso decía lo de los colores). Realmente estoy sorprendido de el esfuerzo y cariño que le metiste al entorno!! Un saludo y muchas gracias por contestar.

**Comment by gh0stzk** [comment]
Jajaja entendi que tu problema era otro, que bueno que pudiste resolverlo.
