### ISSUE TITLE
Keybinds donc work for me.

### ISSUE THREAD

**Issue by zqodev** [gh0stzk/dotfiles#112]
Hello, after installing everything that needed, I noticed that I had the style in terminal, firefox theme etc... But when I tried to use the shortcut to open the theme selector it didn’t work. So I do not know what this is due to especially since I did not have any errors during the download.

**Comment by gh0stzk** [comment]
From experience, when Rofi doesn't start, it's usually due to an issue with your language settings. To check this, launch Rofi from a terminal. Open a terminal and copy-paste the following command:

`rofi -show drun -theme $HOME/.config/bspwm/rices/${RICETHEME}/launcher.rasi`

You should see an error related to your locales.

https://wiki.archlinux.org/title/locale

**Comment by zqodev** [comment]
`Rofi-WARNING **: 15:52:58.876: Failed to parse theme: "/home/zqodev/.config/bspwm/rices//launcher.rasi"`

**Comment by gh0stzk** [comment]
change the command in terminal for this: `rofi -show drun -theme $HOME/.config/bspwm/scripts/RiceSelector.rasi`

**Comment by zqodev** [comment]
![image](https://github.com/gh0stzk/dotfiles/assets/123120185/81471cd3-4694-4485-9eb8-6ae453309413)

But i dont see how i can select a theme with this..
(Thanks for taking the time to help me :D)

**Comment by gh0stzk** [comment]
So sorry, just write on a terminal, `RiceSelector` then you must see the themes, choose another one. then press `super + space bar` and/or `alt + space bar`

If u had an error with your locales, and you fix it, now that keybinds must work.

**Comment by zqodev** [comment]
When i open rice selector with commands, it's show the menu but, i got the error:
`Failed to connect to the socket.`

**Comment by gh0stzk** [comment]
But when you press `super + space bar` it works?

**Comment by zqodev** [comment]
nop
