### ISSUE TITLE
how to change the arch logo on terminal

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#113]
i wanna change this logo
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/19dfeb05-0161-4af8-ac73-bb7c18e2a46a)
to this 
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/ad77036c-e51d-4f44-ab7e-dccdf4cf6951)

**Comment by gh0stzk** [comment]
Just open .zshrc file in your home and edit line 83.

**Comment by 0xN1nja** [comment]
Hey @gh0stzk,

Just wanted to drop a quick note of appreciation for your awesome work on the dotfiles. Your dedication in creating and maintaining them is truly commendable. It's amazing how you not only provide the tools to enhance our systems but also spread positivity by responding to every issue with such a positive attitude. Your efforts make the experience even better. Kudos to you for your hard work and kindness <3
