### ISSUE TITLE
Terminal is froze

### ISSUE THREAD

**Issue by zqodev** [gh0stzk/dotfiles#114]
When i open a terminal (alacritty) it's showing nothing, just the terminal with nothing appening, (but all else work)

**Comment by gh0stzk** [comment]
Can you launch alacritty from another terminal and see the output.

**Comment by Delitel-WEB** [comment]
> When i open a terminal (alacritty) it's showing nothing, just the terminal with nothing appening, (but all else work)

Try pressing the keyboard shortcut Ctrl+C when you see the empty terminal.

**Comment by zqodev** [comment]
I launch alacritty from konsole to test, and it's same, that's opening the alacritty terminal but empty and i cant write in it.
I try Ctrl+C but  nothing append.

**Comment by AzhamProdLive** [comment]
https://github.com/alacritty/alacritty/issues/2333

Maybe try to check here for a possible fix, and if possible give us the output of `alacritty -vvv`
