### ISSUE TITLE
Simple way to update the dotfiles than my current way lmfao

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#115]
Hello, I'm making a simple issue (which isn't really an issue, just mostly a question) to ask if there is a way to update and sync the files I have installed with your updates ? 

Currently, I'm doing simple editing of my files with the edits coming from your commits, but it do be taking time and I wondered if there was a way to make that process easier ? Which I would understand if there is none, by the way

**Comment by AzhamProdLive** [comment]
Also quick question about smth else too, how can I remove the fact that Ranger is used as my default File Manager for some applications ? As I don't know how to use it, I kinda wish to get rid of it

**Comment by gh0stzk** [comment]
> Hello, I'm making a simple issue (which isn't really an issue, just mostly a question) to ask if there is a way to update and sync the files I have installed with your updates ?
> 
> Currently, I'm doing simple editing of my files with the edits coming from your commits, but it do be taking time and I wondered if there was a way to make that process easier ? Which I would understand if there is none, by the way

Don't worry, there won't really be any major updates anymore, I was thinking of modifying the eww media player in the pamela and cristina themes, but surely I won't end up doing it. There will only be fixes.

**Comment by gh0stzk** [comment]
> Also quick question about smth else too, how can I remove the fact that Ranger is used as my default File Manager for some applications ? As I don't know how to use it, I kinda wish to get rid of it

I use thunar and I have no problems, what file manager do you use? You can uninstall ranger, or for example in thunar, I right click on some type of file, I click "open with" and that value is saved for everything.

**Comment by AzhamProdLive** [comment]
> > Hello, I'm making a simple issue (which isn't really an issue, just mostly a question) to ask if there is a way to update and sync the files I have installed with your updates ?
> > 
> > Currently, I'm doing simple editing of my files with the edits coming from your commits, but it do be taking time and I wondered if there was a way to make that process easier ? Which I would understand if there is none, by the way
> 
> Don't worry, there won't really be any major updates anymore, I was thinking of modifying the eww media player in the pamela and cristina themes, but surely I won't end up doing it. There will only be fixes.

Okay okay, noted 👍

**Comment by AzhamProdLive** [comment]
> > Also quick question about smth else too, how can I remove the fact that Ranger is used as my default File Manager for some applications ? As I don't know how to use it, I kinda wish to get rid of it
> 
> I use thunar and I have no problems, what file manager do you use? You can uninstall ranger, or for example in thunar, I right click on some type of file, I click "open with" and that value is saved for everything.

I use Thunar too, but for example, with Steam, when I want to browse local files of a games, it opens Ranger instead of Thunar

**Comment by AzhamProdLive** [comment]
This is what I get when I click "Browse Local Directory" on Steam

![Screenshot-02_09_2023-12-41-24](https://github.com/gh0stzk/dotfiles/assets/73955243/68dc4753-b2ad-4c44-9e29-f16f4c2f3544)

**Comment by gh0stzk** [comment]
Try this command `xdg-mime default Thunar.desktop inode/directory` 
or add to file ~/.config/mimeapps.list this line at the bottom `inode/directory=Thunar.desktop`

![Screenshot-02_09_2023-09-07-21](https://github.com/gh0stzk/dotfiles/assets/67278339/14e42c6a-eb52-4598-b591-20e9e816d324)

restart your session and try again..

**Comment by AzhamProdLive** [comment]
Eh, didn't worked :/ weird, but i can live with that kinda, so it's aight
