### ISSUE TITLE
Hide/ Unhide all windows not working

### ISSUE THREAD

**Issue by linoxolus** [gh0stzk/dotfiles#116]
https://github.com/gh0stzk/dotfiles/wiki/Keyboard-Shortcuts#unhide-if-hidden-all-nodeswindows

hide/unhide all windows not working

**Comment by gh0stzk** [comment]
To hide a node (window) place the mouse over the window (focus the window) and press `ctrl + alt + i` and to unhide press `ctrl + alt + u` 

It's my mistake, I need to clarify that part of the keybindings.
