### ISSUE TITLE
NetworkManager loss connection after lid closes laptop and open it

### ISSUE THREAD

**Issue by linoxolus** [gh0stzk/dotfiles#117]
NetworkManager loss connection after lid closes laptop and open it, i ONLY JUST can reconnect with:

```sudo systemctl restart NetworkManager```

if i use ```nmcli dev wifi connect mySSID password myPassword``` i has error:
Error: No network with SSID 'mySSID' found.

**Comment by AzhamProdLive** [comment]
If you get this error, it means that you might be typing the wrong SSID or that you are typing smth else than the SSID in the command

**Comment by linoxolus** [comment]
> If you get this error, it means that you might be typing the wrong SSID or that you are typing smth else than the SSID in the command

I was used this command for connect wifi very much time, and in nmtui mySSID is showing

**Comment by AzhamProdLive** [comment]
Well, I just tried the command and as you can see it in the screenshot, it works, so I don't want to sound mean but double check these : 

- Are you on Wifi or Ethernet ?
- Are you sure you are typing the right SSID ?
- Is your network an hidden network ?
- Have you tried using `wifi-menu` to connect to your wifi ?

![Untitled](https://github.com/gh0stzk/dotfiles/assets/73955243/a1b2927c-1dfd-4e50-8b05-fc221cbf9107)

**Comment by AzhamProdLive** [comment]
Also the fact that you have to restart your NM service is weird, can you send the output of `systemctl status NetworkManager` ?

**Comment by linoxolus** [comment]
> Well, I just tried the command and as you can see it in the screenshot, it works, so I don't want to sound mean but double check these :
> 
> * Are you on Wifi or Ethernet ?
> * Are you sure you are typing the right SSID ?
> * Is your network an hidden network ?
> * Have you tried using `wifi-menu` to connect to your wifi ?
> 
> ![Untitled](https://user-images.githubusercontent.com/73955243/265199252-a1b2927c-1dfd-4e50-8b05-fc221cbf9107.png)

i used true SSID, i only using nmtui, nmcli and i dont know `wifi-menu`

**Comment by AzhamProdLive** [comment]
Copy pasted from the man page of Wifi-menu : 
```DESCRIPTION
       wifi-menu allows to interactively connect to a wireless network on
       INTERFACE using a netctl profile. In case no netctl profile is
       available, one can be generated. If only one wireless interface is
       available, INTERFACE can be omitted.

       wifi-menu is only able to generate netctl profiles for simple network
       configurations. Profiles for more complex configurations must be set up
       manually. See netctl.profile(5) for more information.```
       
I suggest you to use this to try to connect to your wifi, install it with `sudo pacman -S wifi-menu` and run it using `sudo wifi-menu`

**Comment by linoxolus** [comment]
> Also the fact that you have to restart your NM service is weird, can you send the output of `systemctl status NetworkManager` ?

This is output after connection lost:

sudo systemctl status NetworkManager                                                                                                        ─╯
[sudo] password for khai:
● NetworkManager.service - Network Manager
     Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; enabled; preset: disabled)
     Active: active (running) since Sat 2023-09-02 17:44:18 +07; 49s ago
       Docs: man:NetworkManager(8)
   Main PID: 1180 (NetworkManager)
      Tasks: 4 (limit: 4442)
     Memory: 3.9M
        CPU: 258ms
     CGroup: /system.slice/NetworkManager.service
             └─1180 /usr/bin/NetworkManager --no-daemon

Sep 02 17:44:59 HP NetworkManager[1180]: <info>  [1693651499.6385] manager: rfkill: Wi-Fi now disabled by radio killswitch
Sep 02 17:44:59 HP NetworkManager[1180]: <info>  [1693651499.6386] device (wlan0): state change: activated -> unavailable (reason 'none', sys-ifa>
Sep 02 17:44:59 HP NetworkManager[1180]: <info>  [1693651499.6442] dhcp4 (wlan0): canceled DHCP transaction
Sep 02 17:44:59 HP NetworkManager[1180]: <info>  [1693651499.6442] dhcp4 (wlan0): activation: beginning transaction (timeout in 45 seconds)
Sep 02 17:44:59 HP NetworkManager[1180]: <info>  [1693651499.6442] dhcp4 (wlan0): state changed no lease
Sep 02 17:44:59 HP NetworkManager[1180]: <info>  [1693651499.6445] dhcp6 (wlan0): canceled DHCP transaction
Sep 02 17:44:59 HP NetworkManager[1180]: <info>  [1693651499.6445] dhcp6 (wlan0): activation: beginning transaction (timeout in 45 seconds)
Sep 02 17:44:59 HP NetworkManager[1180]: <info>  [1693651499.6445] dhcp6 (wlan0): state changed no lease
Sep 02 17:44:59 HP NetworkManager[1180]: <info>  [1693651499.6700] device (wlan0): set-hw-addr: set MAC address to 7A:C1:C9:65:7D:33 (scanning)
Sep 02 17:44:59 HP NetworkManager[1180]: <info>  [1693651499.6710] manager: NetworkManager state is now DISCONNECTED

**Comment by AzhamProdLive** [comment]
You seems to have an HP laptop, which I don't have, so I can only redirect you to stuff I can find about the same issue as you.
Also, this isn't really an issue related to the rice, afaik, but I can be wrong :thinking: 

https://www.reddit.com/r/archlinux/comments/jtt16n/wifi_gets_disabled_on_laptop_lid_close/
https://bbs.archlinux.org/viewtopic.php?id=283196
https://unix.stackexchange.com/questions/751479/arch-linux-on-laptop-disables-wifi-after-lid-close-open

**Comment by linoxolus** [comment]
> You seems to have an HP laptop, which I don't have, so I can only redirect you to stuff I can find about the same issue as you. Also, this isn't really an issue related to the rice, afaik, but I can be wrong 🤔
> 
> > https://www.reddit.com/r/archlinux/comments/jtt16n/wifi_gets_disabled_on_laptop_lid_close/
> > https://bbs.archlinux.org/viewtopic.php?id=283196
> > https://unix.stackexchange.com/questions/751479/arch-linux-on-laptop-disables-wifi-after-lid-close-open

thanks
