### ISSUE TITLE
theme in termite doesn not work, and thunar.

### ISSUE THREAD

**Issue by Rainy-chan** [gh0stzk/dotfiles#12]
ahoy! The theme in termite does not work for me. and also the theme does not work in the thunar. maybe you use another file manager? Maybe I don't have some apps installed? Write what I might be missing, and will themes be applied to them after installation?

**Comment by gh0stzk** [comment]
Ok first look if u copy "termite" dir in dotfiles to .config dir in your home. 

Thunar theme will not change because my setup will not change gtk theme, i will implement to setup in a few weeks.

But is dracula gtk theme if u wanna download https://draculatheme.com/gtk

**Comment by Rainy-chan** [comment]
heeeey? where are you

**Comment by gh0stzk** [comment]
> heeeey? where are you

Sorry i didnt saw your image, the termite background looks like must be, why you say color didnt change.. maybe you are refering the prompt??? Rainy@archxxx ?? You use bash or zsh? My setup use zsh.
