### ISSUE TITLE
Network usage on Polybar disappeared after reinstallation

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#121]
I initially installed Arch via archinstall and added your dotfiles. Due to mistakenly selecting a separate partition for /home, I had to reinstall Arch manually. After this, the network usage isn't visible on Polybar. I am using NetworkManager. Can you please guide me on which application is responsible for displaying network usage on Polybar?
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/83bc0d47-91c2-42b9-8069-cd9dd0afc1d0)
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/3ce5897c-9190-4976-a349-6c0ea35acdc5)
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/dfa22312-6e08-4dc9-b98d-be02523d21c1)

**Comment by gh0stzk** [comment]
Go to .../.config/bspwm/scripts/system.ini file, chech if your network is the correct one.
Type
`ip link | awk '/state UP/ {print $2}' | tr -d :`
And set the correct one.

**Comment by 0xN1nja** [comment]
It is working now. Thanks!
