### ISSUE TITLE
Problema con eww bar

### ISSUE THREAD

**Issue by Gottbow** [gh0stzk/dotfiles#122]
Una vez terminada la instalación, al momento de cambiar al rice de z0mbi3 o Andrea la barra no se muestra.  Intenté una instalación limpia, pero el problema persiste

**Comment by gh0stzk** [comment]
Seguramente eww no se instalo, abre una terminal y teclea estos comandos

`curl -sS https://github.com/elkowar.gpg | gpg --import -i -`

`curl -sS https://github.com/web-flow.gpg | gpg --import -i -`

`paru -S eww-x11`

**Comment by Gottbow** [comment]
Una vez hecho lo que me dijiste, me aparece este error :/

![Screenshot-15_09_2023-06-10-02](https://github.com/gh0stzk/dotfiles/assets/59183892/d6806deb-64ac-46f4-8e55-56995c82f274)

**Comment by gh0stzk** [comment]
Uhh que pesar con ese paquete de eww tiene fallas seguido, no es un problema de mis dots, pero te voy a subir a mediafire mi binario de eww pesa 7mb creo y lo copias en /usr/bin/ dame unos minutos.

**Comment by gh0stzk** [comment]
https://www.mediafire.com/file/9s2bjewnbm5qqnm/eww/file ahi esta el link. lo copias con sudo.

**Comment by Gottbow** [comment]
okay gracias, entonces despues de copiarlo ya estaría?

**Comment by gh0stzk** [comment]
Asi es, si te funciona podrias cerrar el issue como completado porfavor para saber que quedo listo :)

**Comment by Gottbow** [comment]
okayy, gracias :)
