### ISSUE TITLE
how do i disable the pixel art in terminal

### ISSUE THREAD

**Issue by Th4nhTh4nh** [gh0stzk/dotfiles#126]
Hi! I want to know how to disable this pixel art in terminal when i open it
![Screenshot-21_09_2023-04-11-54](https://github.com/gh0stzk/dotfiles/assets/111641722/e2874aa0-82ee-47b6-9769-2ca024600311)

**Comment by gh0stzk** [comment]
Open ~/.zshrc and delete the last line

`$HOME/.local/bin/colorscript -r`

**Comment by Th4nhTh4nh** [comment]
Closed
