### ISSUE TITLE
eww Error in z0mbi3 theme

### ISSUE THREAD

**Issue by Walker-00** [gh0stzk/dotfiles#128]
When I switch to z0mbi3 theme, eww bar doesn't work.
but when I run manual like `eww -c /home/walker/.config/bspwm/rices/z0mbi3/bar open bar` it work.
eww is already installed by compiling from source with x11 feature.
also tried with restarting wm but doesn't work.

**Comment by gh0stzk** [comment]
Where did you put the eww binary?

You can try editing the file .../.config/bspwm/rices/z0mbi3/bar/eww.yuck
the line 4 remove the path /usr/bin/eww, let just;

`(defvar eww "eww -c $HOME/.config/bspwm/rices/z0mbi3/bar")`

**Comment by Walker-00** [comment]
ahh sorry it work now, I've compiled it with x11 feature and no default feature, when I recompile it with default features it work now. but polybar tray looks a little weird for me. 
![poly_tray](https://github.com/gh0stzk/dotfiles/assets/85013114/50a64ebd-63f7-46bd-9b30-5eddd3ce425c)
It's normal?

**Comment by AzhamProdLive** [comment]
> ahh sorry it work now, I've compiled it with x11 feature and no default feature, when I recompile it with default features it work now. but polybar tray looks a little weird for me.

Yes it is, because eww doesn't have a tray, so it's tricked with the Polybar tray, that's why it looks funky

**Comment by Walker-00** [comment]
ahh ok thanks a lot.
