### ISSUE TITLE
high Cpu resources if reload the bspwm everytime

### ISSUE THREAD

**Issue by spacewonderers** [gh0stzk/dotfiles#129]
Anyone have any idea or having the same issue as me if u keep reloading the bspwm causing the cpu resources go higher? Or is it the normal behaviour? Firstime trying BSPWM.

**Comment by gh0stzk** [comment]
Switching between themes, and the entire environment of my dotfiles, is not heavy. To help you better, could you tell me what you use to start bspwm, a login manager, or xinitrc, what services you run, your hardware. If it's slow for you, try changing the picom.conf file in .config/bspwm/picom.conf on the backend, changing glx to xrender.
If that doesn't solve it in bspwmrc, comment out the picom line and uncomment the one that says picom --legacy-backends and restart bspwm with super + alt + r

Also, if you have modified something, etc., it could be thousands of things, but the environment is light and changing between themes should not cause problems, it should be something else.

**Comment by spacewonderers** [comment]
Yes, there is nothing wrong with switching the themes.  tried the picom --legacy and also xrender but still the same. Only happen if i restart the bspwm super + alt + r and also clean install and setup using your files to test and still happen the same. The cpu resources keep going higher if i keep restart super +alt + r.

**Comment by gh0stzk** [comment]
try `htop` when you note the increment in cpu usage that will show the responsable for that usage.

**Comment by spacewonderers** [comment]
i did htop before and notice the

dbus-daemon --session  --nofork -pidfile --systemd-activation
dbus-daemon --system --nofork -pidfile --systemd-activation

start taking up resources if i restart super + alt + r. Maybe u got any ideas which modules giving the problem. 

[sessiondbus.txt](https://github.com/gh0stzk/dotfiles/files/12786237/sessiondbus.txt)
[systemdbus.txt](https://github.com/gh0stzk/dotfiles/files/12786238/systemdbus.txt)

**Comment by spacewonderers** [comment]
Found the culprit. In my case, its the mpd modules. Disabling the modules work great. Still, i will keep monitoring the status.

**Comment by gh0stzk** [comment]
It's good that you found it, check if you are running the mpd service as a system service or just a user service, it should be a user service.

I have been working on an update to my dots for a month and on the installer. I make sure that the daemon runs in user form and not global.

**Comment by gh0stzk** [comment]
I will close the issue now.
