### ISSUE TITLE
polybar disappears when my cursor is not on it

### ISSUE THREAD

**Issue by boyceta** [gh0stzk/dotfiles#130]
If my cursor is not on it stays for 3 seconds and disappears leaving the spac
e empty. (already reloaded and restarted, it is not hidden with super + h)
![image](https://github.com/gh0stzk/dotfiles/assets/99550408/ed428fca-6127-45e1-9c88-27f05e170698)
![image](https://github.com/gh0stzk/dotfiles/assets/99550408/edf8aad9-653f-4ede-be0f-48e46fdf4a3e)

**Comment by gh0stzk** [comment]
Wooo, this error is new, I had never read it here... I see your images, but that doesn't tell me anything. Could you start the polybar from the terminal, apparently you are in the aline theme, is it happening with the others? or only in that one?

Open your terminal and type

`polybar aline-bar -c $HOME/.config/bspwm/rices/aline/config.ini`

That will show u the errors.
If you use a login manager like lightdm probably in your home there is a file called .xsession-erros, that file contain logs too. But if not, first kill all polybar instances, `killall polybar`, then run polybar from terminal.

**Comment by gh0stzk** [comment]
It is probably some module, color, or font that you added or modified that is causing the problems.

**Comment by boyceta** [comment]
.xsession-errors shows nothing wrong, killall polybar then running from terminal with/without config apparently fixed. thx
