### ISSUE TITLE
Issue with themes with rounded corners 

### ISSUE THREAD

**Issue by carlosonrails** [gh0stzk/dotfiles#131]
Hey, 
First things first congratulations man, your rice is amazing. Easy to install, clean and smooth on my old machine ( intel i3 - 1st gen).
So my problem here is with the corners of polybar I guess. They appeared rounded but inside of a 'black box'. I tested all the themes and it only happens with the rounded corners ones. 

![image](https://github.com/gh0stzk/dotfiles/assets/69637662/93bc2d2e-3296-417c-97bd-1ded76597e27)

![image](https://github.com/gh0stzk/dotfiles/assets/69637662/4257e808-5ca8-4dd8-b7f3-d12d5d7f8c0b)

![image](https://github.com/gh0stzk/dotfiles/assets/69637662/01135a8c-b848-4953-81a6-c9c810ef58b6)

**Comment by gh0stzk** [comment]
That's definitely a problem with picom.
Try this:
Open the file ~/.config/bspwm/**bspwmrc**

Search this line
`picom --config "$HOME"/.config/bspwm/picom.conf`

and comment it, and uncomment the one below the one with the --legacy-backends option

press super + alt + r to restart bspwm and see if it fixes.

If not, you can also try changing the backend from glx to xrender in the picom.conf file within the same bspwm folder.

Unfortunately we all have different hardware, more modern or older, I try to set the most generic configurations but there will always be someone whit picom strange behavior, plus picom as a composer is not the best but it is the only thing for x11.

Every time you make a change in picom, restart bspwm with the aforementioned keys.

**Comment by gh0stzk** [comment]
you need to play with the picom options in picom.conf first try picom with legacy backends and the xrender backend.

**Comment by carlosonrails** [comment]
Okay. Thanks for the explanation. I'll try it out today.

**Comment by carlosonrails** [comment]
Everything going well now. Thanks a lot.
