### ISSUE TITLE
Frozen Desktop

### ISSUE THREAD

**Issue by Alex0os** [gh0stzk/dotfiles#132]
First of all, even though I have this issue, I really liked the installation script and I love the design, you did an amazing job.

The problem that I'm facing is that everything seems to be frozen, I opn the terminal and it appears completely transparent. The apps menu appears but It doesn't response. I don't know If anyone faced this problem but I didn't find anything related on previous issues

![noTerminal](https://github.com/gh0stzk/dotfiles/assets/145087288/81ef531f-1851-4ecb-b039-3bd3d44b43a6)
![Terminal](https://github.com/gh0stzk/dotfiles/assets/145087288/de2cfa07-02e1-4d28-bee3-29be09b82571)
![rofi](https://github.com/gh0stzk/dotfiles/assets/145087288/0ea476d2-7f9a-4f12-bc34-4df171138001)

**Comment by gh0stzk** [comment]
Is that a VM or a real hardware??? Try open picom.conf file located at ~.config/bspwm/ and in the backend, change "glx" for "xrender" reboot and see if is fixed.

**Comment by Alex0os** [comment]
It's a VM. I change it as you said and now it works perfectly, thanks man, I've been testing it at first hand now and It is pretty good. From what it seem it only doesn't work with glx. Can I ask why is that? is it related to the fact that is inside a virtual machine?

**Comment by gh0stzk** [comment]
yeah is a graphic drivers issue with vms, in real hardware works fine. The xrender backend is the fallback, glx is modern, in real hardware and with a modern or relative modern graphic card, you should use glx, but xrender always work fine.

More than that, if u have old pc, in bspwmrc, you should uncomment the picom with --legacy option and comment the default one. picom is a mess but is the only modern and decent composer in x11

**Comment by gh0stzk** [comment]
People should test the different backends with the 2 ways of loading picom, with --legacy and with the default. all of us have different hardware and different setup, so glx and default picon work for most but for other ppl, they need --legacy and xrender...

**Comment by Alex0os** [comment]
changing the title so anyone that have an issue in the future can find the solution faster
