### ISSUE TITLE
Firefox issues.

### ISSUE THREAD

**Issue by Th4nhTh4nh** [gh0stzk/dotfiles#137]
Hi, gh0stzk! 
Every time I open Firefox, it always opens in the 3rd workspace, how do I open it in the current workspace?
Second, I selected the "Open previous windows and tabs" box, but when I restarted Firefox, my selection was deleted.  And Firefox doesn't automatically reopen previous tabs. Is it an error? How do i fix it?

**Comment by gh0stzk** [comment]
Hello, open ~/.config/bspwm/scripts/ExternalRules file, search for this

```bash
firefox|Navigator)
		eval "$consequences"
		[ "$state" ] || echo "desktop=^3 follow=on"
		;;
```
And delete it. is from line 49 to 52, now firefox will no open in the desktop 3

about the other issue, open ~/.mozilla/firefox/XXXXXX.default-release/user.js file, and in the line 23
`user_pref("browser.startup.page", 1);`

change the "1" for a "3"

`user_pref("browser.startup.page", 3);`
