### ISSUE TITLE
Not an issue but a question, because I have too much of them 

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#138]
So, I saw the Massive Update just dropped, so I wanted to say Gratz ! Good to see that some stuff I suggested are in there ;)

My question is : I have the dotfiles already installed and some of the rices are modified for my own usage. If I use the installer script to update it, will it override my already existing rices ? Thanks in advance for the reply :)

EDIT : Also damn, now I have to update my fork too LMAO

**Comment by gh0stzk** [comment]
The installer will create a backup folder in your home, so you have access to your already modified files, but I do recommend using the installer instead of doing it manually, since there are many edited and new files.

**Comment by AzhamProdLive** [comment]
Gotcha gotcha, thanks for the fast reply !
