### ISSUE TITLE
Polybar not showing

### ISSUE THREAD

**Issue by Him7n** [gh0stzk/dotfiles#139]
After I re installed the updated dotfiles the polybar isn't showing up only for the Zombi3 theme...
In the other themes the polybar is showing but not in the Zombi3 one
I am using arch btw .. :)

**Comment by gh0stzk** [comment]
You need to update your eww binary. open a terminal and : 

```
sudo pacman -S rustup --noconfirm
git clone https://github.com/elkowar/eww
cd eww
cargo build --release --no-default-features --features x11
sudo install -m 755 "$HOME/eww/target/release/eww" -t /usr/bin/
```

The z0mbi3 theme dont use polybar, it use eww as a bar. And now to display date formats it uses EWW_TIME internal variable, if u have old eww binary will not support EWW_TIME

**Comment by gh0stzk** [comment]
If u have eww installed from aur, first uninstall it.

**Comment by Him7n** [comment]
It did work out!, thanks a lot man  :)
