### ISSUE TITLE
CHange wallpaper

### ISSUE THREAD

**Issue by chaloski** [gh0stzk/dotfiles#141]
Hello there, i just want to say it is a really good job, but im confused trying to change the wallpaper, and also there is an option to split the terminal windows in 2? thanks in advanced

**Comment by gh0stzk** [comment]
Hello, if you don't want the random wallpaper function and want to put your own.
Open the bspwmrc file located in ~/.config/bspwm/ and look for the line almost to the bottom;

```bash
# Set random wallpaper for actual rice
feh -z --no-fehbg --bg-fill ${rice_dir}/walls
```
You need to chage it to 

`feh --no-fehbg --bg-fill PATH/TO/YOUR/IMAGE`

Or maybe you don't want to use feh, and instead use nitrogen for example, you would need to add the line to bspwmrc

`nitrogen --restore &`

about splitting the terminal into 2, I'm not sure if alacritty has that option but if you want to use the terminal of your choice, install it and open the OpenApps file located in ~/.config/bspwm/scripts/ and change alacritty to the terminal your choice
