### ISSUE TITLE
VPN

### ISSUE THREAD

**Issue by ByyLafe** [gh0stzk/dotfiles#144]
I really like these dot files, but I have a problem with the VPN. Without dotfiles, I can configure a vpn in bspwm from the NetworkManager and then activate it using an arrow button, ethernet manager, with dotfiles this button is no longer present, so I can no longer connect to the VPN, despite it being registered I can no longer activate it. I've managed to connect via an ovpn file, using nmcli, but this only masks my ipv4, there's no shield for ipv6...
Do u have an idea thanks in advance

**Comment by gh0stzk** [comment]
You can try install [network-manager-applet](https://archlinux.org/packages/?name=network-manager-applet) `sudo pacman -S network-manager-applet` and add to autostart programs, for example add to bspwmrc add this line

`nm-applet &` 

And so it will always be active from the beginning in the systray
