### ISSUE TITLE
Alacritty

### ISSUE THREAD

**Issue by PolarisLueur** [gh0stzk/dotfiles#145]
Hello, Alacritty doesn't start, solution?
Thank you for your time.

**Comment by skiss0** [comment]
doesn't work with?
super + Return

**Comment by PolarisLueur** [comment]
It doesn't start with super + return. So, with Rofi, it doesn't start.

**Comment by skiss0** [comment]
then I don't know, someone will answer you

**Comment by PolarisLueur** [comment]
Base installation bspwm, archinstall, bspwm profile, I install rxvt-unicode terminal, then I uninstalled rxvt-unicode, rxvt-unicode starts now.
Excuses, je vais continuer à essayer.

**Comment by gh0stzk** [comment]
open rxvt-unicode terminal and there type alacritty, so terminal will show the error.

**Comment by PolarisLueur** [comment]
Error: there was an error initializing they shaders: Failed linking shader: error: if/then statements not supported by i915 fragment shaders, should hace bee flattened by peephole_select.
Error: "Evento loop terminated with code: 1"

**Comment by gh0stzk** [comment]
Apparently it is an error in the mesa package.

https://github.com/alacritty/alacritty/issues/7260

**Comment by PolarisLueur** [comment]
Merci.
