### ISSUE TITLE
Shortcut error?

### ISSUE THREAD

**Issue by valdiviesod** [gh0stzk/dotfiles#147]
There is an error with the windows+shift+1,2,3... shortcut to move the window to another workspace? It isn't working for me

**Comment by gh0stzk** [comment]
in one on the updates i changed that, now you send focused node (window) with `super + ctrl + shift + {1,9}` and you will follow your window.

if u wanna move a node (window) directionally and following your window `super + ctrl + shift + {left,right}

i forgot to update the wiki shortcuts section, i will do it this wekend.
`

**Comment by gh0stzk** [comment]
from line 168 to 174 you have this code

```
# focus or send to the given desktop
super + ctrl + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}' '--follow'
	
# Send focused Node to workspace directionally
super + ctrl + shift + {Left,Right}
	bspc node -d {prev,next} '--follow'
```

If you dont wanna follow your window just remove the '--follow' at the end of each command.

**Comment by valdiviesod** [comment]
Thanks a lot!
