### ISSUE TITLE
Alacritty font spacing issue

### ISSUE THREAD

**Issue by kthurman59** [gh0stzk/dotfiles#149]
After a recent update of Linux on 11/21/23 the font on Alacritty has a weird irregular spacing issue.  I have re-installed nerd-fonts, but it has not fixed it.  Also, when I use Konsole there is no spacing issue.  It seems that the issue is tied specifically to Alacritty.  Let me know if you have any questions.

![Screenshot-22_11_2023-04-08-05](https://github.com/gh0stzk/dotfiles/assets/25540190/013d5562-5643-48d0-b18d-dfe2a8527636)

**Comment by gh0stzk** [comment]
Yes in the last update, the JetBrains nerd font changed its name, which screwed up some parts of the theme, such as alacritty, the app launcher. I already push a commit to fix that, https://github.com/gh0stzk/dotfiles/commit/ee3724c2400c573fd141c3d83fff6b86939960b7 

If you have not made changes you can clone the repository again and overwrite the files.

If you have already made changes in the link I left you, you can see which files were modified, some of them were Theme.sh, RiceSelector.rasi, there you can see which files were corrected.

name changed from JetBrainsMono Nerd Font to JetBrainsMono NF

**Comment by kthurman59** [comment]
You are my hero!  I LOVE LOVE LOVE what you have made here and I don't know if I can drive a machine daily without it now.  I have broken it a few times on accident and tried to go back to plain Plasma X11 and I felt depressed.  Exceptional work and keep it up.

**Comment by gh0stzk** [comment]
i will pin your issue for some days, since a lot of people will have the same problem as you.
