### ISSUE TITLE
eww bar error, power module exit screen

### ISSUE THREAD

**Issue by juanda3132** [gh0stzk/dotfiles#15]
hi, i have a problem with eww bar in z0mbie, when i hover over the power the bar goes out of the screen.
my resolution is 1360x768
![020221201_085511951_8 4 400](https://user-images.githubusercontent.com/75529640/205072520-78d09f85-f50a-4742-b32f-6370f6a49e2e.jpg)
![020221201_085607405_8 4 400](https://user-images.githubusercontent.com/75529640/205072536-2d8abe7f-dd42-449e-b8a8-eb2ad6ff48a6.jpg)

**Comment by gh0stzk** [comment]
Could you pls reload bspwm with super + alt + r  (super is windows key) and test if happend again. its a problem always? or only sometimes?

**Comment by juanda3132** [comment]
no, it's still the same, the other modules work fine, I don't know what's wrong, I've tried another similar bar and it has the same error with the power module, could it be a lack of dependency?

**Comment by juanda3132** [comment]
I found the same error in the eww repository, does it help?
![Screenshot_20221201-132827_Chrome Beta](https://user-images.githubusercontent.com/75529640/205131766-0d178df4-5161-4e05-bf6f-a089d99c4c1b.png)

**Comment by gh0stzk** [comment]
Yes, its a eww bug but for some people like you, is a problem that happend always, i asked to you because sometimes happend to me with my 1600x900 resolution, but reloading bspwm fixes the problem for me. and it happends to me like 2 times in 6 months so is very random issue. first of all, check if u have the latest eww version. is the 0.4.0.

And let me play with the true and false values in that module and i reply in a few hours.

**Comment by gh0stzk** [comment]
could you pls in ../z0mbi3/bar/eww.yuck in line 172 change the :space-evenly "false" to true, reload and test if happends.

**Comment by juanda3132** [comment]
i tried it, and reload bspwm as you say, it didn't work

**Comment by gh0stzk** [comment]
Well sorry dud, It seems that this issue goes beyond my dotfiles, as the image you posted says, it could be the css, eww, and God knows who else . I can not replicate because it didnt happend to me, i will let this issue open, for the future if someones know what happends.

**Comment by juanda3132** [comment]
ok no problem, still congratulations for the rice, it's amazing, I'm going to remove the power module and use it like that, thanks.

**Comment by gh0stzk** [comment]
> ok no problem, still congratulations for the rice, it's amazing, I'm going to remove the power module and use it like that, thanks.

Hello, i updated the file bspwm/rices/z0mbi3/bar/eww.yuck with a possible fix, could you test if works for you.
