### ISSUE TITLE
Why's there a gap in the left side?

### ISSUE THREAD

**Issue by rew1nter** [gh0stzk/dotfiles#150]
![image](https://github.com/gh0stzk/dotfiles/assets/64508791/8fe3259d-aa09-4d58-b78a-f87dd3104e6e)
I'm noticing this issue for the past few weeks. Can't exactly tell which polybar update did this. Now every round circle module has this issue on the left side.

**Comment by gh0stzk** [comment]
The truth is that I investigated and I have no idea why that gap appeared.

But there is a solution, open the file **~/.config/bspwm/rices/emilia/config.ini**

and edit line 54, where the MesloLGS font is specified.

Change the last values ​​"15;4" to **"16;3"**

It doesn't appear in other themes like "cynthia" or "melissa" or "aline" with the same font.

In fact it is regarding the font size, if you change it to 14 or 16 it works without that gap, however with size 15 as it was, that gap appears... anyway... is easily fixeable and already push a commit. Thanks, i didnt saw that gap, i live in karla theme right now and I hadn't noticed it.

**Comment by rew1nter** [comment]
Yes that fixes the issue!

> Change the last values ​​"15;4" to "16;3"

Does this font change have any effect on the bar UI? Although it looks the same. 

Btw thank you very much for your great work. I'm on KDE actually and use your configs from the repo
