### ISSUE TITLE
Not a bug, a question about  change a color for eww 

### ISSUE THREAD

**Issue by carlosonrails** [gh0stzk/dotfiles#153]
Hey, first of all thanks for give us this amazing config. 
I'd like to change the colors of eww bar on Emilia to Dracula palette. 
So I comment out the previous code and I put this restart the config and also reboot the PC, but it didn't work. 

![image](https://github.com/gh0stzk/dotfiles/assets/69637662/7d09ddcd-431b-4eb9-81bf-4ab26dd50459)

**Comment by gh0stzk** [comment]
Hello, that part of the code that you modified changes the color of the eww widgets (music player, calendar, power off menu, and profile card) · The emilia theme uses polybar and you can change the polybar colors in the ~/.config/bspwm/scripts/colors.ini

![Screenshot-09_12_2023-09-19-52](https://github.com/gh0stzk/dotfiles/assets/67278339/6c00ac7e-caba-457a-b733-b0312e6a6d4c)

But if you want to change the general color appearance of the theme, you must also modify the part that you have already modified.

**Comment by carlosonrails** [comment]
wow, thanks for help. 
I'd like to create a rice myself and push to the repo. Maybe the 13 rice. So I begin change it little by little.

**Comment by carlosonrails** [comment]
Don't know what is happening. I changed the values. Try reload the config and colors stays the same. Kill and init polybar and nothing. Any suggestions?

![image](https://github.com/gh0stzk/dotfiles/assets/69637662/598c68e3-82d5-4c97-826e-78a9af1ac50a)

**Comment by gh0stzk** [comment]
Mmmm how strange, that file controls the color of all the polybars, changing it should change the colors.

Have you made a modification? Are you trying it on a new theme you're doing? did you change something in the config.ini file?

It may sound silly but it has happened to me that I make changes to the files in the cloned directory "~/dotfiles" when in reality the changes should be made to the .config directory

You can kill the polybar process and launch it from a terminal with

polybar -q emi-bar -c ~/.config/bspwm/rices/emilia/config.ini

That will show you information.

The colors are linked to the name of the rice, in this case they are like this ${emilia.bg}

**Comment by gh0stzk** [comment]
![Screenshot-09_12_2023-02-23-09](https://github.com/gh0stzk/dotfiles/assets/67278339/cbce8e9e-704c-464b-80f7-4b024e21835a)

here look i changed the background to red "#ff0000" and works.

**Comment by carlosonrails** [comment]
Hey, tried this after kill polybar 
> polybar -q emi-bar -c ~/.config/bspwm/rices/emilia/config.ini
  
![image](https://github.com/gh0stzk/dotfiles/assets/69637662/89f130b8-1e46-4aad-9b22-9d47eeda4b59)

I had change only the offset y cuz I am in a small laptop. 

I'll try reinstall the config and apply the changes.

**Comment by carlosonrails** [comment]
As I think it was something weird. While talking with you I remember that zombie flavor was broken too. I reinstalled and everything works. Did you update the Rice Selector? The version I had here didn't show up that preview of Rices which looks like amazing by the way!

![image](https://github.com/gh0stzk/dotfiles/assets/69637662/ced33bd2-efec-4965-ba4e-ca045411d717)

**Comment by gh0stzk** [comment]
Yes i updated, when is a important update in the info of the commit i link to the CHANGELOG file, to show whats new.
