### ISSUE TITLE
how do I remove that weird background from battery

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#154]
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/37e3504a-510d-4156-92ef-89e3b80625f3)

**Comment by gh0stzk** [comment]
ohh sorry totally my fault i forgot to push that i will push the update in a few minutes but now to fix that just open the file modules.ini located at ~/.config/bspwm/rices/emilia/ and overwite the battery module for this one:

```
[module/battery]
type = internal/battery
full-at = 99
battery = ${system.sys_battery}
adapter = ${system.sys_adapter}
poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging><label-charging>
format-charging-prefix = " "
format-charging-prefix-font = 2
format-charging-prefix-background = ${emilia.mb}
format-charging-prefix-foreground = ${emilia.red}
label-charging = " %percentage%%"

format-discharging = <ramp-capacity><label-discharging>
format-discharging-background = ${emilia.mb}
format-discharging-foreground = ${emilia.green}
label-discharging = " %percentage%%"

format-full = <label-full>
format-full-prefix = " "
format-full-prefix-font = 2
format-full-prefix-foreground = ${emilia.green}
format-full-prefix-background = ${emilia.mb}
label-full = "%percentage%%"

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-background = ${emilia.mb}
ramp-capacity-foreground = ${emilia.yellow}
ramp-capacity-font = 2

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-background = ${emilia.mb}
animation-charging-foreground = ${emilia.green}
animation-charging-font = 2
animation-charging-framerate = 700
```

**Comment by 0xN1nja** [comment]
No problem, thanks for the quick response! The update fixed the icon's background, but the text's background issue still persists. Is there anything specific I should modify in the configuration to address this? Appreciate your help!
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/e5071606-06ed-4950-a9c0-e1ccc09202fa)

**Comment by gh0stzk** [comment]
oh yes sorry again, in the line 162 `format-charging-prefix-background = ${emilia.mb}` change it to 

`format-charging-background = ${emilia.mb}`

that will cover all the charging background

**Comment by 0xN1nja** [comment]
it didn't work :(
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/8c59f0d4-781a-4717-99d9-33899d8a8907)

**Comment by gh0stzk** [comment]
allright then add below line 163 this:

`label-charging-background = ${emilia.mb}`

**Comment by 0xN1nja** [comment]
nope didn't work
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/026d96e1-f419-416c-a6a4-b5908166a72b)

**Comment by gh0stzk** [comment]
you are charging your laptop? or is disconected?

**Comment by gh0stzk** [comment]
Make sure to reload the theme after make changes to the module.

**Comment by 0xN1nja** [comment]
when I plug in the charger, it works. also im reloading after saving the config file

**Comment by gh0stzk** [comment]
Ahhhh ok is when is discharging okk!! then add this:

`label-discharging-background = ${emilia.mb}`

below _label-discharging = " %percentage%%"_

**Comment by 0xN1nja** [comment]
the issue still persists when the battery is 100%
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/e0280fa2-52bc-496e-a6dd-bc92b78dbf0f)

**Comment by gh0stzk** [comment]
its weird maybe something changes in last polybar updates because the format-background, work for all labels, well.. just add below _label-full = "%percentage%%"_

`label-full-background = ${emilia.mb}`

**Comment by 0xN1nja** [comment]
it is finally working now. thank you so much!
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/354023b8-21ef-4166-a86c-6ddc2ac3ccc0)

config:
```
[module/battery]
type = internal/battery
full-at = 99
battery = ${system.sys_battery}
adapter = ${system.sys_adapter}
poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging><label-charging>
format-charging-prefix = " "
format-charging-prefix-font = 2
format-charging-background = ${emilia.mb}
format-charging-prefix-foreground = ${emilia.red}
label-charging = " %percentage%%"

format-discharging = <ramp-capacity><label-discharging>
format-discharging-background = ${emilia.mb}
format-discharging-foreground = ${emilia.green}

label-discharging = " %percentage%%"
label-full-background = ${emilia.mb}
label-discharging-background = ${emilia.mb}

format-full = <label-full>
format-full-prefix = " "
format-full-prefix-font = 2
format-full-prefix-foreground = ${emilia.green}
format-full-prefix-background = ${emilia.mb}
label-full = "%percentage%%"

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-background = ${emilia.mb}
ramp-capacity-foreground = ${emilia.yellow}
ramp-capacity-font = 2

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-background = ${emilia.mb}
animation-charging-foreground = ${emilia.green}
animation-charging-font = 2
animation-charging-framerate = 700
```

**Comment by 0xN1nja** [comment]
still facing this
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/9be30b3c-3aa9-43ae-8aec-8f15611a1b32)

**Comment by 0xN1nja** [comment]
it seems to work now. thank you so much! <3
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/3056a94f-5574-4567-90c4-1f3656072183)
