### ISSUE TITLE
Incorrect time in polybar

### ISSUE THREAD

**Issue by mangopanda455** [gh0stzk/dotfiles#16]
After installing this config the time in polybar is 5 hours ahead of what it should be in my timezone. Where can I change that?

**Comment by gh0stzk** [comment]
Well that's strange, my settings don't change your system time in any way. but can you tell me in which "rice" that happens to you.

**Comment by mangopanda455** [comment]
This takes place in all rices. like when it's 1:03, the time in the bar shows 6:03

**Comment by gh0stzk** [comment]
Polybar try to read TZ environment variable to determine the timezone, could you please type this command on a terminal and share the reply.

timedatectl status

**Comment by gh0stzk** [comment]
Additionally i search for this issue and it could be a time sync error. check with the command i let u above this part:

System clock synchronized: yes
              NTP service: active
must be on yes if not you could try sudo systemctl enable systemd-timesyncd.service

As i said, my config files, doesnt change your date/time in anyways sp probably your timezone is not set correctly

**Comment by gh0stzk** [comment]
you must read this post in reddit.

https://www.reddit.com/r/Polybar/comments/n0xugw/how_do_i_get_the_time_to_be_in_the_correct_time/
