### ISSUE TITLE
battery icon

### ISSUE THREAD

**Issue by M3m31697** [gh0stzk/dotfiles#160]
In the Emilia theme, the battery icon doesn't show up, but it does in the other themes. Do I need to make any extra settings or configurations?

**Comment by gh0stzk** [comment]
Yes open ~/.config/bspwm/rices/emilia/config.ini

search for this
![Screenshot-10_12_2023-12-54-39](https://github.com/gh0stzk/dotfiles/assets/67278339/c4a19cc1-3ee4-4bae-80d4-5f2592b9b469)

add the battery module wherever u want, in left, center or right section
