### ISSUE TITLE
Thanks for your awesome work 

### ISSUE THREAD

**Issue by allenmagic** [gh0stzk/dotfiles#162]
Hello,

I really like these bspwm themes and thanks for your awesome work to build the beautiful themes for Linux users. But I am not using Arch Linux and the distros based on Arch. So I try to transfer your installer and configs for Debian Linux. 

I really appreciate your work and accomplishments. I think they're amazing.

**Comment by gh0stzk** [comment]
Thank you, I love that you like my rices.

For a while I have wanted to convert the installer for debian and fedora, but I have always used arch and I always end up being too lazy to do so. You know, create the virtual machines, install the systems and search for the packages, many packages have another name in Debian and Fedora, and those that are not there, install the necessary dependencies to compile those packages. and create/modify some scripts that only work with arch, like the one that shows the updates in the polybar... it is not so hard work but it would take me time.
