### ISSUE TITLE
Issues with the Screenshot feature 

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#165]
So, I noticed this when using the screenshot feature some days ago, and my attempts at trying to fix it didn't really worked.

When you try to take a screenshot, but press "Escape" on the keyboard to cancel the operation, it says the same message as if you successfully take a screenshot. Any reason why and maybe is there a possible fix to this ?

**Comment by gh0stzk** [comment]
Yes, in the past I used a script with which you could cancel with esc, mmmm let me look for it.

**Comment by gh0stzk** [comment]
this is the old script:

```bash
#!/usr/bin/env bash

# Author 	 -  z0mbi3
# Source 	 -  https://github.com/gh0stzk/dotfiles
# Maintainer -  z0mbi3.zk@protonmail.com

time=$(date '+%d-%B-%y-%H%M%S')
dir="$(xdg-user-dir PICTURES)/ScreenShots"
file="$time.png"

	if ! [ -d "$dir" ]; then
		mkdir -p $dir
	fi

function notify_view() {
	
	if [[ -e "$dir/$file" ]]; then
		notify-send -i "$dir/$file" -a shot -u low Screenshot "Screenshot Guardado!"
	else
		notify-send -i custom-trash-bin -a shot_icon -u low Screenshot "Screenshot Eliminado"
	fi
}

function pumpumshot() {
	
	cd "$dir" || return
	local bytes
    if [ "$(pgrep -x picom)" ]; then
      bytes="$(maim -u -o -m 4 -d 3 -f png -s -b 2 -c 0.35,0.55,0.85,0.25 -l | base64)"
    else
      bytes="$(maim -u -o -m 4 -d 3 -f png -s -b 2 | base64)" 
    fi
	if [ "$bytes" ]; then
		echo "$bytes" | base64 --decode | tee "$file"
		notify_view
	else
		notify-send -i custom-cancel -a shot_icon -u low Screenshot "Operacion Cancelada."
	fi
}

pumpumshot
```
In the new script it is not possible to cancel the screenshot. In the old script yes because let's say that the resulting file is stored in a temporary file, in the bytes variable, and if the process is completed it is decoded and you have a resulting file.

I don't promise anything but maybe during the week I will rewrite the script to add the function to cancel the screenshot

**Comment by AzhamProdLive** [comment]
Okok, thanks for that, I'll try to come up with something and check if I can modify the script on my end myself
