### ISSUE TITLE
super+h shortcut

### ISSUE THREAD

**Issue by ignatyb** [gh0stzk/dotfiles#17]
i use super+{h,j,k,l} shortcut for focusing the windows, but since super+h is taken for hiding polybar in your rice, i can't really focus anymore, pretty annoying. i've tried to find where this shortcut is located, but I haven't found it. i've checked ~/.config/sxhkd/sxhkdrc and ~/.config/bspwm/bspwmrc. where's it? (great rice btw. i really enjoy using it :))

**Comment by gh0stzk** [comment]
The sxhkdrc config file is in ~/.config/bspwm/ dir. Im glad you enjoy it :)

**Comment by ignatyb** [comment]
thanks! <3
