### ISSUE TITLE
Zsh Starting ASCII art 

### ISSUE THREAD

**Issue by Him7n** [gh0stzk/dotfiles#170]
whenever I open my terminal , sometimes the ascii art that comes on the top comes distorted. also Idont like these art how to I remove them, I tried reading the .zshrc but I couldnot understand it. 
![Screenshot-22_12_2023-11-48-48](https://github.com/gh0stzk/dotfiles/assets/123625528/87dad10a-d559-4fd2-8187-ea1a5dd63226)

**Comment by gh0stzk** [comment]
https://github.com/gh0stzk/dotfiles/wiki/Questions---Answers#how-can-i-disable-the-ascii-art-that-appears-when-opening-a-terminal
