### ISSUE TITLE
How do I open these eww widgets?

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#171]
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/b707c9ab-9aab-4b19-90ba-53dc74834654)

**Comment by gh0stzk** [comment]
The natural way is **right click on the desktop --> widgets**

Each theme has icons to open them from polybar 
![Shot-2023-12-24-072944](https://github.com/gh0stzk/dotfiles/assets/67278339/c337c477-b0d5-4cab-95c6-603bd7ffc495)

**Comment by 0xN1nja** [comment]
is there any command to open that?

**Comment by 0xN1nja** [comment]
nevermind, found it: `eww -c "directory" open --toggle launchermenu`
