### ISSUE TITLE
Fix to update config to new Alacritty 0.13.0

### ISSUE THREAD

**Issue by gh0stzk** [gh0stzk/dotfiles#172]
Last night Alacritty was updated with several important changes, one of them stopped using YAML for its configuration files and migrated to TOML. And that broke the way colors are changed between themes. 

But here you have the fix, but you will have to update some files.

First you need to clone my repository again.
`git clone --depth=1 https://github.com/gh0stzk/dotfiles.git`

Now you need to copy and overwrite some files.

1. The 3 new .toml files inside ~/dotfiles/config/alacritty/ **alacritty.toml fonts.toml rice-colors.toml**  copý them to ~/.config/alacritty/ dir. You can delete the .yaml old files.
2. _~/dotfiles/config/bspwm/scripts/_**OpenApps**   copy to _~/.config/bspwm/scripts/_**OpenApps**
3.  And finally, inside every rice there is a file called **Theme.sh** you need to copy that file from all the rices and  replace it respectively.

_~/dotfiles/bspwm/rices/_**RICENAME**_/Theme.sh_  --> _~/.config/bspwm/rices/_**RICENAME**_/Theme.sh_
You need to do it with all themes..

**Comment by AzhamProdLive** [comment]
Small comment since it's related to the subject : 

Since the update and changes of Alacritty, there is a small white flash that happens everytime you do an action that fails (example : clicking left when you are already on the left-side of the line), is that related to your dotfiles or is it an alacritty thing ?

**Comment by gh0stzk** [comment]
Its the bell sound, it happends to me too, if you execute this command a bell sounds `paplay /usr/share/sounds/freedesktop/stereo/dialog-error.oga` 

if you dont like it just remove it form config, open alacritty.toml file in .../.config/alacritty and delete this

```
[bell]
animation = "Linear"
duration = 20
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"] }
```

**Comment by gh0stzk** [comment]
its a flash animation, thats why it suppose to be. In alacritty wiki:

```
animation = "Ease" | "EaseOut" | "EaseOutSine" | "EaseOutQuad" | "EaseOutCubic" | "EaseOutQuart" | "EaseOutQuint" | "EaseOutExpo" | "EaseOutCirc" | "Linear"

    Visual bell animation effect for flashing the screen when the visual bell is rung.

    Default: "Linear"

but if you wanna the sound but no the flash just set to 0 the duration. duration = 0
```
