### ISSUE TITLE
white curves on arch logo in emilia's polybar

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#175]
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/8ad5cfeb-dd72-4f15-bb79-194aa7e7057a)
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/603a519d-9a94-47da-97c2-47cc70bb5ebe)

**Comment by gh0stzk** [comment]
Yep its a picom and polybar "issue" nothing we can do.

**Comment by 0xN1nja** [comment]
alright

**Comment by 0xN1nja** [comment]
is there any way to orient the arch logo vertically upwards?
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/3eba19b4-e000-4ede-be34-5f381ad35f5f)

**Comment by gh0stzk** [comment]
yes you need to check first if that module uses a specific font, in this case yes:

```
[module/launcher]
type = custom/text

label = 󰣇
label-foreground = ${emilia.blue-arch}
label-font = 4

click-left = OpenApps --menu
click-right = RiceSelector
```

it uses label 4, now in config.ini search for this line

`font-3 = "Material Design Icons Desktop:size=15;4"`

change the last 4 for 3 or 2 15;2

**Comment by 0xN1nja** [comment]
thanks!
