### ISSUE TITLE
How to add new themes to Theme Selector?

### ISSUE THREAD

**Issue by adilzaheem** [gh0stzk/dotfiles#176]
How to add my own themes and rices to the rice selector, can u give a summarized guide?

**Comment by gh0stzk** [comment]
I've just been making a guide for that for a while.

Summarized

Inside the folder ../.config/bspwm/rices/ copy any theme folder, and paste it inside that same folder, rename it whatever you want, for example, "darktheme" and that's it, the theme will be available and functional in the rice selector.

Now you have the base, now you just have to edit the Theme.sh, config.ini and modules.ini files with the look you want to give it.

Other files that you have to edit and add would be colors.ini and HideBar. which are located in .config/bspwm/scripts

But one of the most important or the most important is Theme.sh which is the one that controls most of the aspect of the theme,

**Comment by adilzaheem** [comment]
Sorry for the late reply. Thank you very much for the explanation <3
