### ISSUE TITLE
Theme change for other applications

### ISSUE THREAD

**Issue by kinjar1988** [gh0stzk/dotfiles#177]
This is not a issue. But i have not enough knowledge about linux. I have successfully installed your dotfiles and it' works perfect. Now I want to know how can I change theme for thunar and vscode or pamac etc according to bspwm theme. by default thunar and pamac or other applications showing light mode by default.

I want to make it look like as per other applications in rice.

Please guide me.

**Comment by gh0stzk** [comment]
you can try this:
https://github.com/gh0stzk/dotfiles/issues/169#issuecomment-1866433691

**Comment by kinjar1988** [comment]
ok. Thank you for your quick response.
