### ISSUE TITLE
script Failed to copy the files

### ISSUE THREAD

**Issue by Antwa-sensei253** [gh0stzk/dotfiles#178]
Hi there, I have encountered certain file permission issues, as shown in the photo.
 I have a copy of the previous installation of the script (some corrupt files in the copy), and after copying it to the config files to.config, it worked but with missing bars and malfunctioning settings. The bspwm files are gone after running the script. I tried a number of solutions, but none of them worked.
![WhatsApp Image 2024-01-12 at 21 20 28_421819f6](https://github.com/gh0stzk/dotfiles/assets/101470839/24958577-c037-414c-966a-ea5444ddcc44)

**Comment by gh0stzk** [comment]
Hello, try clone the repo from zero again if there is a **dotfiles** directory in your home delete it and `git clone --depth=1 https://github.com/gh0stzk/dotfiles.git`

then enter to dotfiles/ and copy manually all the directories, the ones in dotfiles/config to ~/.config
 
and check your installation for wrong permissions in the home directory.

**Comment by Antwa-sensei253** [comment]
That worked for me, thanks man.
