### ISSUE TITLE
How to change homepage Firefox

### ISSUE THREAD

**Issue by thien0709** [gh0stzk/dotfiles#179]
When I change the homepage in Firefox's settings. But when I shut down and reopened the browser, the homepage didn't change and it stayed :/home/z0mbi3/.local/share/startup-page/index.html.

**Comment by gh0stzk** [comment]
Hello, open ~/.mozilla/firefox/xxxx.default-release/user.js and deletre from line 21 to 26, restart firefox and you are done, the configs you made from firefox options will now take affect.

![Shot-2024-01-14-094316](https://github.com/gh0stzk/dotfiles/assets/67278339/54200fd3-414c-4710-9cea-407ee72bc1c6)

**Comment by thien0709** [comment]
I fixed it. thank you very much
