### ISSUE TITLE
/home/owl/.local/bin/colorscript: line 50: declare: 5357%0: division by 0 (error token is "0")

### ISSUE THREAD

**Issue by makssxwq** [gh0stzk/dotfiles#180]
when i open alacritty i have the error: /home/owl/.local/bin/colorscript: line 50: declare: 5357%0: division by 0 (error token is "0")

**Comment by gh0stzk** [comment]
What a strange and weird error, do you use an old zsh or bash versions?

i do not know whats thats error but you do this:
open .zshrc file in your home and delete the last line `$HOME/.local/bin/colorscript -r`

**Comment by makssxwq** [comment]
Thank u for fast answer
