### ISSUE TITLE
Stuck on tty 

### ISSUE THREAD

**Issue by edanbigw** [gh0stzk/dotfiles#182]
I just finished installing the script on fresh install arch based distro (EndeavourOS with no desktop), but I still boot into tty, what should I do?

**Comment by AzhamProdLive** [comment]
Like stated in this issue : https://github.com/gh0stzk/dotfiles/issues/89#issuecomment-1629544070

You need a login manager in order to boot inside BSPWM, henceforth why you keep booting into TTY

**Comment by gh0stzk** [comment]
Yes as @AzhamProdLive said you need a login manager.

`sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings`

Then activate it, `sudo systemctl enable lightdm` and then reboot.

**Comment by edanbigw** [comment]
Thank y'all it's work! Greeting from Indonesia, I really love it 🔥
