### ISSUE TITLE
[Suggestion] Wifi menu with rofi

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#183]
Hello, it is I, here for another suggestion n this time it's about a Wifi Menu when clicking on the wifi icon. 

I have found [this repo](https://github.com/zbaylin/rofi-wifi-menu) while browsing Github, and I thought it would be a great addition to my dotfiles. Problem is, no matter how much I've tried, I can't manage to make it work. 

So I suggest this here maybe hopping I could get help with it or even add it into this repo :D

**Comment by AzhamProdLive** [comment]
Found a more uptodate and maybe more fitting one to use ? https://github.com/ericmurphyxyz/rofi-wifi-menu

**Comment by gh0stzk** [comment]
The first one is old and outdated, the second one is a fork of the first one that does work and the last one is the one I would choose.

At this moment I don't have any PC with WiFi capability, in one or two months I will have a new laptop PC and I will be able to experiment and test. I will keep it in mind to think about it, since the vast majority of people use networkmanager to connect, I don't use it because it is bloated for my taste. But, in one or two months when I can test the last 2 repos I will see if I add it.

**Comment by AzhamProdLive** [comment]
> The first one is old and outdated, the second one is a fork of the first one that does work and the last one is the one I would choose.

Yea that's what I noticed too, henceforth why I suggested the other two

> At this moment I don't have any PC with WiFi capability, in one or two months I will have a new laptop PC and I will be able to experiment and test. I will keep it in mind to think about it, since the vast majority of people use networkmanager to connect, I don't use it because it is bloated for my taste. But, in one or two months when I can test the last 2 repos I will see if I add it.

I do be having a laptop with WiFi capability and networkmanager on it, so if you need a hand to test stuff I would be happy to (instead of waiting the two months, but that's up to you)

**Comment by gh0stzk** [comment]
The problem with these types of functions to add to dotfiles is that adding them means modifying an important aspect of your system, "how you connect to the internet." It involves installing NetworkManager and leaving it active, running at the same time with the method you use to connect, be it iwd, systemd-network, etc., which would imply the malfunction of your connection. Or somehow in the installer detect the tools you use to connect, deactivate them and activate networkmanager.

And my intention is not to modify any aspect of the system configuration.

Or simply add the function with rofi from one of those repos, and if you use wifi and networkmanager then fine, if not simply the rofi menu will not show you anything. Which may be the most viable solution.

I'm going to try it tonight for the second repo, and I'll decide whether to leave it or not.

**Comment by AzhamProdLive** [comment]
I was kind of thinking the same thing (for the 2nd option), as to ensure global system compatibility. I tried to do it myself to do something like that but my knowledge is too limited and not big enough that I can't manage to make anything with it. 

I barely managed to make nm-applet work when you click on the wifi icon, but it crashes the bar when you do so I'm back to square one myself
