### ISSUE TITLE
Suggestion time : Rofi-games menu, for the gamers out there

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#186]
So, I've been having fun since a little while on some games, but because I'm lazy asf and that i'm an Arch User btw (sarcasm involved), I've searched ways to improve my user experience, and I've found something named [Rofi-games](https://github.com/Rolv-Apneseth/rofi-games). So I wanted to try it and imported it on my system and I do have to admit that it looks good 

https://github.com/gh0stzk/dotfiles/assets/73955243/904a48bc-62cb-4ceb-838b-ca68e07139dc

In order to use it at full potential, you have to make themes for it, but as you can see, the default theme is great.

So I decided to modify my sxhkdrc to add this app as a shortcut : 
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/3df50a8f-626e-4c49-86ce-6088d4ea0846)

Now, my suggestion would be, is it a good idea to add it in this repo ? So people can enjoy this too ? and working on rasi themes ? Even thought I want to try if you can use the already existing themes from this repo, which I'm gonna try right now and do another comment when done

**Comment by AzhamProdLive** [comment]
https://github.com/gh0stzk/dotfiles/assets/73955243/b6ddb114-6e3c-4a7a-83fc-9c831f0353e4

Just tried with the RiceSelector.rasi theme, and this actually does work, so I think, if I am allowed, I could add this thing inside my fork and do a pull request for it tonight, except if you want to study the subject

**Comment by AzhamProdLive** [comment]
Okay it wasn't as easy as I thought, adding the ```$HOME/.config/bspwm/scripts/RiceSelector.rasi``` actually kind of breaks it, making a SEGFAULT when you select a game 

I do not know if it's from the code or the fact that I use the RiceSelector .rasi file, but it works without the line for the theme (aka -theme games-default)

**Comment by gh0stzk** [comment]
Yeah looks great! When i did the new rice selector and wallpaper selector, i thought to made this game selector, will take the images from steam library, but in this machine i dont play, yes i wanna do it but i need you to be my tester.

about de rofi and wifi, i almost done, i will send you the files to you to test.

**Comment by AzhamProdLive** [comment]
> Yeah looks great! When i did the new rice selector and wallpaper selector, i thought to made this game selector, will take the images from steam library, but in this machine i dont play, yes i wanna do it but i need you to be my tester. 

Sure i'm down for that, do you have any other platforms like Discord or Matrix or any other socials to communicate ? Would be easier for deep testing instead of just normal Github comments imo :p

> about de rofi and wifi, i almost done, i will send you the files to you to test.

:+1:
