### ISSUE TITLE
Issue with editing some colors

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#187]
Hi, I am making an issue instead of commenting in my other ticket to distinct the two issues.

I have been doing some edits to my rices, and I've been having a small struggle with the colors of some scripts. 
When I reboot or change rices, my jgmenurc config get overwritten by a default config, which is a little bit annoying having to set the colors by hands again

My question would be, how can i remove that thing that setup jgmenu automatically when switching rices ? Thanks in advance

**Comment by AzhamProdLive** [comment]
Also, everytime I switch Rices, my Discord crashes, am I the only one facing this issue or is this a common issue ?

**Comment by gh0stzk** [comment]
You need to set the jgmenu colors in every Theme.sh inside each rice

Search for this function:
```bash
# Set jgmenu colors for Aline
set_jgmenu_colors() {
	sed -i "$HOME"/.config/bspwm/jgmenurc \
		-e 's/color_menu_bg = .*/color_menu_bg = #f4f5f8/' \
		-e 's/color_norm_fg = .*/color_norm_fg = #51576d/' \
		-e 's/color_sel_bg = .*/color_sel_bg = #e5eafe/' \
		-e 's/color_sel_fg = .*/color_sel_fg = #51576d/' \
		-e 's/color_sep_fg = .*/color_sep_fg = #212121/'
}
```

**Comment by gh0stzk** [comment]
> Also, everytime I switch Rices, my Discord crashes, am I the only one facing this issue or is this a common issue ?

I do not use discord sorry.

**Comment by AzhamProdLive** [comment]
> I do not use discord sorry.

All good dw dw 👍
