### ISSUE TITLE
Music deamon error while starting mpd.service

### ISSUE THREAD

**Issue by kirillgerke** [gh0stzk/dotfiles#19]
Hello gh0stz,
First, let me say thanks for this cool rices!
I did try to use them for a clean Arch install and get this non-obvious error:

○ mpd.service - Music Player Daemon
     Loaded: loaded (/usr/lib/systemd/user/mpd.service; enabled; preset: enable>
     Active: inactive (dead) since Fri 2022-12-30 00:56:05 MSK; 30s ago
       Docs: man:mpd(1)
             man:mpd.conf(5)
    Process: 1108 ExecStart=/usr/bin/mpd --systemd (code=exited, status=1/FAILU>
   Main PID: 1108 (code=exited, status=1/FAILURE)
        CPU: 60ms

Dec 30 00:56:05 archlegion systemd[1094]: Starting Music Player Daemon...
Dec 30 00:56:05 archlegion mpd[1108]: Ignoring the 'pid_file' setting in system>
Dec 30 00:56:05 archlegion mpd[1108]: server_socket: bind to '0.0.0.0:6600' fai>
Dec 30 00:56:05 archlegion mpd[1108]: exception: Failed to open '/var/lib/mpd/m>
Dec 30 00:56:05 archlegion mpd[1108]: exception: Failed to open database plugin>
Dec 30 00:56:05 archlegion systemd[1094]: mpd.service: Main process exited, cod>
Dec 30 00:56:05 archlegion systemd[1094]: mpd.service: Failed with result 'exit>

Any idea how to fix that? I applied all changes from the troubleshooting section (btw, there is no /scripts/weather in /config/bspwd/rices/z0mbi3/dashboard)

Many thanks in advance,
Kirill

**Comment by gh0stzk** [comment]
Hello, about weather scripts, the location is ~/.config/bspwm/scripts   there you can found the 2 weather scripts used in some rices.

About mpd, could be a lot of things, but first could you pls create manually a file called mpd.pid  in ~/.config/mpd/ 

and did you enable the service?

systemctl --user enable mpd.service
systemctl --user start mpd.service

**Comment by kirillgerke** [comment]
Hello gh0stzk,
Thank you for prompt reply!
Yes, i did enable the mpd service.
Also, as you suggested i created the file. The problem persists though:

× mpd.service - Music Player Daemon
     Loaded: loaded (/usr/lib/systemd/user/mpd.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sat 2022-12-31 12:40:20 MSK; 10s ago
       Docs: man:mpd(1)
             man:mpd.conf(5)
    Process: 2137 ExecStart=/usr/bin/mpd --systemd (code=exited, status=1/FAILURE)
   Main PID: 2137 (code=exited, status=1/FAILURE)
        CPU: 63ms

Dec 31 12:40:20 archlegion systemd[1120]: Starting Music Player Daemon...
Dec 31 12:40:20 archlegion mpd[2137]: Ignoring the 'pid_file' setting in systemd mode
Dec 31 12:40:20 archlegion mpd[2137]: server_socket: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
Dec 31 12:40:20 archlegion mpd[2137]: exception: Failed to open '/var/lib/mpd/mpd.db': No such file or directory
Dec 31 12:40:20 archlegion mpd[2137]: exception: Failed to open database plugin; Can't create db file in "/var/lib/mpd": Permission denied
Dec 31 12:40:20 archlegion systemd[1120]: mpd.service: Main process exited, code=exited, status=1/FAILURE
Dec 31 12:40:20 archlegion systemd[1120]: mpd.service: Failed with result 'exit-code'.

If i look at /var/lib/mpd it seems to be ok:
drwxr-xr-x  3 mpd     mpd     4096 Dec 30 00:22 mpd

Feels like something went wrong during installation may be... Not sure.
Any ideas?
Kirill

**Comment by kirillgerke** [comment]
So, i still have no idea what the problem was, but i managed to run bspwm by installing lightgdm - it starts and runs smoothly now.
![mynerdvana](https://user-images.githubusercontent.com/38157235/210173366-7ea9b732-bcb7-457c-ae75-c259adf853ca.jpeg)
Now will have some time to manage connecting the laptop to the external monitor with all the rices working as desired:)
Many thanks!

**Comment by gh0stzk** [comment]
Sorry forgot about the file "socket" in ~/.config/mpd/  create it. 
Disable all mpd services first.
You must enable mpd service without sudo "systemctl --user enable mpd.service" first kill all mpd process, "killall mpd" then "systemctl --user start mpd.service"
 In ncmpcpp if it says connected, you are done. then add songs.
If nothing helps, try read mpd wiki in archwiki, this page helps me firts time i configured mpd.
