### ISSUE TITLE
help :open bspwm i am try to add keybindings and they are not working or i am doing some think worng plz you can add example for add ing keybindings 

### ISSUE THREAD

**Issue by slPOOJI** [gh0stzk/dotfiles#190]

**Comment by adilzaheem** [comment]
To add keybindings in bspwm, you need to edit the sxhkdrc file, which is where you define the hotkeys for your window manager. You can find this file in ~/.config/bspwm/sxhkdrc. 

The syntax of the sxhkdrc file is simple. You just need to write the key combination followed by the command you want to execute. For example, if you want to launch a terminal with Super + Enter, you can write:


```bash
super + Return
  alacritty
```


You can use modifiers like super, alt, ctrl, shift, and hyper to create different combinations. You can also use brackets, commas, and semicolons to group keys or commands. For example, if you want to switch between desktops with Super +  ctrl + {1-9}, you can write:

```bash
super + ctrl +  {1-6}
  bspc desktop -f {1-6}
```

You can also use special keys like XF86AudioMute, XF86MonBrightnessUp, Print, Escape, and so on. 

To reload the sxhkdrc file, you can use Super + Alt + r, which is the keybinding for that.

**Comment by gh0stzk** [comment]
A common cause of keybindings not working is that they are repeated.

Another error they usually have with my dotfiles is that they edit the file ~/.config/sxhkd/sxhkdrc

And mine is located in the bspwm directory.

Whenever you edit sxhkdrc remember to reload the daemon with the Super + esc keys

And so it's a little difficult to help you, put your file, what you're trying to add.

**Comment by slPOOJI** [comment]
ok. thanks now keybindings are ok  but  i want add vscode to key keybindings
# Open webbrower
super + alt + v
      OpenApps --visual-studio
but it did not work  plz help

**Comment by adilzaheem** [comment]
```bash
super + alt + v
  code
```
