### ISSUE TITLE
Polybar config

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#191]
I'm using an old fork of your rice; in your `rices/*/modules.ini`, `content` has been replaced by `label` in your latest commit:

Old:
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/b2ba6912-9cf1-4197-91e4-8a5c918c7b8a)
New:
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/4e909d28-3db0-4ba1-871e-b23c7c64c555)

So what's the difference in them?

**Comment by adilzaheem** [comment]
The content-foreground and content-background options set the default colors for the entire module. They apply to the whole module output, unless overridden by other options. For example, if you set content-foreground = #ffffff and content-background = #000000, your module will have white text on a black background. 

The label-foreground and label-background options set the colors for specific labels within the module. Labels are parts of the module output that have a specific meaning or function, such as showing the volume level, the date, or the battery percentage. You can use these options to make certain labels stand out or match a certain theme. For example, if you set label-foreground = #ff0000 and label-background = #00ff00, your label will have red text on a green background. 

I assume this is how it works, lets wait for the owner to confirm the same.

**Comment by gh0stzk** [comment]
It has to do with the internal changes made by polybar 3.6 -> 3.7

https://github.com/polybar/polybar/releases/tag/3.7.0

_custom/text: The content setting and all its properties are deprecated in favor of format with the same functionality. (https://github.com/polybar/polybar/pull/2676)_

Migration examples https://polybar.readthedocs.io/en/stable/migration/3.7/index.html
