### ISSUE TITLE
System tray (Stalonetray or Polybar default one)

### ISSUE THREAD

**Issue by gh0stzk** [gh0stzk/dotfiles#192]
Hey, I want to ask you if you like the current stalonetray, or do you prefer the one that comes included with polybar.

Currently the only disadvantage of stalonetray is that it cannot be configured with percentages, which means that in your different resolutions it does not appear properly aligned where it should go. And you need to edit it manually.

On the other hand, the disadvantage of polybar is that it arranges the icons within the systray horizontally, and in resolutions lower than 1600x900 it could even cut the bar if you had many icons inside the systray.

I plan to change back to the one with polybar by default, but if it turns out that you like stalonetray better, then I'll leave it as is.

Which one do you prefer?

**Comment by adilzaheem** [comment]
Hey there! First off, thanks for your hard work on both stalonetray and polybar. It's clear that a lot of thought and effort has gone into both. As for your question, I've been using stalonetray and while I appreciate its standalone nature and flexibility, the lack of percentage-based configuration has been a bit of a challenge, especially when switching between different screen resolutions. 

On the other hand, I've also used polybar and really enjoyed the integrated system tray and the horizontal arrangement of icons. It's aesthetically pleasing and works well on larger screens. However, I can see how it could be an issue on lower resolutions if the system tray is crowded with icons.

Given these experiences, my vote would go to polybar. Despite its potential limitation on lower resolutions, I find its integrated nature and advanced customization options provide a more seamless user experience. However, I do hope there could be some improvements on how it handles a crowded system tray on lower resolutions.

Again, thanks for your amazing work and for considering our feedback!

**Comment by AzhamProdLive** [comment]
Hello there, For me, my answer would be kinda biased, as I've been trying to use them both more often, but it feels lacking a bit

Both would work for me, the issue I have with Polybar is that you cannot have a lot of icons, because I would just cut them out of the bar, and with stalonetray, the fact that you can move the tray by accident is annoying.

Overall, I think the experience with both are okay, but maybe trying to find a already existing script and see if we can adapt it to the dotfiles could be interesting too ? Just a thought

**Comment by AzhamProdLive** [comment]
I see the update has been pushed to the repo for the switch back to Polybar tray, so I did push it on my computer, but it seems that it doesn't work, even after copying the files right, I do not have the tray popping up on my system, maybe I did something wrong, but I'm not sure.
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/8ed270a4-4a1d-40e7-9f65-47ad6613e603)
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/08da547c-3d48-444a-840d-101892ab2b24)
( for a deeper and better readability, the complete files are available [here](https://github.com/AzhamProdLive/dotfiles/tree/master/rices/pamela)

**Comment by gh0stzk** [comment]
Are you sure the stalonetray process is dead?

```bash
pkill stalonetray
sudo pacman -Rns stalonetray
```
reload bspwm `super + alt + r`

**Comment by gh0stzk** [comment]
I just install a new arch VM to test some things and tray is fine.
![Shot-2024-02-22-135333](https://github.com/gh0stzk/dotfiles/assets/67278339/9ac6536d-6e57-49c1-8e5f-ea9c2591b5f2)

**Comment by AzhamProdLive** [comment]
> Are you sure the stalonetray process is dead?
> 
> ```bash
> pkill stalonetray
> sudo pacman -Rns stalonetray
> ```
> reload bspwm `super + alt + r`

I think I killed it, but I'm gonna check when I get back on comp

**Comment by AzhamProdLive** [comment]
Indeed, it wasn't killed, I thought I did, it works now, thanks!
