### ISSUE TITLE
Pantalla negra luego de login

### ISSUE THREAD

**Issue by devaacode** [gh0stzk/dotfiles#193]
Que tal como va?, primero que nada muchas gracias por la gran aportación de temas y el haberlo hecho un script para todos, se agradece mucho.
Cuento con 2 problemas, cuando termina de instalar todo, me pide que configure algunas cosas desde la consola tocando las teclas "a" "b" "c" "1" etc, soy bastante nuevo en esto así que no se que tocar y dejo todo default, luego de eso mi terminal queda sin hacer nada como si hubiera finalizado la instalación, probé dejarlo un rato largo así y nada, así que luego de eso hago reboot y selecciono bspwm en el login, pongo mi contraseña y luego la pantalla queda en negro y lo único que puedo ver es el puntero, ya no se que hacer, tuve que borrar la maquina virtual y volver a instalar todo como por 6ta vez :(
Mientras escribia esto estaba instalando de nuevo y me salio esto ahora 
![image](https://github.com/gh0stzk/dotfiles/assets/136910459/a7db6998-8eb0-44d6-a975-98b9452e6e0d)
Y esta es la pantalla donde no se que poner entonces dejo todo default
![image](https://github.com/gh0stzk/dotfiles/assets/136910459/7577b164-b3bc-4d86-9501-8e530f901fc7)
luego de eso queda asi y no pasa nada
![image](https://github.com/gh0stzk/dotfiles/assets/136910459/069b4a63-171d-4d6e-b999-1e2de1e81173)

**Comment by gh0stzk** [comment]
El problema principal es que por alguna razon no se estan copiando mis dotfiles a tu carpeta ~/.config   el otro problema relacionado a zsh es por lo mismo no se copio la configuracion zsh.

Pueden ser muchas cosas, pero primero hay que asegurarse que la carpeta dotfiles en tu home se clono correctamente desde mi repositorio, haz  `cd dotfiles/config `dentro deberias de ver distintas carpetas como bspwm, mpd, etc. Despues serciorate que tu carpeta .config exista en tu home haz `ls -la ` deberias tener la carpeta .config listada.

Como instalaste arch? con archinstall ??? tienes otro entorno como kde, xfce? si lo tienes, entra a el, y solo copia las respectivas carpetas, las que estan en dotfiles/config copialas dentro de .config en tu home, las que estan en misc, dentro de .local en tu home... 

es extraño que haya fallado el instaldor, tal vez tienes un problema de permisos que impide que se copie, o no se pueden ser varias cosas. Generalmente el instaldor no falla, son ordenes simples como copiar de una carpeta a otra, y no me ha llegado mas gente con tu problema, por eso deduzco que podria ser un problema de permisos.

De ultima, borra el directorio dotfiles que esta en tu home y vuelve a clonar el instaldor `curl https://raw.githubusercontent.com/gh0stzk/dotfiles/master/RiceInstaller -o $HOME/RiceInstaller` haz `chmod +x RiceInstaller` y ejecutalo con `./RiceInstaller`

Precisamente hoy en la mañana en una laptop vieja que tengo, instale los dotfiles para probar unas cosas y no me dio algun error.

**Comment by devaacode** [comment]
Primero que nada muchas gracias por responder tan rapido, se agradece, yo cuando instale el arch me hizo seleccionar un tema por asi decirlo y elegí el kde, me estuve fijando y en mi carpeta home no se creo ninguna carpeta llamada dotfiles pero si hago ls -la si tengo la carpeta .config, es un error bastante raro, cuando use vmware en lugar de virtual box el otro dia me funciono todo bien pero unos dias despues yo hice un formateo de mi pc y borre sin querer todo el vmware y desde ahi que no puedo arreglar este error, ahora mismo estoy probando con los comandos que me dijiste a ver que pasa.

**Comment by gh0stzk** [comment]
Estas en una maquina virtual?? 
Bueno como sea puedes usar de manera grafica el programa arandr. `sudo pacman -S arandr`

**Comment by devaacode** [comment]
dale muchas gracias <3
