### ISSUE TITLE
rofi-games implementation project

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#194]
Hello there, to make some follow-up on #186, I started working on implementing rofi-games into the dotfiles here (I'm working on the fork I've made).

For that, I searched for a way to add rofi-games in the installer scripts, and I had two roads: Building the rofi-games repo from the source, or using the AUR to download it. As a fellow Arch btw user, I decided to download it from the AUR, making this addition in the RiceInstaller script (can be seen here : https://github.com/AzhamProdLive/dotfiles-fork/blob/af8ecc326f2558d71a601cecfaba432d2e33804b/RiceInstaller#L310 )
```
# Installing rofi-games
	if command -v "rofi -modi games" >/dev/null 2>&1; then
		printf "\n%s%srofi-games is already installed%s\n" "${BLD}" "${CGR}" "${CNC}"
	else 
		printf "\n%s%sInstalling rofi-games, this should take a moment.%s\n" "${BLD}" "${CBL}" "${CNC}"
		paru -S rofi-games --skipreview --noconfirm
	
	fi
```
After that, I've added a way to open the game panel with OpenApps ( can be seen here : https://github.com/AzhamProdLive/dotfiles-fork/blob/af2621a07f3e7d9b0c7b20cf31f8301b0897ca05/config/bspwm/scripts/OpenApps#L77 ) 
```
# My widgets
	  --games)
	    rofi -modi games -show games -theme games-default
	    ;;
```
Then, I've added the shortcut in sxhkdrc ( can be seen here : https://github.com/AzhamProdLive/dotfiles-fork/blob/9ad3e47a950c4969e8baca50c1c70e12fcbd445e/config/bspwm/sxhkdrc#L24 ) 
```
# Games Menu
super + alt + @space
    OpenApps --games
```
I am making this issue before doing a PR in order to fix the possible errors in the script and make sure everything that I did is correct, so, feel free to tell me if I did anything wrong 👍

**Comment by gh0stzk** [comment]
Does this launcher support steam?

**Comment by AzhamProdLive** [comment]
It does, when I did the showcase in #186, you could see the games starting from steam when rofi-games was used

**Comment by AzhamProdLive** [comment]
My main concern is on the RiceInstaller script, because i'm not sure if it's the right way to do it or not, as I don't have my Linux laptop with me atm

**Comment by gh0stzk** [comment]
Currently I have been busy with various dotfile things, returning to using the polybar systray, fixing visual errors in some themes, eww it was updated and I need to see if it doesn't break something, and if so fix it, getting the launcher ready for the wifi that you had told me about and creating a simple but professional environment with neovim.
And i don't forget the game launcher, I'm working on this script, which is not mine, I'm modifying it, and adapting it to x11

```bash
#!/usr/bin/env sh

# set variables
ScrDir=`dirname "$(realpath "$0")"`
source $ScrDir/globalcontrol.sh
ThemeSet="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/themes/theme.conf"
RofiConf="${XDG_CONFIG_HOME:-$HOME/.config}/rofi/steam/gamelauncher_${1:-5}.rasi"


# set steam library
if pkg_installed steam ; then
    SteamLib="${XDG_DATA_HOME:-$HOME/.local/share}/Steam/config/libraryfolders.vdf"
    SteamThumb="${XDG_DATA_HOME:-$HOME/.local/share}/Steam/appcache/librarycache"
    steamlaunch="steam"
else
    SteamLib="$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/config/libraryfolders.vdf"
    SteamThumb="$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/appcache/librarycache"
    steamlaunch="flatpak run com.valvesoftware.Steam"
fi

if [ ! -f $SteamLib ] || [ ! -d $SteamThumb ] ; then
    dunstify "t1" -a "Steam library not found!" -r 91190 -t 2200
    exit 1
fi


# check steam mount paths
SteamPaths=`grep '"path"' $SteamLib | awk -F '"' '{print $4}'`
ManifestList=`find $SteamPaths/steamapps/ -type f -name "appmanifest_*.acf" 2>/dev/null`


# set rofi override
elem_border=$(( hypr_border * 2 ))
icon_border=$(( elem_border - 3 ))
r_override="element{border-radius:${elem_border}px;} element-icon{border-radius:${icon_border}px;}"


# read intalled games
GameList=$(echo "$ManifestList" | while read acf
do
    appid=`grep '"appid"' $acf | cut -d '"' -f 4`
    if [ -f ${SteamThumb}/${appid}_library_600x900.jpg ] ; then
        game=`grep '"name"' $acf | cut -d '"' -f 4`
        echo "$game|$appid"
    else
        continue
    fi
done | sort)


# launch rofi menu
RofiSel=$( echo "$GameList" | while read acf
do
    appid=`echo $acf | cut -d '|' -f 2`
    game=`echo $acf | cut -d '|' -f 1`
    echo -en "$game\x00icon\x1f${SteamThumb}/${appid}_library_600x900.jpg\n"
done | rofi -dmenu -theme-str "${r_override}" -config $RofiConf)


# launch game
if [ ! -z "$RofiSel" ] ; then
    launchid=`echo "$GameList" | grep "$RofiSel" | cut -d '|' -f 2`
    ${steamlaunch} -applaunch "${launchid} [gamemoderun %command%]" &
    dunstify "t1" -a "Launching ${RofiSel}..." -i ${SteamThumb}/${launchid}_header.jpg -r 91190 -t 2200
fi


```

It works for Steam and there is no need to install anything or make changes to the installer. I'll try that aur pack anyway, and I'll let you know.

**Comment by AzhamProdLive** [comment]
gotcha gotcha, in the meantime i'll keep the files ready on my fork for a possible PR

**Comment by AzhamProdLive** [comment]
Gotcha gotcha, one more kid to add to the rice party 🤣

**Comment by AzhamProdLive** [comment]
Just checked the script, and I feel like smth doesn't feel right to me
these lines
```
SteamLib="${XDG_DATA_HOME:-$HOME/.local/share}/Steam/config/libraryfolders.vdf"
SteamThumb="${XDG_DATA_HOME:-$HOME/.local/share}/Steam/appcache/librarycache"
steamlaunch="steam"
```   

For it to work, it would mean that the user would have installed Steam by the package manager and without changing the path afterwards, maybe trying to get the ``${HOME}/.steam`` content instead would be more helpful ?

**Comment by gh0stzk** [comment]
@AzhamProdLive this works for you??? could you please test it.
https://github.com/P3rf/rofi-network-manager

**Comment by AzhamProdLive** [comment]
> @AzhamProdLive this works for you??? could you please test it.
> https://github.com/P3rf/rofi-network-manager

Currently at work, I'll try this when I get back home 👍

**Comment by gh0stzk** [comment]
There is no hurry, when you can ;)

**Comment by AzhamProdLive** [comment]
So I managed to make it work, but I can't manage for the life of me to make the thing open the script on click 
the whole script works when I run it with terminal, but when I try to add it to my modules.ini on pamela's rice, it doesn't let me click it when I used the old config

So I've put the new config of the repo you linked, which made it clickable, but doesn't open at all either, I pushed the updates I did to my repo, if you want to check it out 

(also this script shows the name of the wifi hotspot & the private IPv4 IP, jsyk)

**Comment by gh0stzk** [comment]
> So I managed to make it work, but I can't manage for the life of me to make the thing open the script on click the whole script works when I run it with terminal, but when I try to add it to my modules.ini on pamela's rice, it doesn't let me click it when I used the old config
> 
> So I've put the new config of the repo you linked, which made it clickable, but doesn't open at all either, I pushed the updates I did to my repo, if you want to check it out
> 
> (also this script shows the name of the wifi hotspot & the private IPv4 IP, jsyk)

I just wanna know if the scripts runs fine, i tested in a laptop and the script do nothing, There is a closed issue for this in that repo, but re installing the SO is not a solution. https://github.com/P3rf/rofi-network-manager/issues/21

Your problems are a PATH problems, if you move the wifi scripts to .../bspwm/scripts/ just use:
`%{A1:rofi-network-manager.sh:}<ramp-signal> <label-connected>%{A}` should work

**Comment by gh0stzk** [comment]
> same! I have never been able to add or edit things to be clickable, for example cpu_bar I tried to make it run `btop` on click but never been clickable

```
[module/cpu_bar]
type = internal/cpu

interval = 0.5

format = <label>
format-prefix = "%{A1:alacritty -e btop:}%{A}"
format-prefix-font = 2
format-prefix-background = ${color.grey}
format-prefix-foreground = ${color.red}

label = "%{A1:alacritty -e btop:}%percentage%%{A}"
label-background = ${color.grey}
```
This works for me, it makes the icon clickeable and the percentage too. if you are launching a terminal program, remember to specify the terminal, if not, that will not work.

**Comment by AzhamProdLive** [comment]
> I just wanna know if the scripts runs fine, i tested in a laptop and the script do nothing, There is a closed issue for this in that repo, but re installing the SO is not a solution. https://github.com/P3rf/rofi-network-manager/issues/21
> 
> Your problems are a PATH problems, if you move the wifi scripts to .../bspwm/scripts/ just use:
> `%{A1:rofi-network-manager.sh:}<ramp-signal> <label-connected>%{A}` should work


Gotcha gotcha, yes the scripts runs fine otherwise, it shows everything that has to show on my network, and it's actually pretty cool looking

**Comment by gh0stzk** [comment]
Nice, today i will made another try in old laptop with networkmanager. if it works, i will adapt it to make color change in all themes.
for now i have a lot of work, in my real work, and in free time now im creating 3 new themes. i have 2 finished now. the difficult part are the wallpapers xD find beautiful wallpapers that match the colorscheme of the theme is not easy lol.. Dracula, everforest, and catppuccin machiatto will be the new color schemes for the new themes. In last commit i change cynthia colorscheme to kanagawa dragon colors.

![Shot-2024-02-29-083121](https://github.com/gh0stzk/dotfiles/assets/67278339/66b103df-7fea-4023-b736-2eab370a6703)

The dracula new rice.

**Comment by AzhamProdLive** [comment]
> The dracula new rice.

Damn, that looks cool ngl
> Nice, today i will made another try in old laptop with networkmanager. if it works, i will adapt it to make color change in all themes.
for now i have a lot of work, in my real work, and in free time now im creating 3 new themes. i have 2 finished now. the difficult part are the wallpapers xD find beautiful wallpapers that match the colorscheme of the theme is not easy lol.. Dracula, everforest, and catppuccin machiatto will be the new color schemes for the new themes. In last commit i change cynthia colorscheme to kanagawa dragon colors.

Gotcha gotcha

**Comment by AzhamProdLive** [comment]
@ahmedrowaihi Do you have this issue of the Network module in the bar being a little bit off ? Might just be me but it looks bigger than the rest : 
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/7709a9f3-3e8b-4bf9-be93-dcd34bd125c5)

**Comment by AzhamProdLive** [comment]
no not that, i'm talking about the icon in the bar

**Comment by AzhamProdLive** [comment]
pamela
I'm just gonna try to see if it's because of the new logo, hangon

**Comment by AzhamProdLive** [comment]
Mhmmm, we indeed don't have the same logo, let me try with the old one

**Comment by AzhamProdLive** [comment]
Yea I found it already, thanks for pointing it out though :+1:

**Comment by AzhamProdLive** [comment]
@gh0stzk 
Dunno if you plan to, but I was planning of trying to add the rofi-network-menu on every rices on the fork i have of this repo (not my personal one, the 1to1 copy of it) and to make a pull request in order to give you less work to do with and focus on more features, if you are down for it ?

**Comment by gh0stzk** [comment]
> @gh0stzk Dunno if you plan to, but I was planning of trying to add the rofi-network-menu on every rices on the fork i have of this repo (not my personal one, the 1to1 copy of it) and to make a pull request in order to give you less work to do with and focus on more features, if you are down for it ?

Unfortunately I couldn't get it to work on my laptop, it is a bug which exists in the creator's repo https://github.com/P3rf/rofi-network-manager/issues/21 , but he couldn't solve it and I don't think he would be interested in fixing it, so I won't add it to the repo, sorry.

**Comment by AzhamProdLive** [comment]
It's fine, don't worry 👍

**Comment by Malcnez** [comment]
hello, i know this might not be the place for this but i can't find where i can change the size of the icons and numbers on the bar, my monitor is kinda big and everything is too small.

**Comment by gh0stzk** [comment]
> hello, i know this might not be the place for this but i can't find where i can change the size of the icons and numbers on the bar, my monitor is kinda big and everything is too small.

In each theme "~/.config/bspwm/rices/ there is a config.ini file, look for the part where the fonts are defined and there you can change the font size.

**Comment by AzhamProdLive** [comment]
Hello there @gh0stzk, it is I, with yet another question and maybe feature. 
As I've seen in the changelog of February : 
> The neovim configuration is returned to the dotfiles
    I try to make a simple but powerful neovim configuration, of course if you are a pro with neovim and have your own super pro configuration, you will not be interested, remember that your neovim folder was moved to the backup folder, so you can return to it without problems. But if you start with neovim, you will surely be able to get a lot of juice out of it.

my question would be, for those people that already got a neovim config, why not make the code asks you if you want or not to copy the neovim config from this rice ? I'm already searching a little bit on the subject and I'm trying to make something work about it, but if you think it would be a futile idea, I can drop it ofc 

(Also I need to rename this issue, because it doesn't only relate to rofi-games but on the dev side of the project lmao)

**Comment by gh0stzk** [comment]
It is a good idea, I had already thought about it, to add the question for neovim and for the Firefox theme. Yeah will add it asap.

By the way, in two days my new laptop will arrive, and I will be able to make it work the script for the wifi, and efficiently test the battery modules for the eww bars. and finally work in the rofi game launcher.

**Comment by AzhamProdLive** [comment]
Just modified the neovim part of the script both for Backup and copying : 

```
########## ---------- Backup files ---------- ##########

logo "Backup files"
read -p "Do you want to backup your nvim files? (y/n): " download_nvim
printf "Backup files will be stored in %s%s%s/.RiceBackup%s \n\n" "${BLD}" "${CRE}" "$HOME" "${CNC}"
sleep 10

[ ! -d "$backup_folder" ] && mkdir -p "$backup_folder"

for folder in bspwm alacritty picom rofi eww sxhkd dunst polybar ncmpcpp ranger zsh mpd paru; do
    if [ -d "$HOME/.config/$folder" ]; then
        if mv "$HOME/.config/$folder" "$backup_folder/${folder}_$date" 2>> RiceError.log; then
            printf "%s%s%s folder backed up successfully at %s%s/%s_%s%s\n" "${BLD}" "${CGR}" "$folder" "${CBL}" "$backup_folder" "$folder" "$date" "${CNC}"
            sleep 1
        else
            printf "%s%sFailed to backup %s folder. See %sRiceError.log%s\n" "${BLD}" "${CRE}" "$folder" "${CBL}" "${CNC}"
            sleep 1
        fi
    else
        printf "%s%s%s folder does not exist, %sno backup needed%s\n" "${BLD}" "${CGR}" "$folder" "${CYE}" "${CNC}"
        sleep 1
    fi
    if [[ $download_nvim == "y" || $download_nvim == "Y" ]]; then
        # Download nvim
        if [ -d "$HOME/.config/nvim" ]; then
            if mv "$HOME/.config/nvim" "$backup_folder/nvim_$date" 2>> RiceError.log; then
                printf "%s%snvim folder backed up successfully at %s%s/nvim_%s%s\n" "${BLD}" "${CGR}" "${CBL}" "$backup_folder" "$date" "${CNC}"
                sleep 1
            else
                printf "%s%sFailed to backup nvim folder. See %sRiceError.log%s\n" "${BLD}" "${CRE}" "${CBL}" "${CNC}"
                sleep 1
            fi
        else
            printf "%s%snvim folder does not exist, %sno backup needed%s\n" "${BLD}" "${CGR}" "${CYE}" "${CNC}"
            sleep 1
        fi
    fi
done
```

```
########## ---------- Copy the Rice! ---------- ##########

logo "Installing dotfiles.."
read -p "Do you want to install nvim? (y/n): " install_nvim
printf "Copying files to respective directories..\n"

[ ! -d ~/.config ] && mkdir -p ~/.config
[ ! -d ~/.local/bin ] && mkdir -p ~/.local/bin
[ ! -d ~/.local/share ] && mkdir -p ~/.local/share

for dirs in ~/dotfiles/config/*; do
    dir_name=$(basename "$dirs")
    # If the directory is nvim and the user doesn't want to install it, skip this loop
    if [[ $dir_name == "nvim" && $install_nvim != [Yy] ]]; then
        continue
    fi
    if cp -R "${dirs}" ~/.config/ 2>> RiceError.log; then
        printf "%s%s%s %sconfiguration installed succesfully%s\n" "${BLD}" "${CYE}" "${dir_name}" "${CGR}" "${CNC}"
        sleep 1
    else
        printf "%s%s%s %sconfiguration failed to been installed, see %sRiceError.log %sfor more details.%s\n" "${BLD}" "${CYE}" "${dir_name}" "${CRE}" "${CBL}" "${CRE}" "${CNC}"
        sleep 1
    fi
done
```

what do we think about it ?

**Comment by gh0stzk** [comment]
> Just modified the neovim part of the script both for Backup and copying :
> what do we think about it ?

Thank you for the code i will add it in a moment, i already test your code, i just made 2 changes:

Asking people twice for the nvim configuration leads to errors, imagine that they answer yes to the question to backup, but they answer no, to the question to copy my configuration, they would have to manually move their personal configuration. Or worse yet, they respond that they do not want to make a backup, but yes to copy my nvim configuration, their configuration would be deleted and no backup.

The solution would be to ask a single question, I already modified it.

The other change in:

`if [[ $download_nvim == "y" || $download_nvim == "Y" ]]; then`

I think it could be `if [[ $download_nvim == [Yy] ]]; then` to simplify the code. just like you do in the copy rice code.

And the if statment for $download_nvim should be outside the for loop, because if not, the result is something like:

bspwm backeup sucesfully
nvim backeup sucesfully
alacritty backeup sucesfully
nvim backeup sucesfully
mpd backeup sucesfully
nvim backeup sucesfully
...

I will made some changes and push it today.

**Comment by AzhamProdLive** [comment]
Gotcha gotcha, I mostly made this as a draft to get something to work with, so make sure to edit it if you need to ahah

> I think it could be if [[ $download_nvim == [Yy] ]]; then to simplify the code. just like you do in the copy rice code.

Good point, it is true that I didn't thought about it and did two conditionals to make sure both of em are taken into account

 > And the if statment for $download_nvim should be outside the for loop, because if not, the result is something like:
 
Oh, I see I see, I didn't noticed that when testing it on my end, I might be a little bit blind lol

**Comment by gh0stzk** [comment]
Ok i already push the new code to riceinstaller. I will close this topic now, so as not to continue mixing ideas and topics. And I left the game launcher and the Wi-Fi module pending.

**Comment by gh0stzk** [comment]
@AzhamProdLive i already did it, from this repo https://github.com/firecat53/networkmanager-dmenu?tab=readme-ov-file

I just finishing add colors to all rices and is done.

![Shot-2024-03-22-221610](https://github.com/gh0stzk/dotfiles/assets/67278339/a81dd594-bbde-44db-99e2-81bd55e4ba56)

**Comment by AzhamProdLive** [comment]
> @AzhamProdLive i already did it, from this repo https://github.com/firecat53/networkmanager-dmenu?tab=readme-ov-file
> 
> I just finishing add colors to all rices and is done.
> 
> ![Shot-2024-03-22-221610](https://github.com/gh0stzk/dotfiles/assets/67278339/a81dd594-bbde-44db-99e2-81bd55e4ba56)
> 

Let's gooo, can't wait to try it 👍

**Comment by gh0stzk** [comment]
@AzhamProdLive ok i push the update.

**Comment by AzhamProdLive** [comment]
> @AzhamProdLive ok i push the update.

Currently pushing it on my own fork
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/2e20444b-74ea-47a4-9fae-c4d6a62d2502)

About to try and give my feedback

**Comment by AzhamProdLive** [comment]
> > @AzhamProdLive ok i push the update.
> 
> Currently pushing it on my own fork
> ![image](https://github.com/gh0stzk/dotfiles/assets/73955243/2e20444b-74ea-47a4-9fae-c4d6a62d2502)
> 
> About to try and give my feedback

Just tried the new NM, the wifi icon looks not centered lol ![IMG_20240324_220503256~2.jpg](https://github.com/gh0stzk/dotfiles/assets/73955243/af858454-1b05-483b-80b2-6d49e34d735c)
