### ISSUE TITLE
Zsh autofill even when I don't ask about it

### ISSUE THREAD

**Issue by FastDust11** [gh0stzk/dotfiles#196]
For example I try to write "sudo" and it autocomplete as in picture bellow, without me pressing any button: 
![Shot-2024-02-26-100328](https://github.com/gh0stzk/dotfiles/assets/38609216/b270ead1-9699-4d60-a82a-2204304cd71f)
Then I can only delete to "sudo mkf" and I'm writing from it:
![image](https://github.com/gh0stzk/dotfiles/assets/38609216/52769130-5caa-4527-936f-a10a695c249d)
The problem repeats in many other examples, making using zsh very annoyign. Clearing history helps but only for a short time.
It almost new install where I definitely do not change anything connected to zsh, but I'm new to linux so maybe somehow I did something unintentionally or something working different then I understand it. Would be glad if You could help or give me some advice. I think of commenting .zshrc, but it's little overwhelming and don't know where I should start. I would like to save as much functionality as I could, cause when it was working it was working great ;).  

Thanks for great dotfiles

**Comment by FastDust11** [comment]
Just to make sure that You understand me correctly more example: 
![image](https://github.com/gh0stzk/dotfiles/assets/38609216/9abd7d0a-ccb8-469d-99f6-623d3b72f8c5)
(I only wrote sda)
Later I cannot delete it and start writing from it: 
![image](https://github.com/gh0stzk/dotfiles/assets/38609216/8b743cdc-5c9a-402a-a9dd-8154d9eadec0)

**Comment by gh0stzk** [comment]
That's strange, did you previously have a zsh configuration?

I understand the error, it should only show you the suggestion but it should not be filled in automatically.

I have never received issues about this failure, you are the first, this afternoon I will look for information about this and I will try to help you.

If you have much problems try change to bash for now, `chsh -s /usr/bin/bash`

**Comment by FastDust11** [comment]
Yup it's new linux arch installation by this guide "https://www.youtube.com/watch?v=68z11VAYMS8&t=14s&pp=ygUSbGludXggYXJjaCBpbnN0YWxs" after that I installed Your dotfiles. I got some problem cause "startx" won't work but my friend helped me with that doing some linux magic, don't think it's connected and I don't think I installed zsh at that time. 

After that  zsh work without problems, I used system for few days, did some changes in gui, installed few basic apps but nothing special connected to zsh in my knowledge. Only problem I encounter is that in split screen with zsh on one side in longer commands it stop showing what I writing showing blank space but I just move zsh to other desktop so it's not so big deal, don't know it's connected to my main problem tho. 

The problem does not always occur it's kinda random (maybe more often when I copy past something, but it's not a rule) when it does I have to close terminal and open new one to fix it.

"In .config/zsh/ delete zcompdump and zshistory files. then open a terminal and write source zsh" after that I get some strange response showed lower: 
source zsh
[2] 5057
/usr/bin/zsh:1: no such file or directory: ^@^A^@^@^@\M-`p^A^@^@^@^@^@@^@^@^@^@^@^@^@\M-^X\M-]^N^@^@^@^@^@^@^@^@^@@^@8^@^M^@@^@^[^@^Z^@^F^@^@^@^D^@^@^@@^@^@^@^@^@^@^@@^@^@^@^@^@^@^@@^@^@^@^@^@^@^@\M-X^B^@^@^@^@^@^@\M-X^B^@^@^@^@^@^@^H^@^@^@^@^@^@^@^C^@^@^@^D^@^@^@^X^C^@^@^@^@^@^@^X^C^@^@^@^@^@^@^X^C^@^@^@^@^@^@^\^@^@^@^@^@^@^@^\^@^@^@^@^@^@^@^A^@^@^@^@^@^@^@^A^@^@^@^D^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^Xb^A^@^@^@^@^@^Xb^A^@^@^@^@^@^@^P^@^@^@^@^@^@^A^@^@^@^E^@^@^@^@p^A^@^@^@^@^@^@p^A^@^@^@^@^@^@p^A^@^@^@^@^@\M-YN^K^@^@^@^@^@\M-YN^K^@^@^@^@^@^@^P^@^@^@^@^@^@^A^@^@^@^D^@^@^@^@\M-@^L^@^@^@^@^@^@\M-@^L^@^@^@^@^@^@\M-@^L^@^@^@^@^@\M-h\M-!^A^@^@^@^@^@\M-h\M-!^A^@^@^@^@^@^@^P^@^@^@^@^@^@^A^@^@^@^F^@^@^@\M-0j^N^@^@^@^@^@\M-0z^N^@^@^@^@^@\M-0z^N^@^@^@^@^@\M-$q^@^@^@^@^@^@p\M-(^A^@^@^@^@^@^@^P^@^@^@^@^@^@^B^@^@^@^F^@^@^@\M-hv^N^@^@^@^@^@\M-h\M-^F^N^@^@^@^@^@\M-h\M-^F^N^@^@^@^@^@\M-`^A^@^@^@^@^@^@\M-`^A^@^@^@^@^@^@^H^@^@^@^@^@^@^@^D^@^@^@^D^@^@^@8^C^@^@^@^@^@^@8^C^@^@^@^@^@^@8^C^@^@^@^@^@^@P^@^@^@^@^@^@^@P^@^@^@^@^@^@^@^H^@^@^@^@^@^@^@^D^@^@^@^D^@^@^@\M-^H^C^@^@^@^@^@^@\M-^H^C^@^@^@^@^@^@\M-^H^C^@^@^@^@^@^@D^@^@^@^@^@^@^@D^@^@^@^@^@^@^@^D^@^@^@^@^@^@^@S\M-etd^D^@^@^@8^C^@^@^@^@^@^@8^C^@^@^@^@^@^@8^C^@^@^@^@^@^@P^@^@^@^@^@^@^@P^@^@^@^@^@^@^@^H^@^@^@^@^@^@^@P\M-etd^D^@^@^@\M-(U^M^@^@^@^@^@\M-(U^M^@^@^@^@^@\M-(U^M^@^@^@^@^@^L^@^@^@^@^@^@^L^@^@^@^@^@^@^D^@^@^@^@^@^@^@Q\M-etd^F^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^P^@^@^@^@^@^@^@R\M-etd^D^@^@^@\M-0j^N^@^@^@^@^@\M-0z^N^@^@^@^@^@\M-0z^N^@^@^@^@^@P^U^@^@^@^@^@^@P^U^@^@^@^@^@^@^A^@^@^@^@^@^@^@/lib64/ld-linux-x86-64.so.2^@^@^@^@^@^D^@^@^@@^@^@^@^E^@^@^@GNU^@^B^@^@\M-@^D^@^@^@^C^@^@^@^@^@^@^@^B\M-^@^@\M-@^D^@^@^@^A^@^@^@^@^@^@^@^A^@^A\M-@^D^@^@^@
[3] 5058
/usr/bin/zsh:3: unmatched '
/usr/bin/zsh:2: parse error in command substitution
[2]  - exit 1     ELF  >
[3]  + exit 1     pLi�c�E 2D  <
/usr/bin/zsh:6: command not found: \M- DD\M-1^D\M-^BH^A^A\M-^Q
/usr/bin/zsh:7: command not found: ^D
/usr/bin/zsh:9: parse error near `)'
/usr/bin/zsh:8: parse error in command substitution

**Comment by gh0stzk** [comment]
if you still having that strange response when open a terminal just write `compinit -C -d $ZDOTDIR/zcompdump` close terminal and open again.

Yeah thats strange if its not happend always, mmm maybe a problem in your keyboard or mouse? i guess not but just be sure. You have correctly set your layout keyboard?

Dont know about this but i will search for some info.

**Comment by FastDust11** [comment]
I use no mouse but indeed I was changing keyboard layout after installation, in general it works but I will check tomorrow, maybe I made some mistake will check that. Thanks for an idea.

**Comment by gh0stzk** [comment]
actually i didnt find anything about this :s

**Comment by FastDust11** [comment]
Okay so I found out that I set Polish keyboard layout (in Poland we use US one, I don't even know what this monstrosity (Polish layout) is. It looked like it helped, but I cannot say for 100% cause error occurred randomly and day after I change it I bricked the system and did full reinstall.

**Comment by FastDust11** [comment]
Okay so I found out that I set Polish keyboard layout (in Poland we use US one, I don't even know what this monstrosity (Polish layout) is. It looked like it helped, but I cannot say for 100% cause error occurred randomly and day after I change it I bricked the system and did full reinstall.
