### ISSUE TITLE
How to get battery icon in zombie theme, it's my favourite of all rices

### ISSUE THREAD

**Issue by NavatejR** [gh0stzk/dotfiles#197]

**Comment by NavatejR** [comment]
So how do I enable it?
Could you show opthe steps because I have never configured eww before

**Comment by NavatejR** [comment]
I don't mind editting the code myself if you don'tmind

**Comment by NavatejR** [comment]
in the other rices such as pamela they do show the battery percent its only a slight inconvenience for the zombie as I have to open up terminal and type cat /sys.. and find battery capacity

**Comment by gh0stzk** [comment]
The thing is that the other themes like pamela use polybar to show the battery information.

In z0mbi3 the bar is made with eww and it is a little more complicated because the code is not already in my dotfiles, it is not just that need to enabled, but rather the code has to be created.

Let me look for some dotfiles to show you how you could do it with the script that is in my dotfiles.

**Comment by gh0stzk** [comment]
Look this. This code is from the rxyhn repo, the bar from where i inspired, use the same bash script.

```yuck
;; Battery Widgets ;;
(defwidget bat []
	(box	:orientation "v"	
			:space-evenly "false"
	(label	:class "bat"		
			:halign "end"		
			:text battery	
			:tooltip "Battery: ${battery-cappacity}%")))
(defpoll battery			:interval "1s"	"scripts/battery icon")
(defpoll battery-cappacity	:interval "1s"	"scripts/battery percent")
```
of course yo nee to change the path to script.
from there you need to add the widget to some part of my bar, (bat)

of course this only shows a glyph shows you the percent.
When the time comes, i will modify to show an image icon, not a glyph, to make it looks nicer. a notification when you are under certain percentage, etc.. and other improvs. But for now, that will show what you want.

**Comment by NavatejR** [comment]
Yes I ended up somehow fixing it by doing this
I adjusted the eww.yuck by adding:
;; Battery Widgets ;;
	(defwidget bat []
	(box	:orientation "v"
			:space-evenly "false"
	(label	:class "bat"
			:halign "end"
			:text battery
			:tooltip "Battery: ${battery-cappacity}%")))
	(defpoll battery			:interval "1s"	"scripts/battery icon")
	(defpoll battery-cappacity	:interval "1s"	"scripts/battery percent")
under
;; Workspaces Widgets ;;
	(defwidget workspaces []
		(literal :content workspaces))
and 

	;; Control Panel Widgets ;;
	(defwidget control []
		(box :orientation "v"
			:space-evenly false
			:class "control"
	(bat)
	(notifycenter)
	(volum)
	(wifi)
	(pacman)))
under top widgets


and in eww.scss
// icons info
.control {
  padding: 0.5rem;
  background-color: $black;
  border-radius: 5px;
}

.trayicon {
  background-repeat: no-repeat;
  background-size: 25px;
  min-height: 25px;
  min-width: 7px;
  margin: 0.2rem 0 0.2rem 0;
}

.bar-updates-text {
  font-family: "JetBrainsMono NF";
  font-size: 14px;
  font-weight: Bold;
  color: #8ea6c4;
  margin: 0.4rem 0 0.2rem 0.2rem;
}

scale trough {
  all: unset;
  background-color: $background;
  border-radius: 5px;
  min-height: 80px;
  min-width: 10px;
  margin: 0.3rem 0 0.3rem 0.1rem;
}

.volbar trough highlight {
  background: linear-gradient($red, $magenta, $blue, $cyan);
  border-radius: 5px;
}

.bat{
  font-family: JetBrainsMono Nerd Font;
  font-size: 1.4em;
  padding-right: 0.8rem;
  margin: 0.3rem -1 0.6rem 0.1rem;
  color: $blue;
}

**Comment by gh0stzk** [comment]
Nice!! do you need something else or i can close the issue?
