### ISSUE TITLE
Working with River on Wayland.

### ISSUE THREAD

**Issue by Alucard2169** [gh0stzk/dotfiles#198]
Hey, first of all, thank you for your hard work, really love this project.

I am planning to switch to Wayland, and I was wondering if I can make this work with `river` as Wayland doesn't have bspwm. Have you tried it?

**Comment by gh0stzk** [comment]
I have never used river but I once read that it was the most similar to bspwm. However, I have used hyprland and I think that the bars would be easily ported to hyprland since it uses CSS.

**Comment by Alucard2169** [comment]
Thanks for the input, I will try adjusting it to river on my PC, and will get back to you after that. Though on river, I guess I would have to use waybar or something else, and woffi for rofi.

**Comment by gh0stzk** [comment]
Surely it can be ported in its entirety. But it will be a lot of work.

**Comment by Alucard2169** [comment]
That's true.
