### ISSUE TITLE
Bar is in a black box

### ISSUE THREAD

**Issue by Momen-MKadry** [gh0stzk/dotfiles#199]
Hey, so I came back to this rice yesterday and I noticed something weird with the bar in some themes.

![image](https://github.com/gh0stzk/dotfiles/assets/93672218/06593771-b2e9-4c12-96a6-a83d71d0a2a0)

![image](https://github.com/gh0stzk/dotfiles/assets/93672218/9d5f79f9-2465-4c66-b8c4-db2332d347c5)

the bar is surrounded by a black box, this happens in almost all the themes, I tried bpwm and bspwm-rounded-corners and both have this issue, also I tried the solution in #131 and it solved nothing.

Some other things to note, idk if this can affect it ot not:
* I have hyprdots installed for my hyprland, I know they both configure same things but I installed this rice again before opening bspwm.
* I deleted the bspwm config directory and installed the theme after that and the issue presists too.

**Comment by gh0stzk** [comment]
It's definitely a problem with picom.

Could you send a screenshot of bspwmrc, the part where picom is launched, and another of picom.conf, the part where the backend is established, please.

**Comment by Momen-MKadry** [comment]
Ok, here is the part from bspwmrc

![image](https://github.com/gh0stzk/dotfiles/assets/93672218/fd068e19-4960-4dca-b361-400a2c678da6)


here's picom.conf

![image](https://github.com/gh0stzk/dotfiles/assets/93672218/d96cd3ed-c861-4dac-8f4b-7e4a6c8f6fbe)

**Comment by gh0stzk** [comment]
Ok. 
First make sure there is no other picom directory in ~/.config/

Then make sure that the process is active, pidof picom. If it is not active, that is where the problem lies.

If active, kill the process, pkill picom.

Now edit the picom.conf file of my dotfiles and change the backend to xrender.
And change the log-level option to warn.

Now restart bspwm with super + alt + r keys

Are you sure there isn't another instance of picom running at the beginning of everything?
How do you log in? with a login manager or with xinitrc???

**Comment by gh0stzk** [comment]
For some reason your picom is not loading.
first rename or delete that picom.conf inside .config dir, picom-backup.conf or whatever u want.
now open a terminal and write: `picom --config "$HOME"/.config/bspwm/picom.conf &`

the picom should be loaded succesfully and no more errors in your bars. 

Running it from the terminal should give us some error if picom is not loaded successfully.

Now you can close the terminal, the picom process will die, now just reload bspwm with `super + alt + r` and it should load without problems.

**Comment by gh0stzk** [comment]
Another thing, be sure picom is installed, `which picom` if not, just `sudo pacman -S picom`

**Comment by Momen-MKadry** [comment]
Ok, so I did what you said and I think I found the problem, I had `picom-jonaburg-git` installed not `picom`, removing the first and installing regular `picom` removed the black spots.

Thanks a lot for your help.
