### ISSUE TITLE
Theme switching not changing anything

### ISSUE THREAD

**Issue by Rainerr123** [gh0stzk/dotfiles#2]
when i try switching the theme polybar doesn't change at all and bspwm restarts, i've reinstalled a few times and nothing's changed.

**Comment by gh0stzk** [comment]
Could you please confirm that bspwmrc and scripts inside your home/.config/bspwm/scripts have execute permission.

then could you pls share errors inside your home/.xsessionerrors

**Comment by Rainerr123** [comment]
If I run rice selector from console I get bspwm/rice.cfg permission denied
