### ISSUE TITLE
Problem with Neovim 

### ISSUE THREAD

**Issue by thien0709** [gh0stzk/dotfiles#201]
![image](https://github.com/gh0stzk/dotfiles/assets/85043649/5fd460b0-ecfb-4b64-984f-d18a93b0c936)
I have a problem with Neovim. Failed install bashls html cssls

**Comment by gh0stzk** [comment]
Install npm package, `sudo pacman -S npm`

Sorry forgot to add npm package to dependencies. will fix asap.

**Comment by thien0709** [comment]
Thanks for that solution, I again have a problem when editing the mason-lspconfig file like this: 
"Spawning language server with cmd: `lua-language-server` failed. The lang
uage server is either not installed, missing from PATH, or not executable
." How to fix it ?

**Comment by thien0709** [comment]
Thank you for it
