### ISSUE TITLE
Change terminal transparency and add rounded corner

### ISSUE THREAD

**Issue by paulo-barbosa2006** [gh0stzk/dotfiles#202]
Hello! I started using bspwm 1 day ago and I want to congratulate you on your dotfile, I'm a beginner and I can easily configure it a little. But I'm not able to change the transparency of the terminal, and if possible, change the transparency of other windows like file manager for example. I would also like to change the borders on all the windows, I found the border a little thick and I would also like to change the color. And about changing the rounded corners, the edge is not becoming round but rather 'disappearing'.
![Shot-2024-03-14-231544](https://github.com/gh0stzk/dotfiles/assets/74267828/73b6c1d1-60c8-445e-8599-d7504c489f21)

**Comment by gh0stzk** [comment]
Hello, some options, you can change them in the Theme.sh file that is in each theme directory, for example:

To change the border of the windows in a theme, look for this line in Theme.sh

`bspc config border_width 0`

change the 0 to the number you want

To change the transparency of the terminal, I defined 2 classes which are overridden depending on the theme you are in, one for the terminal that you open with `super + enter` and another for the floating terminal that you open with `super + alt + enter`

In the same Theme.sh file look for the _set_picom_config_ function, within that function the last 2 lines are:

```bash

-e "s/\".*:class_g = 'Alacritty'\"/\"100:class_g = 'Alacritty'\"/g" \
-e "s/\".*:class_g = 'FloaTerm'\"/\"100:class_g = 'FloaTerm'\"/g"

```

Change the 100 for other number, you need to reload bspwm after save your changes.

**Important**, if you want to add any other app, you have to do it from the picom.conf file in ~/.config/bspwm/

search in picom.config

```
opacity-rule = [
  "100:class_g = 'Alacritty'",
  "100:class_g = 'FloaTerm'",
  "95:class_g = 'Updating'",
  "90:class_g = 'scratch'"
];
```

and add your app for example :

```
opacity-rule = [
  "100:class_g = 'Alacritty'",
  "100:class_g = 'FloaTerm'",
  "95:class_g = 'Updating'",
  "90:class_g = 'scratch'",
  "70:class_g = 'firefox'"
];
```

In theme.sh above that 2 lines you will se the corner-radius = 6 you can change the radious of the corners for that theme.

**Comment by paulo-barbosa2006** [comment]
Everything worked. Thanks!
