### ISSUE TITLE
updater is not working

### ISSUE THREAD

**Issue by kthurman59** [gh0stzk/dotfiles#204]
When I click on the system update icon I get the following error:
paru: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory

I did try a full re-install of the dotfile program:  Did not fix it.
I tried using Claude AI to help:  Did not fix it.

**Comment by AzhamProdLive** [comment]
Pacman had an update that broke yay and paru, but both pushed fix in order to fix this issue, make sure to have a up-to-date Paru version

**Comment by gh0stzk** [comment]
Yes, the problem is not the script of my dotfiles, yesterday Pacman was updated and broke paru, you need to reinstall paru. What I did was:

```
sudo pacman -Rns paru

git clone https://aur.archlinux.org/paru.git

paru cd

makepkg -si

```
You can try cloning the paru-bin from AUR if you dont want to compile but at the moment i dont know if paru-bin pkgbuild is updated in AUR
