### ISSUE TITLE
Zombi3 Setup

### ISSUE THREAD

**Issue by Shentxt** [gh0stzk/dotfiles#205]
**### Zombie3's sliderup causes the bar to expand out of bounds and never go back to normal, any suggestions?**
![Screenshot_2024-03-16-16-12-41_1366x768](https://github.com/gh0stzk/dotfiles/assets/89170885/9bc7ea7c-eb9a-4754-bbd4-c329b2634236)

**Comment by gh0stzk** [comment]
Yes, it is an old "bug" that has been discussed in the eww repo, but it is not a bug itself, it is how css works, as there is no space when the bar expands. (eww works with limited css)

2 Solutions, make your bar smaller or press `Super + h` to hide it, then press `Super + u` to show it again and the bar should regain its original shape.

For a long time I looked for a solution to this problem in the eww repo, and in the end that is the reason and the solutions.

**Comment by Shentxt** [comment]
Oh, thank you I was supposed to. By the way, what a good setup
