### ISSUE TITLE
How do I add github copilot to the neovim of this setup?

### ISSUE THREAD

**Issue by ChrolloRifat** [gh0stzk/dotfiles#208]

**Comment by AzhamProdLive** [comment]
You should check out this guide over here, if you want to add Copilot to Neovim : https://github.com/github/copilot.vim

**Comment by gh0stzk** [comment]
You need to create a new file called **copilot.lua** under _~/.config/nvim/lua/plugins_

Then your new copilot.lua file must be like:

```
return {
      "github/copilot.vim",
}
```

Thats it. Then open neovim again and write `:Copilot setup` and follow the instructions to add your account.

**Comment by ChrolloRifat** [comment]
Thanks a lot. it was so easy.
