### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by darkyll** [gh0stzk/dotfiles#209]
hello ,
i am new to Arch pls guide to what to do after running the Rice script . i am not able to start my X session , current using exec bspwm take me to default terminal screen of Arch

**Comment by AzhamProdLive** [comment]
As stated in here already : https://github.com/gh0stzk/dotfiles/issues/182#issuecomment-1902669985

You have to install a Login Manager in order to use the dotfiles, 
``sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings``
``sudo systemctl enable lightdm``
``reboot``

**Comment by gh0stzk** [comment]
If you are new to a system like arch, using startx may not even be configured, to start that way you need to have some configuration.

The way I recommend is to install a login manager, I use lightdm it is easy and fast to use, do the following.

`sudo pacman -S lightdm lightdm-gtk-greeter configuration-lightdm-gtk-greeter`

After activating the service, `sudo systemctl enable lightdm.service`

Then reboot and that's it.
