### ISSUE TITLE
neofetch config

### ISSUE THREAD

**Issue by mazdakdev** [gh0stzk/dotfiles#21]
Please commit your neofetch config.

**Comment by mazdakdev** [comment]
It seems, it uses sysfetch and there is a sysfetch config in this repository.
I close this issue.

**Comment by gh0stzk** [comment]
> It seems, it uses sysfetch and there is a sysfetch config in this repository. I close this issue.

Yes and there is another fetch in ~/.local/share/asciiart called zfetch
