### ISSUE TITLE
Updating and Keeping my own edits/customization

### ISSUE THREAD

**Issue by ChrolloRifat** [gh0stzk/dotfiles#211]
How do we update and is there a way to preserve the changes we made which are crucial to our workflow and system? By update, I mean the new features or bug fixes that you are adding or will add to this repo. For example, if we update, it shouldn't overwrite the changes that we made previously to the rice to setup our network manager, terminal tweaks, keybindings, neovim setups etc etc you get the gist, right?

**Comment by gh0stzk** [comment]
On every change i made i can upload a diff patch, so you can apply them in your local repo, of course that patch could and should fail in most cases due to your local modifications, but you can test from there.
