### ISSUE TITLE
Trying to add a new widget to replace the calendar, without success

### ISSUE THREAD

**Issue by AzhamProdLive** [gh0stzk/dotfiles#214]
Hello there, as the title states, I am trying to add a new widget I found, but everytime I do the changes, I just can't pull it up, and it always pulls up the calendar widget from this repo, what should I do to change it ? (I tried modifying OpenApps, changing the line in Modules.ini, and trying to start it from the command line)

If you need to see, I have the new widget on my repo with the files that i've took from [this repo](https://github.com/hidayry/dotfiles-bspwm/tree/main/config/bspwm/ryan/src/eww/date)

**Comment by gh0stzk** [comment]
Its imposible to know what you are doing, and where but, where you create this new widget?? in .config/eww/ or in .config/bspwm/eww ? remember my conf, launch the eww daemon in .config/bspwm/eww.

**Comment by AzhamProdLive** [comment]
>Its imposible to know what you are doing, and where but, where you create this new widget??

I added the files in .config/bspwm/eww , in a folder named date

>launch the eww daemon in .config/bspwm/eww.

I did that, but it starts the calendar included in this rice instead of the new one I added

**Comment by AzhamProdLive** [comment]
The command I've used to launch the daemon
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/317c013a-fb2b-4316-a5ad-8c7f2b817922)

My eww.scss & eww.yuck
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/f5983817-e4d1-405a-bb75-06d8f94e3293)
![image](https://github.com/gh0stzk/dotfiles/assets/73955243/8fbbe702-8571-4627-ad62-2cac09732f5f)

**Comment by gh0stzk** [comment]
check if the window name is not the same.... my windows widget name is :

```
;; Windows ;;
(defwindow date
  :geometry (geometry :x "40%"
                      :y "8%"
                      :anchor "center top")
  :wm-ignore true
(cal))
```

is "date"

**Comment by AzhamProdLive** [comment]
Okay, I figured why it wasn't working now 

It was because of the name of the window widget, and also because eww doesn't sync changes without restarting the daemon lmao

Now it's fixed and I can progress thru it lmaoo, thanks
