### ISSUE TITLE
Why bspwm?

### ISSUE THREAD

**Issue by rew1nter** [gh0stzk/dotfiles#215]
Hey. I'm planning on switching to WMs. I've been using some of this repos configs in KDE till now.
I'm curious why you chose bspwm. What makes you use this over other WMs?

**Comment by gh0stzk** [comment]
It is totally up to each person's taste.

Personally, I don't really love wayland even though hyprland is popular now.

I don't like wms where you need to learn a programming language to configure it, with +50 configuration files for the themes, (hello awesomewm) and in the end bspwm does the same.

**Comment by rew1nter** [comment]
Thanks for the detailed reply. I don't root for Hyprland either.
I tried awesome in the past a couple of times and ended up rage-quitting. Guess I'll start with bspwm

**Comment by gh0stzk** [comment]
try various wms, keep it wherever you feel fine.
