### ISSUE TITLE
Obstructing the readability of SONG and ARTIST texts on Player widget

### ISSUE THREAD

**Issue by JuanH88** [gh0stzk/dotfiles#216]
The music widget 'player.yuck' tends to get too dark in Andre Rice, it can be solved for now by changing the fg color of eww colors, but the cause of the problem is still the image that gets darker on the left side, obstructing the readability of SONG and ARTIST texts

**Comment by gh0stzk** [comment]
Oh that's right, thank you, I hadn't noticed it with dark backgrounds. I put it on my to-do list.

In the meantime, you can modify the Theme.sh file within the andrea theme, search line 111

`\$fg: #151515;`

change it for:


`\$fg: #474747;`

**Comment by 0xN1nja** [comment]
any progress on this? @gh0stzk

**Comment by gh0stzk** [comment]
> any progress on this? @gh0stzk

i just merge the commit, it only changes the text shadows, it more visible now. I could add a new color but that means i need to modify all the theme.sh files. so for now only changes the text shadow.
