### ISSUE TITLE
im stuck in lock screen

### ISSUE THREAD

**Issue by hoyazin** [gh0stzk/dotfiles#217]
after everything was downloaded i rebooted my laptop and went to desktop session and clicked "bspwm" and i entered my password and clicked enter and it got stuck it does take me to homescreen or anything im just stuck in lockscreen. is there a way to fi this if not how do i uninstall it

**Comment by gh0stzk** [comment]
You need to gave me more details, can you can check if in ~/.config/bspwm you have files? Check the error log RiceError.log in your home. You enter your session with a login manager??? which one?
