### ISSUE TITLE
Ranger VSCode

### ISSUE THREAD

**Issue by LuiBi10** [gh0stzk/dotfiles#219]
Hey! Espero estes super, muchas gracias por los dotfiles

Solo un par de preguntas (perdon si son muy basicas)  como hago que el editor de texto que abra ranger por defecto no sea neovim sino vscode. Y la otra es quela shell  (alacritty) tarda demasiado en cargar (1 min promedio). Alguna recomendacion para ello? 

De antemano muchas gracias y felicidades por tu excelente trabajo

**Comment by gh0stzk** [comment]
Hola si para que ranger abra tu editor de preferencia edita el archivo .zshrc el cual si estas usando mis dotfiles ya deberia venir con estas lineas de inicio:

```bash
export VISUAL="${EDITOR}"
export EDITOR='nvim'
......
```

Con eso ranger deberia abrir el programa de tu eleccion para editar archivos. En este caso los abre con nvim.
Sin embargo supongo que estas abriendo ranger con el shortcut `Shift + alt + r` y es un problema que tengo que solucionar, si lo abres de esa forma, por alguna razon no abre los archivos, necesitas abrir una terminal `super + enter` o `super + alt + enter` escribir ranger y ya asi te abre los archivos sin problema, con el editor que elijas.

El otro problema que mencionas, es muy raro y desconozco el por que sucede, me ha pasado, tengo 4 computadoras, 2 de ellas son laptops, una de ellas es vieja, y en esa me sucedia lo que mencionas, no tengo idea del porque, y luego de un momento a otro dejo de demorarse en abrir y abre ya con normalidad, incluso dentro de .zshrc esta configurado para que el zdump se actualice cada 24 horas y abra aun mas rapido, se que puede pasar y me ha pasado pero desconozco totalmente el porque, prometo investigar a fondo. Mintras tanto si te es muy molesto, instala cualquier otra terminal y abrela desde el menu de apps.

**Comment by LuiBi10** [comment]
Muchas gracias. En efecto, Ranger desde el shortcut no abre los archivos, voy a revisar y si puedo ayudar te estarè comentando.  

Gracias
