### ISSUE TITLE
A need for a lock-screen

### ISSUE THREAD

**Issue by ChrolloRifat** [gh0stzk/dotfiles#220]
It would be very nice to have aesthetic lock-screen that matches this gorgeous rice. How can it be implemented?

**Comment by Ig-Joseph** [comment]
Never tried bspwm but ig it's X'Org. Therefore u can try a betterlockscreen. A modern alternative to i3-lock

**Comment by gh0stzk** [comment]
Yes you need to search for one lockscreent to fit your like. But yes im thinking in add another more good looking, for me phsylock is minmal and fit my like, but thre are several people like you that needs more, maybe i will add another next update.

**Comment by ChrolloRifat** [comment]
also, it would be awesome if you could mention what changes in where do we need to make for the lockscreen to work smoothly with our rice.

**Comment by gh0stzk** [comment]
Yep in the next 2 updates i will change to another and the steps for update the rices.

**Comment by ChrolloRifat** [comment]
Thank you. I'll be waiting for the updates, my bro.
