### ISSUE TITLE
ncmpcpp con spotify?

### ISSUE THREAD

**Issue by ricrubrom** [gh0stzk/dotfiles#221]
Es posible? por lo que vi los programas y librerias que se utilizaban para esto ya no existen mas. Hay algun alguna alternativa sino a ncmpcpp que me permita conectarme con spotify? de ser asi tendria que cambiar algo en los rices para que funcionara correctamente? mas que nada con respecto a la polybar

**Comment by gh0stzk** [comment]
Hola, en este caso son dos cosas distintas, el reproductor ncmpcpp lo controla mpd, spotify lo controla playerctl, respecto a polybar puedes controlar las canciones de ncmpcpp por que usa el modulo mpd, pero bien existen algunos modulos para polybar que pueden ser controlados con playerctl https://github.com/mihirlad55/polybar-spotify-module este por ejemplo.


un repoductor tipo ncmpcpp para spotify pues esta spotify-cli creo que se llama, esta en el aur.

Pero basicamente para controlar desde olybar tu spotify solo tienes que agregar ese modulo del link, hay mas, igual busca el que te guste.

**Comment by 0xN1nja** [comment]
Hey, @ricrubrom even though the owner of this repository knows Spanish, it doesn't mean that you should write issues in Spanish.

Most contributors to this repository do not understand Spanish, and it becomes frustrating to have to translate everything.

So, this is a request to please write your issues in English.

**Comment by 0xN1nja** [comment]
Hey @ricrubrom, even though the owner of this repository knows Spanish, it doesn't mean that you should write issues in Spanish.

Most contributors to this repository do not understand Spanish, and it becomes frustrating to have to translate everything.

So, this is a request to please write your issues in English.
