### ISSUE TITLE
I want to uninstall this environment 

### ISSUE THREAD

**Issue by hoyazin** [gh0stzk/dotfiles#223]
how do uninstall BSPWM environment  cuz after i installed it my laptop started lagging even tho bspwm didnt work right

**Comment by AzhamProdLive** [comment]
If you want to delete only BSPWM, you can do ``sudo pacman -Rns bspwm`` to remove BSPWM and all the dependencies and configuration files

**Comment by freejooo** [comment]
yap this same case happened with me too huh i have add some ramdum 
free -h && sudo sysctl -w vm.drop_caches=3 && sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && free -h
in a randam fastion to be excecuted in random time so it does not lag but it does still so yap lol

**Comment by AzhamProdLive** [comment]
> yap this same case happened with me too huh i have add some ramdum free -h && sudo sysctl -w vm.drop_caches=3 && sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches && free -h in a randam fastion to be excecuted in random time so it does not lag but it does still so yap lol

That's weird, I don't face those issues, what are your specs ?

**Comment by gh0stzk** [comment]
Yes only unisntall bspwm, sometimes is for bad graphics drivers and/or the picom config, if ur specs ara not modern or good, you need to change in bspwmrc the picom line, to legacy, and in picom choose the xrender backend.
