### ISSUE TITLE
Terminal Themes

### ISSUE THREAD

**Issue by LuiBi10** [gh0stzk/dotfiles#225]
Hola, soy yo nuevamente.

Queria consultarte  si es posible personalizar la terminal con oh-my-zsh, sobre el dotfile que compartiste de .zschr. Es decir, debo borrar algo del zsh actual (el de tu dotfile) a puedo cambiar el tema con powerlevel10k sin problema

Disculpa si es muy basico, apenas estoy empezando en este mundillo.

Gracias y saludos

**Comment by gh0stzk** [comment]
No deberias de tener ningun tipo de problema modificando el archivo .zshrc, ya que no deberia intervernir respecto a los dotfiles.
