### ISSUE TITLE
Nvim - Ranger

### ISSUE THREAD

**Issue by LuiBi10** [gh0stzk/dotfiles#227]
Hola! 

He instalado la actualizacion en un disco duro externo en el  cual tengo  endeavour, en general todo corre muy bien pero tengo un problema con ranger y  el neovim, cuando abro el editor por defecto se abre nano.  He revisado el zshrc y se mantiene igual a tu configuración, revise el rc.conf  (rifle) y tampoco hay diferencia. Alguna recomendacion?  

Muchas gracias nuevamente

**Comment by gh0stzk** [comment]
En .zshrc cambia 

`export EDITOR='nvim'`

por 

`export EDITOR='/usr/bin/nvim'`

ya deberia abrirte en nvim.
