### ISSUE TITLE
conflict a keybind ==

### ISSUE THREAD

**Issue by raman164** [gh0stzk/dotfiles#230]
Hi, first of all I congrats gh0stzk on the nice work to create such a beautiful daily driver rice. 
Here is a little prob I faced during working with vscode on these newly set keybindings, shift + arrows are conflicting. These keys are set for CHANGE NODE FOCUS. So, I just re-changed these to Alt + arrows. While doin it, vscode keys working fine again. I hope it will be useful.
Thanks

**Comment by gh0stzk** [comment]
Yes this always be a problem with certain apps, setups, workflows, i dont use vscode, i use nvim, but of course vscode is used for many people, let me think what shortcuts be more efficient.

the problem with chenge for alt key, is the expand window:

# expand a window
ctrl + alt {Left,Down,Up,Right}
	bspc node -z {left -10 0,bottom 0 10,top 0 -10,right 10 0}
	
that interferes with ctrl + alt + arrows to expand windows, change that too.

**Comment by raman164** [comment]
Yes, have to think about it.
But thanks for the wonderful rice :) Always waiting for the coming updates
:)))

**Comment by gh0stzk** [comment]
will close this, in the next updates i will try to find an alternative :D
Thanks.
