### ISSUE TITLE
Null temperature script

### ISSUE THREAD

**Issue by adilhyz** [gh0stzk/dotfiles#234]
# context
This a script ```temp.sh``` is broken  https://github.com/gh0stzk/dotfiles/blob/bc533dab1e73792a3e8a9da2754338df2614aeb8/config/bspwm/scripts/temp.sh#L3

<details>
<summary>This broken screenshot</summary>

> ![Screenshot-2024_04_26-03 58 14-1366x768 (copy 1)](https://github.com/gh0stzk/dotfiles/assets/100203867/186e6813-0fe1-4d9c-a1cc-fd398a7fbcae)

</details>

## The gaffe

![Screenshot-2024_04_26-04 18 06-1366x768](https://github.com/gh0stzk/dotfiles/assets/100203867/59455e16-ff99-4b5f-a963-9a9e044715fc)

#### whats broken?
I assume that every user including me, not all have the same directory which [**`hwmon0`**](#context). here I have a same case but different /sys/devices/platform/coretemp.0/hwmon/**`hwmon5`**/

## solved

![Screenshot-2024_04_26-03 58 24-1366x768](https://github.com/gh0stzk/dotfiles/assets/100203867/c1e3ae04-fa01-4939-9500-c17b7decb850)

**Comment by gh0stzk** [comment]
Thank you i just merge your PR. Yeah i forgot to re edit after make a test on my machine.
