### ISSUE TITLE
Key Bindings and widgets not working

### ISSUE THREAD

**Issue by Momen-MKadry** [gh0stzk/dotfiles#236]
Hey, I reinstalled Arch and installed your rice again, it was working perfectly before, now for some reason not all the bindings are working, the eww widgets also don't open when pressing the bar, I traced through the scripts and couldn't find the problem.

I did a fresh Arch install then ran the script, idk if it is related

**Comment by gh0stzk** [comment]
Maybe eww fails to install, check if is installed, open a terminal and run `which eww` the output must be /usr/bin/eww if not then follow this:

```bash
git clone https://github.com/elkowar/eww

cd eww

cargo build --release --no-default-features --features x11

cd target/release

chmod +x ./eww

sudo install -m 755 "$HOME/eww/target/release/eww" -t /usr/bin/
```

about the keybindigs, gime more info, all fails or just some, and whitch ones.

**Comment by Momen-MKadry** [comment]
I installed eww, it wasn't installed, the power button now works but everything in the bar doesn't, the theme selector and app menu don't open too, I have rofi installed and polybar too

**Comment by gh0stzk** [comment]
open a terminal and write `rofi -show drun -theme "$HOME"/.config/bspwm/scripts/Launcher.rasi `

Whats the output?? something like glibc language or related???

If something like this appears, means your locales are no properly configured, generate your locales.

**Comment by Momen-MKadry** [comment]
Oh that solved it, I generated the locale and it worked, thanks a lot

**Comment by gh0stzk** [comment]
the wifi indicator in polybar i guess? thats because probably you have an ethernet and wifi connections, polybar grabs only one.

open ~/.config/bspwm/scripts/system.ini and edit the sys_network_interface = to your desire interface. reload polybar or bspwm and should work

**Comment by Momen-MKadry** [comment]
Ah ok it worked now, thanks a lot for the help

**Comment by gh0stzk** [comment]
No prob.
