### ISSUE TITLE
Falla en el F1

### ISSUE THREAD

**Issue by Zirox121** [gh0stzk/dotfiles#237]
Creo que hay algunas fallas chiquitas en eww, presento fallas visuales (otra vez), ahora en el keybindigs, perdon por la molestia.
![Shot-2024-04-25-201248](https://github.com/gh0stzk/dotfiles/assets/146961720/49dc9592-84f1-4bb3-a4bd-64100204d558)

**Comment by gh0stzk** [comment]
Oh si es verdad, es relacionado al problema de antes, se me olvido editar el cheatsheet, pero ya lo corregi, puedes, clonar el repo de nuevo y copiar el archivo ~/dotfiles/config/bspwm/eww/cheatsheet/cheatsheet.yuck y reemplazar el viejo en ~/.config/bspwm/eww/cheatsheet/cheatsheet.yuck

o descarga si no quieres clonar de nuevo el repo, solo descarga el nuevo archivo https://github.com/gh0stzk/dotfiles/blob/master/config/bspwm/eww/cheatsheet/cheatsheet.yuck y lo pegas donde va.

O si aun tienes la carpéta de mis dotfiles en tu home, abre la terminal, cd dotfiles, y haz, git pull, eso actualizara los dotfiles en tu carpeta, y ya solo vas copias el nuevo y lo pegas donde va.
