### ISSUE TITLE
Physlock. GDM en bucle, no incia sesión

### ISSUE THREAD

**Issue by JuanH88** [gh0stzk/dotfiles#238]
Bueno, physlock me manda a GDM y al intentar loguearme me regresa a la misma pantalla de login en GDM, y como Physlock bloquea las TTY solo queda forzar el apagado con un botonazo, pues no se puede apagar desde GDM.

**Comment by gh0stzk** [comment]
Si no lo uses, por el momento, igual, ya estoy por subir la configuracion de otro screen locker, pero en creo que es mas problema de usar gdm en conjunto, no como tal de los dotfiles, ya que con sddm, lightdm y ly, me funcionan bien, yo no uso login manager, uso xinitrc, pero en las pruebas con esos login managers no tuve el problema que mencionas.

**Comment by JuanH88** [comment]
Oh, entonces sí debe ser problema de GDM, quedaré atento a tu repositorio.
