### ISSUE TITLE
Volume icon

### ISSUE THREAD

**Issue by paulo-barbosa2006** [gh0stzk/dotfiles#239]
When clicking on my volume icon, it only mutes or unmutes, I can't control the volume level. How can I add a volume controller by clicking on the volume icon?

**Comment by gh0stzk** [comment]
On what theme? in polybar or in eww bars?

**Comment by gh0stzk** [comment]
all themes uses polybar except z0mbi3 and andrea, in polybar Put the pointer over the volume or percentage icon and turn your mouse wheel to lower and raise it.

In z0mbi3, put the pointer over the volume icon and a bar will appear for you to raise or lower it. In Andrea, click on the volume icon, a window will appear so you can lower or raise the volume.

**Comment by paulo-barbosa2006** [comment]
oh... thank you
