### ISSUE TITLE
Ranger colorschemes

### ISSUE THREAD

**Issue by justog220** [gh0stzk/dotfiles#24]
Rices are supposed to change ranger colorschemes or not? Im asking because it´s not working for me.

**Comment by gh0stzk** [comment]
Yes, ranger has the default theme, that theme grabs the colors from the terminal, must be changed, you are using termite right?

**Comment by justog220** [comment]
Oh I was launching it with rofi. My bad, newbie problems. Thank you for your rices 🛐🛐🛐.
