### ISSUE TITLE
Touchpad

### ISSUE THREAD

**Issue by M3m31697** [gh0stzk/dotfiles#240]
Hola, ya llevó un tiempo usando tus dotfiles en mi vieja laptop, pero desde entonces no eh podido lograr hacer funcionar el touchpad, es decir que pueda hacer click derecho o izquierdo solo pulsando, no presionando, espero me haya explicado de la mejor manera y ojalá haya una manera de hacerlo.

Gracias

**Comment by gh0stzk** [comment]
No creo que sea motivo de mis dotfiles, si no de el hardware y el entorno, tienes instalado y correctamente configurado el paquete xf86-input-libinput????
