### ISSUE TITLE
keybinds

### ISSUE THREAD

**Issue by Magzobeem** [gh0stzk/dotfiles#242]
cant change the conf of the superkey to what i want/need it to be

**Comment by gh0stzk** [comment]
Tell me more, what did you try? What did you edit? What do you expect to happen?

**Comment by Magzobeem** [comment]
i edited the /home/usr/config/bspwm/bswmrc from mod 4 to Caps then rebooted, i expected the super key to change from the window key to the caps lock.
 Did i miss something a file that i should configure?

**Comment by Magzobeem** [comment]
ahhh got it appreciate the help <3
