### ISSUE TITLE
Conflicto en Atajos de Teclado

### ISSUE THREAD

**Issue by jalejotorresm** [gh0stzk/dotfiles#243]
### Conflicto con atajos de teclado

Hola, me gustaria reportar un issue con los siguientes atajos de teclado en los dotfiles

![image](https://github.com/gh0stzk/dotfiles/assets/72758522/1c5513aa-b91d-4bbf-82c9-fb812963b76c)

Estas combinaciones presentan 2 conflictos :

1. Shift + arrows = esta combinacion entra en conficto al momento de hacer una seleccion parcial con el teclado, ya que algunas distros comparten esta fucionalidad de teclado presente en Windows y herramientas de MS (aplica para herramientas de ofimatica nativa en Linux). A pesar que este conflicto puede resolverse con el uso del mouse, para los usuarios que usamos mas el teclado genera una experiencia de uso algo incomoda.

Pasos para reproducir el error:
- Ir a cualquier herramienta de ofimatica. En mi caso lo hice con Google Sheets, pero puede hacerse con cualquier herramienta similar
- Intentar hacer seleccion de varias celdas cintiguas a traves del comando shift+arrows
- Como el comando esta tomado a traves de sxhkdrc, e imagino que este toma prioridad, no se puede hacer esta seleccion

2. Ctrl + Shift + Arrows = esta combinacion entra en conflicto directo con el atajo de navegacion de Kitty, y parcialmente con el de Alacritty. Pongo ejemplos de los comandos de Kitty, los cuales estan mejor descritos en su documentacion:

![image](https://github.com/gh0stzk/dotfiles/assets/72758522/861abfd7-dd13-4d8a-aab9-dac2028a963c)
![image](https://github.com/gh0stzk/dotfiles/assets/72758522/59f9d8fc-ace3-488a-bcea-d1921939f133)

A pesar que en algunas distros las opciones alternativas para MacOS sirven, no es el caso de todas, lo cual genera incomodidad en usuarios que solemos usar estos atajos mientras usamos herramientas tipo CLI.

Al momento de escribir este reporte, se me vino la idea de tomar el ejemplo de alacritty y reemplazar las arrows de los atajos en el sxhkdrc por las teclas de navegacion en vim ( h j k l ), aunque no se que tan practico podria ser.

Quedo atento si necesitas algun material adicional para tener una imagen mas amplia del issue.

**Comment by gh0stzk** [comment]
Si creo que al ser unas keybinds que se usan de manera mas general como el shift + arrows para seleccionar, lo mejor seria cambiarlas, pensare y vere cual  o cuales son las mejores alternativas, por que si, al igual que tu, uso muchos cli programs y mucho teclado, kitty casi no lo uso, entonces tendra que ser algo que no moleste otras configuraciones, como neovim, vscode por ejemplo... 

Gracias por el dato, te respondo por aqui a cuales cambie, o si quieres dar sugerencias tambien bienvenidas.

**Comment by gh0stzk** [comment]
Ya lo he modificado, quedo tal cual excepto por las flechas, como bien propusiste, hjkl son usadas ahora, siendo que al parecer no causan conflicto con las demas.

**Comment by jalejotorresm** [comment]
Super, gracias por el arreglo!
