### ISSUE TITLE
Hola 

### ISSUE THREAD

**Issue by eduardo-8** [gh0stzk/dotfiles#25]
Una disculpa , como cambio la resolucion de los temas , es que se mueven un poco en mi pantalla , y se me van los iconos

**Comment by gh0stzk** [comment]
Que resilucion tienes? Y si puedes mandar captura de pantalla.

**Comment by eduardo-8** [comment]
Hola, tengo 1366x768
 y en algunos temas si se me salen algunos widgets 
 
 y despues de mostrar el menu de apagado,  se queda largo  el menu, y en otros tambien , se queda fuera de  lapantalla
 

![23-January-23-203022](https://user-images.githubusercontent.com/30558853/214212470-6ec80b84-d554-429c-8c55-1c727ab0ff11.png)
![23-January-23-203342](https://user-images.githubusercontent.com/30558853/214212848-5ae7c93e-69cc-42a0-a25a-0e983eabfd6a.png)
![23-January-23-203354](https://user-images.githubusercontent.com/30558853/214212852-44cafffc-5381-47ab-867d-ad3fd0024bf6.png)

**Comment by gh0stzk** [comment]
Ok lo de la imagen del fondo con el carro blanco, lamento decirte que es un bug de eww, si reinicias bspwm super + alt + r regresa a la notmalidad y ya no deberia cambiar su tamaño y lugar.

Lo de la barra blanca, en realidad los tamaños de las 3 barras son de 32% y 4% restante son los espacios, las barras se alinean bien sin embaro, al tener elementos como los iconos o las barras verdes de porcentajes, exceden su tamaño por que pues para resoluciones mas grandes que la tuya, quedan bien, se va a solucionar eliminando algunos elementos de la barra, ya sea los iconos lanzadores de aplicaciones o las barras verdes;

Prueba quitando las 3 barras verdes; en el archivo ,config/bspwm/rices/karla/bar/eww.yuck linea 150 veras este codigo,

```
(apps)
(sep)
(disk_st)
(ram_st)
(cpu_st)))
```
dejalo asi;

```
(apps)
(sep)
))
```
reinicia bspwm, deberia ahora verse bien. recuerda solo espara probar, tambien puedes quitar algunos iconos. en la linea 18 estan, 

`(button :style "background-image: url('images/icons/terminal.png');" :class "appicon" :onclick "scripts/apps --tr")`
ese es el codigo de la terminal de su lanzador, puedes pronbar quitando varios. Incluso puedes hacer los iconos mas chicos en el archivo eww.scss desde ahi.

el problema que tienes en si no es problema, es simplemente que la barra fue hecha para 1600x900 en adelante, y la solucion simple es quitar cosas.
