### ISSUE TITLE
Second monitor problem

### ISSUE THREAD

**Issue by kitxt15** [gh0stzk/dotfiles#252]
Hello! You did a great job, i respect you very much. Well, i just wanted to install my second monitor properly, but this happens:
![image](https://github.com/gh0stzk/dotfiles/assets/123263335/c524b537-d0d0-49e2-8044-ea4925e70be6)
Well, second monitor bar overlaps the first monitor. What can i do with it?

**Comment by gh0stzk** [comment]
Hello, first mi setups are with one monitor, saying that, is difficult to me, to help you, but i will try my best.
My dots use the same functionality from archcraft to configure monitors, so first, did you edit bspwmrc like examples in wiki? https://github.com/gh0stzk/dotfiles/wiki/Two-or-more-monitors-setup or is the default config??

**Comment by kitxt15** [comment]
Well, i think its not a problem of your rices, but something about xorg, idk. I will try to solve it myself, so thanks for your attempt to help me.
