### ISSUE TITLE
Display flickering -- while using firefox , and on playing video 

### ISSUE THREAD

**Issue by malhiamitoj** [gh0stzk/dotfiles#253]
I installed the dot-files multiple times to confirm that this issue is present . There is an issue regarding the display blanking or flickering while using Firefox and playing videos on any medium whether its online like Youtube or offline like on mpv , vlc etc. display suddenly start to blank just like shown in the videos . And if cursor is move while the flickering display become working for some time . I want to address that i reinstall the dot-files after deleting the previous once multiple times . This is present in the new updated dot-files while i also installed these a month earlier is its works fine on other hardware..

**Comment by malhiamitoj** [comment]
Watch this is the issue/ 

https://github.com/gh0stzk/dotfiles/assets/171196564/59976630-4767-462d-9595-7a1cc82c0997

**Comment by gh0stzk** [comment]
Ok whats is your graphic card? what driver you use? these sounds like a graphic driver problem, not dotfiles one. I have 3 pcs with amd radeon and intel graphics and i dont have these issues. 

First you can start killing picom `pkill picom` and test if the problem persist. Then you need to look for your dmsg, journal, and x11 logs.

**Comment by malhiamitoj** [comment]
Thanks for your help after killing picom . problem solved .. And your dotfiles are amazing ..

**Comment by malhiamitoj** [comment]
So , now the problem is when i  " pkill picom " the problem get solved but only until i restart my laptop . And have to " pkill picom " again .. So now the question is what i have to do to not " pkill picom " everytime i start my device.

**Comment by malhiamitoj** [comment]
![Shot-2024-05-30-102052](https://github.com/gh0stzk/dotfiles/assets/171196564/a0e7ffe4-c76c-4980-8308-aa1dc717ec64)
this is the screenshot of my neofetch. Its intel graphics card.

**Comment by gh0stzk** [comment]
There is no need to kill picom, all the time, you have a modern intel graphics and sometimes in new kernel releases like in arch few days ago, not all the time works as expected, try to search if there are bugs with this new release, arch forums are a good start point.

And  about picom, try opening ~/.config/bspwm/picom.conf file search for line 95

backend = "glx";

change it for xrender

backend = "xrender";

**Comment by malhiamitoj** [comment]
This settings works as well as change the kernel. 
[  backend = "glx";

change it for xrender

backend = "xrender";  ]

Thank you for your help ;)
