### ISSUE TITLE
Power button and widgets stopped working 

### ISSUE THREAD

**Issue by gr33pp** [gh0stzk/dotfiles#254]
I rebooted my pc today to see that the power button and widgets stopped working. I installed eww the first time I had the issue by following one of the closed issues on here. Now I don't know what to do

**Comment by gr33pp** [comment]
FIXED

Mehhn, I had to copy $HOME/.config/bspwm/eww to $HOME/.config/ . But eww was sourcing its configuration from that folder before. What went wrong? 🤔. You might need to look into this. So I will keep this issue open until you see it.

**Comment by gh0stzk** [comment]
Hello, stop working like widget doesnt start? or icons dont show?
Move again to $HOME/.config/bspwm/ my eww conf and launch a widget from terminal.

first kill eww `killall eww`

`eww -c $HOME/.config/bspwm/eww open --toggle csheet`

copy and paste errores here to help you.

**Comment by gr33pp** [comment]
> Hello, stop working like widget doesnt start? or icons dont show?
> Move again to $HOME/.config/bspwm/ my eww conf and launch a widget from terminal.
> 
> first kill eww `killall eww`
> 
> `eww -c $HOME/.config/bspwm/eww open --toggle csheet`
> 
> copy and paste errores here to help you.
> 

I will try that btw. I'm currently off my pc. But that fix worked.

**Comment by gh0stzk** [comment]
:s well that fix "moving my eww config" to ~/.config/eww should not work, my menus, config or buttoms to launch powermenu for example, look $HOME/.config/bspwm/eww path, not ~/.config/eww, i dont know how its work for you, but should not.

**Comment by AzhamProdLive** [comment]
> :s well that fix "moving my eww config" to ~/.config/eww should not work, my menus, config or buttoms to launch powermenu for example, look $HOME/.config/bspwm/eww path, not ~/.config/eww, i dont know how its work for you, but should not.

Maybe he changed some paths in the config files in the rices ? I would check on these first to see if they are actually linked
