### ISSUE TITLE
Extra padding in battery module of emilia

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#259]
I have a small problem. I was implementing your https://github.com/gh0stzk/dotfiles/commit/88e5669664ad2f034530135f0f9690788ebe3b30 in my fork, I copied the latest modules.ini and config.ini.

I'm encountering an issue with the emilia's bar. I noticed that with the latest modules and config, the battery and network modules are joined together; So, I separated them.

Now, my `modules-right` looks something like this:

```ini
modules-right = mplayer sep mpd sep bi battery bd sep bi network bd sep bi pulseaudio bd sep bi updates bd sep bi date bd sep tray
```

But, there's an extra padding at the end of the battery output:

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/2017a3e9-661e-4d06-8889-c11f376ab44a)

Battery module:

```ini
[module/battery]
type = internal/battery
full-at = 99
battery = ${system.sys_battery}
adapter = ${system.sys_adapter}
poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging><label-charging>
format-charging-background = ${color.mb}
label-charging = %percentage%%
label-charging-padding-left = 3pt
label-charging-padding-right = 7pt

format-discharging = <ramp-capacity><label-discharging>
format-discharging-background = ${color.mb}
label-discharging = %percentage%%
label-discharging-padding-left = 3pt
label-discharging-padding-right = 7pt

format-full = <label-full>
format-full-background = ${color.mb}
format-full-prefix = 
format-full-prefix-font = 2
format-full-prefix-foreground = ${color.green}
label-full = %percentage%%
label-full-padding-left = 3pt
label-full-padding-right = 7pt

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${color.blue}
ramp-capacity-font = 2

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${color.green}
animation-charging-font = 2
animation-charging-framerate = 700
```

Can you fix it?

<hr>

And another thing, in the jan rice, there's a time module, and I wanted to add a "clock" icon in front (`format-prefix`) of it, like:

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/682031fc-d157-41b2-9499-ca260b253978)

But jan uses a different font, so can you tell me which icon I should use?

**Comment by gh0stzk** [comment]
You need to edit all the padding-right properties edit the 7pt for 3pt or remove it, check how it looks.

About jan, you need to install font-manager package, open it and search for phosphor font, click on it and you will see all the glyphs, search for the clock glyph and add it to modules.ini.

**Comment by 0xN1nja** [comment]
Yes, your `padding-right` solution worked. Earlier, I was only changing one `padding-right` property, that's why it was not working.

About the jan rice, I have installed the `font-manager`, but I'm confused about how to get the clock icon:

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/1e2a2da7-458b-4d42-aa83-fd1866d4494d)

**Comment by gh0stzk** [comment]
Yeah in that window, find the clock glyph (the search box sucks, it doesnt work well) an then right click on it and copy it. Then paste in the modules.ini file.
