### ISSUE TITLE
Could we implement the AGS/ eww widgets in the rice?

### ISSUE THREAD

**Issue by chrollorifat** [gh0stzk/dotfiles#261]
I will try to help as much as I can with this. I found the eww widgets especially the aylur's modified version called ags(aylur's gtk shell) very featurfull and convenient. As I daily drive this bspwm exact dots, I thought we could also benefit from the ags.

**Comment by NCNmaker** [comment]
ags is for sway only right ?

**Comment by gh0stzk** [comment]
Yes works for wayland.

**Comment by NCNmaker** [comment]
Yea I mean Wayland, it is not for bspwm
