### ISSUE TITLE
Network manager 

### ISSUE THREAD

**Issue by M3m31697** [gh0stzk/dotfiles#263]
Hola, el día de hoy hace unas horas vi en tu canal de Youtube que mostrabas algunas de las principales funciones de tus dotfiles, me llamo mucho la atención que mostrabas un network manager, pero no sé si ya funciona o como puedo agrégarlo o ejecutarlo, espero me puedas ayudar, admiró mucho tu trabajo

**Comment by gh0stzk** [comment]
Hola, el menu de conexiones lo agregue a los dotfiles el 24 de marzo, si tienes mis dotfiles desde antes de esa fecha, entonces tendriaas que actualizarlos. Pero si los acabas de instalar, entonces bastaria con dar click al icono de wifi en las barras polybar de todos los temas. Si no te abre entonces, que app/servicio/metodo usas para conectarte, ese menu que mencionas que viste, usa networkmanager, si no usas networkmanager posiblemente la razon que no se muestre cuando das click es por eso mismo por que no usas networkmanager como tu gestor de conexiones.

**Comment by gh0stzk** [comment]
Para comprobar si da algun error puedes, abrir una terminal y escribir NetManagerDM das enter y mira que sale.
