### ISSUE TITLE
Can  we introduce dashboard and notification side-bar features like they have in the awesome wm rices?

### ISSUE THREAD

**Issue by chrollorifat** [gh0stzk/dotfiles#266]
You may have seen some of the awesome wm rices where they have this cool looking notification side-bar and a dashboard on the workspace-bar(activates upon click). I was wondering if we could implement such features too as we are using eww-widgets. So that should not be impossible. Of course, that's only if you want it.

**Comment by gh0stzk** [comment]
Hello, I don't think I'll do a side panel as such, it would be modifying the widgets and I think it's unnecessary, but I do plan to modify the calendar widget and leave it something similar to this:

![Shot-2024-06-26-072124](https://github.com/gh0stzk/dotfiles/assets/67278339/88f063d4-c798-4223-832a-943b49421fca)

At the moment it will not be soon, at least not in this next update, now I am finishing the 3 new themes, I already have the applets in rofi for bluetooth, screenshots, clipboard, a new welcome message the first time you run the dotfiles , among many other changes and tweaks, possibly at the end of the week the changes will be uploaded.

**Comment by chrollorifat** [comment]
![1719459446 screensht](https://github.com/gh0stzk/dotfiles/assets/76785992/17aae98c-eea3-4a79-909a-3d63a77aef9d)
Btw, This is the type of dashboard I was talking about. Let me know what are your thoughts on this.

**Comment by gh0stzk** [comment]
My opinion about these types of dashboards "widgets" is that they look very nice, but in practice they are rarely used. I think they are used more for the screenshot on r/unixporn.

I mean, to cite an example, there are people who have told me that they preferred the previous "profilecard" widget without the buttons, the one that only showed cpu, ram and battery information.

Many people have told me that it is a great UI but a horrible UX, and I don't think that type of widgets are the solution to improve the UX, however, create keyboard shortcuts for applets such as the powermenu, screenshot, clipboard that is coming in I think the next update improves the UX.

But in the end, they are only dotfiles, I only leave you the base and you can improve, modify or whatever you want, I cannot please everyone nor do I have the absolute truth to tell you what your workflow should be like.

And there are all kinds of people who install dotfiles, from those who had not even installed arch and much less used a WM to those who are developers but had not used a wm, to those who are cracks using wm and are not dedicated to computing.

But what I do think is used more is the example that I put in the image, a notification history, and that design next to the calendar seems very nice to me, maybe I will do it after the next update.

**Comment by chrollorifat** [comment]
yeah. sounds good to me. btw, what's your discord or signal username? let me add you.

**Comment by gh0stzk** [comment]
I only have telegram :/

Possibly today i will upload the next update.

**Comment by chrollorifat** [comment]
@gh0stzk Thanks for all the hard work, brother. Could you share your telegram please?
