### ISSUE TITLE
Dependencias eww fix

### ISSUE THREAD

**Issue by m4teoarg** [gh0stzk/dotfiles#267]
Hola, para compilar eww hace falta instalar dependencias.

[ ....... ]
if command -v eww >/dev/null 2>&1; then
    printf "\nEww is already installed\n"
else
    printf "\nInstalling Eww, this could take 10 mins or more.\n"
    {
        sudo pacman -S rustup libdbusmenu-glib gtk-layer-shell libdbusmenu-gtk3 --noconfirm
        git clone https://github.com/elkowar/eww
        cd eww || exit
        cargo build --release --no-default-features --features x11
        sudo install -m 755 "$HOME/eww/target/release/eww" -t /usr/bin/
        cd "$HOME" || exit
[ ........... ]

Gran trabajo.

**Comment by gh0stzk** [comment]
Hola gracias, libdbusmenu-glib y libdbusmenu-gtk3 se instalan al instalar gtk3.
gtk-layer-shell solo es necesario para wayland.
Agregare gtk3 mas bien a las dependencias, habia olvidado contemplar que muchos hacen instalacion nueva sin entorno. Gracias.

**Comment by m4teoarg** [comment]
Instale eww con yay en plasma proyecto AxOS con interfaz grafica en wayland, instalo esas dependencias, sin entorno grafico para x11 con bspwm compile desde la fuente instalando  rustup libdbusmenu-glib gtk-layer-shell libdbusmenu-gtk3.
Excelente gracias.

**Comment by gh0stzk** [comment]
Si estaba pensando hace unas semanas cambiar el metodo de instalacion y usar el paquete de AUR que al parecer ahora si esta bien mantenido y funcional, por que el de antes era un problema, pero no recuerdo cual paquete era el indicado, el que instala la ultima version, el ultimo commit, por que hay unos que instalan la version "oficial" y mis dots usan la version desarrollo, y bueno usando paru o yay ya te resuelve las dependencias, pero tendre que confirmar cual paquete es, si funciona bien y si esta al ultimo commit.

**Comment by m4teoarg** [comment]
![Sin título](https://github.com/gh0stzk/dotfiles/assets/140857022/5a17e682-82cd-4734-bbd9-d59ce9e323d9)


el commit esta en el PKGBUILD
https://aur.archlinux.org/packages/eww

**Comment by gh0stzk** [comment]
Si acabo de checar, ya ni existen algunos paquetes que habia, como eww-x11, y el paquete eww no seria el indicado, el indicado seria eww-git, voy a instalarlo con paru ahorita y comprobar que esta sin errores en instalcion y seguramente cambie el metodo de instalcion en el instalador, ya lo anote en mi to-do list, gracias. Cierro tema.

**Comment by Mnvim** [comment]
eww-git da el mismo resultado, ahora lo estoy compilando desde la fuente.

**Comment by gh0stzk** [comment]
Listo no hay problemas en su instalacion como los habia antes, ya cambie el instalador para usar el aur helper en vez de hacerlo "manualmente" desde la fuente

**Comment by m4teoarg** [comment]
![2](https://github.com/gh0stzk/dotfiles/assets/140857022/b10cac2c-bc47-499f-a11e-8ce73cb6f8c3)
COMPILADO DESDE LA FUENTE CON SU SCRIPT. PERFECTO SIN ERRORES

**Comment by m4teoarg** [comment]
![3](https://github.com/gh0stzk/dotfiles/assets/140857022/a156ff0c-4336-4f5a-8ad3-9701391e68a6)
SI AYUDA EN ALGO, COMPILADO DESDE LA FUENTE ESA ES LA VERSION.
MUCHAS GRACIAS.

**Comment by gh0stzk** [comment]
Si, usando el metodo desde la fuente en mi script de instalcion siempre te instalara la ultima version, y ya comprobe que eww-git de aur igual instala la ultima y sin errores. El paquete eww, instala la estable que esta como 5 commits detras, por ahora dejare la version del aur eww-git y eso tambien resolvera los problemas de depencencias.

**Comment by m4teoarg** [comment]
Excelente.  !!!!
