### ISSUE TITLE
Using basic shortcuts in terminal with zsh customization creating other characters

### ISSUE THREAD

**Issue by NavatejR** [gh0stzk/dotfiles#269]
![Shot-2024-07-06-200527](https://github.com/gh0stzk/dotfiles/assets/158991065/5e8c88c9-1eb1-4675-a2e3-8b8e4efe7a35)

So what happens is that when I like do basic shortcuts such as Ctrl + (Left arrow) then it doesn't move the text cursor back but instead writes :5D which I don't understand how to fix, there is no specification in zshrc file either

**Comment by gh0stzk** [comment]
Hello, is in kitty or alacritty?

**Comment by gh0stzk** [comment]
i see, is kitty, i test in alacritty and text cursor go back without problem. in Kitty i got a D.
You can try adding in .zshrc

```sh
# [Ctrl-RightArrow] - move forward one word
bindkey '^[[1;5C' forward-word
# [Ctrl-LeftArrow] - move backward one word
bindkey '^[[1;5D' backward-word
```

**Comment by gh0stzk** [comment]
Or in kitty https://github.com/kovidgoyal/kitty/issues/15
