### ISSUE TITLE
Convert RiceInstaller for Ubuntu

### ISSUE THREAD

**Issue by Jacky2001** [gh0stzk/dotfiles#27]
Hi, I tried replacing the Arch commands with those for Ubuntu.

However they don't all work, kindly when you have time could you help me by correcting them? THX 😁
[RiceInstaller.txt](https://github.com/gh0stzk/dotfiles/files/10527512/RiceInstaller.txt)

**Comment by gh0stzk** [comment]
Of course, friend, I will try to help you.

First of all, I look at your file and the first problem is that even if you find a way to install yay, the AUR packages are made to install on arch linux and based.

All the yay command packages you will need to compile for example;

eww => https://elkowar.github.io/eww/#how-to-install-eww

termite => https://github.com/aperezdc/termite "This maybe is on official repos from ubuntu"

xtitle => https://github.com/baskerville/xtitle

checkupdates-aur => That little script is the one that shows if there are new updates in the polybar. but I'm sure there are thousands of scripts for ubuntu, you will have to look for something like "script to show updates in polybar for ubuntu" and you will have to overwrite my updates.sh for the new one with the same name.

betterlockscreen => maybe that one is in the official ubuntu repositories, in fact I don't understand how it isn't in the Arch ones.

And the two fonts that are there you don't need to compile them, look for them at https://www.nerdfonts.com/ download them and directly put them in .local/share/fonts in your home.

Regarding the other packages of the pacman command, surely they are all in the official ubuntu repositories, although some may have another name, you will have to look for them, I'm sorry that I can't help you much on that but the last ubuntu I installed was more than 15 years old.

From then on the other commands in the script are just copy or move, so those work on all linuxs.

**Comment by Jacky2001** [comment]
Thanks for your help, I have replaced the commands with the packages you gave me.

In addition I replaced the yay package manager with yay-bin (a binary version of yay for Ubuntu)

I also modified the updates.sh file

Next I deleted the command for nerdfonts
[RiceInstaller.txt](https://github.com/gh0stzk/dotfiles/files/10529546/RiceInstaller.txt)
[updates.txt](https://github.com/gh0stzk/dotfiles/files/10529548/updates.txt)

**Comment by gh0stzk** [comment]
You almost have it then.

I saw in your file that you are using xtitle that comes in the ubuntu repositories. If I remember correctly, a person told me some time ago that creating "external rules" for bspwm didn't work for him. Investigating he used the same version that you are installing, I could find that this file is from another author.

So, if that feature of bspwm doesn't work for you, that's the reason, I think you should check that it's the same program. The xtitle that is used in my configuration is from the creator of bspwm "Baskerville"

**Comment by Jacky2001** [comment]
When I try to start the script, it gives me the following error: 'segmentation fault (core dumped)'.

**Comment by gh0stzk** [comment]
Remove this and try again
```
echo "Checking if yay-bin is installed"

	if dpkg -s yay-bin >/dev/null 2>&1; then
		echo "yay-bin is installed"
	else
		echo "Installing yay-bin"
		sudo apt update && sudo apt install git wget && git clone https://github.com/Jguer/yay-bin && cd yay-bin && ./install.sh && cd
	fi
sleep 2
clear
```

**Comment by gh0stzk** [comment]
As i said, yay is only for arch.
