### ISSUE TITLE
Adding custom wallaper to themes

### ISSUE THREAD

**Issue by Sandesh2007** [gh0stzk/dotfiles#270]
Hey i loved your configs and i am currently using it . but i want to add my wallpaper to some of the theme.
How can i add my wallpapers to some of these themes ?

**Comment by gh0stzk** [comment]
Just add your images to ~/.config/bspwm/rices/**THEME NAME**/walls

Then you can press `super + alt + w` and your new images will appear. The first time it may take 1 to 3 seconds for the images to be generated in the cache.

**Comment by Sandesh2007** [comment]
thanks :)
literally just figured out
