### ISSUE TITLE
Error when copying and pasting between virtual host and host , Help me! 

### ISSUE THREAD

**Issue by johandavid77** [gh0stzk/dotfiles#271]
Error when copying and pasting between the host and the host with virtualbox and vmware, I tried both and I have the same error, but in xfce4 I can copy and paste to and from the host...

Give thanks!

**Comment by gh0stzk** [comment]
Hello, i don't usually use virtual machines and when I do it is with qemu and libvirt, but I will look for information about your problem, i found this on arch forums. https://bbs.archlinux.org/viewtopic.php?id=247284

**Comment by gh0stzk** [comment]
try this for vmware `sudo pacman -Sy gtkmm3 open-vm-tools xf86-input-vmmouse xf86-video-vmware`
`sudo systemctl enable vmtoolsd.service`

**Comment by johandavid77** [comment]
I already did those steps but I can't get it to work, I already verified the vmware steps, the libraries are already installed but if I copy something from my browser to the host computer and try to paste them into the virtual machine, it doesn't do anything... It's more or less the last thing I need to be able to play from there, the rest is up to parrot but if I want to arch, we give thanks for the project and for the strength giving support there, all the love my lord many blessings and all the powers!
