### ISSUE TITLE
Picom Alacritty

### ISSUE THREAD

**Issue by LuiBi10** [gh0stzk/dotfiles#273]
Hey muchas gracias por compartir tu trabajo, esta genial.  Soy un poco nueva en todo esto y he querido modificar la transparencia de Alacritty pero al modificar el picom, guardar y reinciar el bspwm los valores vuelven a ser 100. Es decir, los modifico y guardo pero automaticamente se cambian a 100. Esto me pasa con alacritty y kitty. Sabes por que puede estar pasando esto? De antemano muchas gracias y disculpa mii novatada

**Comment by gh0stzk** [comment]
Hola, claro, de hecho es la pregunta mas recurrente que me hace, tendre que agregarla a la wiki. 
Para que cada tema tenga sus diferencias, como has notado, algunos temas tienen transparencias otros no, lo logro editando el picom perooo, no desde el picom.conf

Para lograr lo que quieres, en cada carpeta de temas .../.config/bspwm/rices/* hay un archivo llamado Theme.sh ese controla ciertos aspectos de ciertas configuraciones como en este caso es picom, abre el Theme.sh dentro de la carpeta del tema que quieras modificar y busca la funcion del picom:

```
# Set compositor configuration
set_picom_config() {
	sed -i "$HOME"/.config/bspwm/picom.conf \
		-e "s/normal = .*/normal =  { fade = true; shadow = true; }/g" \
		-e "s/shadow-color = .*/shadow-color = \"#000000\"/g" \
		-e "s/corner-radius = .*/corner-radius = 6/g" \
		-e "s/\".*:class_g = 'Alacritty'\"/\"100:class_g = 'Alacritty'\"/g" \
		-e "s/\".*:class_g = 'kitty'\"/\"100:class_g = 'kitty'\"/g" \
		-e "s/\".*:class_g = 'FloaTerm'\"/\"100:class_g = 'FloaTerm'\"/g"
}
```

Para tu duda especifica, en la linea de alacritty y kitty cambia el 100 por el numero que quieras. Ademas puedes cambiar ahi tambien las esquinas redondeadas, las sombras, el fade effect.

Y es que aunque hagas cambios en el picom.conf a las lineas de kitty, o alacritty, cada que inicias o cambias a otro tema, este tema sobreescribe esas partes de picom.conf por eso siempre te regresaba a el valor de 100. Pero donde debes modificar es desde Theme.sh

**Comment by LuiBi10** [comment]
Muchisimas gracias, efectivamente esa era la solucion. Seguire probando para modificarlo a mis gustos, pero de verdad es una base de partida excelente.  Saludos y gracias por la pronta respuesta.

**Comment by LuiBi10** [comment]
Solo para terminar queria preguntar si es posible cambiar la imagen de cabecera del rofi y en caso tal como se puede hacer. De antemano gracias nuevamente

**Comment by gh0stzk** [comment]
Dentro de la carpeta del tema, hay una imagen que se llama rofi.webp su tamaño es 550x160 pues solo usa el edit de imagenes de tu preferencia y la imagen que quieras que tenga esa medida, aunque no es obligatorio ese tamaño. la guardas con el mismo nombre y extendion rofi.webp y ya.

**Comment by LuiBi10** [comment]
Perfecto muchas gracias
