### ISSUE TITLE
neovim

### ISSUE THREAD

**Issue by cupenk** [gh0stzk/dotfiles#275]
hello,how can i open terminal with ur neovim?

**Comment by gh0stzk** [comment]
if you selected yes during my install script to test my nvim config, just open a terminal and write `nvim`

**Comment by cupenk** [comment]
> if you selected yes during my install script to test my nvim config, just open a terminal and write `nvim`

I mean terminal in neovim.

**Comment by 0xN1nja** [comment]
`:term`

**Comment by gh0stzk** [comment]
Yeah but there is no shortcut for that, i need to add it. "Added to my to do list."

**Comment by cupenk** [comment]
> Yeah but there is no shortcut for that, i need to add it. "Added to my to do list."

yes, please.

**Comment by cupenk** [comment]
> Yeah but there is no shortcut for that, i need to add it. "Added to my to do list."

[
![Shot-2024-07-26-040837](https://github.com/user-attachments/assets/debcb4c0-3685-4a4a-8ca8-56c466ea4d11)
](url)

how to fix border width ?

**Comment by cupenk** [comment]
![image](https://github.com/user-attachments/assets/cf6437a3-4fc0-40da-aaed-01f4d03020a2)
then how to change the keybind of suggestion i want to use tab for drop and down,thanks.

**Comment by LuiBi10** [comment]
Me aparece este error cada vez que abro neovim! Sabes que es lo que ocurre y como puedo solucionarlo?

![Screenshot_20240725_204706](https://github.com/user-attachments/assets/a42bbd95-d45e-4547-8679-d387b2eb34cd)

Gracias de antemano, saludos!

**Comment by gh0stzk** [comment]
> Me aparece este error cada vez que abro neovim! Sabes que es lo que ocurre y como puedo solucionarlo?
> 
> ![Screenshot_20240725_204706](https://private-user-images.githubusercontent.com/126365012/352339729-a42bbd95-d45e-4547-8679-d387b2eb34cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzAyMjYsIm5iZiI6MTcyMTk2OTkyNiwicGF0aCI6Ii8xMjYzNjUwMTIvMzUyMzM5NzI5LWE0MmJiZDk1LWQ0NWUtNDU0Ny04Njc5LWQzODdiMmViMzRjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNlQwNDU4NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjIwNGI4ZjBkZGZkMWU3ZDQyOTJhYzE3OWM0ZGE2MmRhZWEwY2M4Njg4MzM3YTIyMjA0ZGRjZGI0ZWY0YWM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FEVA3eyXS1JcDyEDFozib8NX64NiB9-SI9ZPHmm0bto)
> 
> Gracias de antemano, saludos!

Solo actualiza el plugin bufferline escribe `:Lazy ` dentro de nvim
despues en la nueva ventana oprime Shift + u y eso actualizara todos. reinicia nvim y listo.
