### ISSUE TITLE
playercard doesn't open

### ISSUE THREAD

**Issue by gnussbaum67** [gh0stzk/dotfiles#278]
I'm trying to open playercard to see weather but it won't open on any of the rices

**Comment by gh0stzk** [comment]
Possibly eww has failed to install during the installation process of my dotfiles, that AUR package always causes problems.

open a terminal and write `which eww`  te result must be /usr/bin/eww.    if not, then follow this steps to installa manually.

https://github.com/gh0stzk/dotfiles/wiki/Installing-EWW

**Comment by gnussbaum67** [comment]
that was it!  Gracias!
