### ISSUE TITLE
CheatSheat is small that can't even see anything

### ISSUE THREAD

**Issue by safe049** [gh0stzk/dotfiles#281]
using Arch Linux,Linux-lts kernel
the f1 cheatsheat is very thin and small
![图片](https://github.com/user-attachments/assets/c3ac268a-2d2e-47d2-8909-83482a4c1b5b)

Just like this
How do I solve it?

**Comment by gh0stzk** [comment]
what version of eww do you have? `eww -V` The latest one fixes that problem.

eww 0.6.0 4d55e9ad63d1fae887726dffcd25a32def23d34f thats the latets one.

**Comment by safe049** [comment]
> what version of eww do you have? `eww -V` The latest one fixes that problem.您拥有哪个版本的 EWW？`eww -V` 最新版本解决了这个问题。
> 
> eww 0.6.0 4d55e9ad63d1fae887726dffcd25a32def23d34f thats the latets one.eww 0.6.0 4d55e9ad63d1fae887726dffcd25a32def23d34f 这是最新的一个。

```
  dynamo   ~  sudo pacman -Qi eww
Deploying root access for dynamo. Password pls:
Name            : eww
Version         : 0.6.0-1
Description     : Standalone widget system made in Rust
Architecture    : x86_64
URL             : https://github.com/elkowar/eww
Licenses        : MIT
Groups          : None
Provides        : eww
Depends On      : libdbusmenu-gtk3  gtk3  gtk-layer-shell
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : eww
Replaces        : None
Installed Size  : 16.79 MiB
Packager        : Unknown Packager
Build Date      : Fri 19 Jul 2024 01:43:13 PM CST
Install Date    : Fri 19 Jul 2024 01:48:47 PM CST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None

  dynamo   ~    
```
This is the pacman -Qi result for eww,It was 0.6.0-1

**Comment by safe049** [comment]
Solved!the compile of eww is a little difficult but successfully installed. Now the CheatSheet is completely normal.
