### ISSUE TITLE
Pantalla de bloqueo de aspecto agradable mejora.

### ISSUE THREAD

**Issue by AlvinPix** [gh0stzk/dotfiles#285]
# Pantalla de bloqueo

Hola @gh0stzk, Primeramente quiero decir que muy buen trabajo, con estos dotfiles, tengo una idea que me gustaría que hagas si es que puedes, la cuestión es que no veo que tengas un lock screen atractivo ya que cuando bloqueo el sistema simplemente aparece una pantalla en negro diciendo que escriba mi contraseña.

Me gustaría que implementando herramientas como [betterlockscreen](https://github.com/betterlockscreen/betterlockscreen) y [i3lock-color](https://github.com/Raymo111/i3lock-color) se haga una pantalla de bloqueo dinamica tipo asi.

[lua-pam](https://github.com/RMTT/lua-pam)

![lockscreen](https://github.com/user-attachments/assets/6d8aabcb-9b62-4fcf-ac14-78560699cc36)

**Comment by gh0stzk** [comment]
Hola, gracias, si, de hecho es lo que estaba empezando por hacer, pero pushee primero otras cosas y ya en estos dias me iba a poner a esto que dices, por que igual mucha gente me lo ha pedido, si ando en eso, y se ve muy bien esa imagen que dejaste, lo anoto para ahora que este en eso, gracias.

**Comment by AlvinPix** [comment]
Exelente, que bueno que ya tenías pensado implementarlo, qué hago con el "issue"?, lo cancelo o lo dejo abierto hasta que terminas de agregar esa funcionalidad.

**Comment by gh0stzk** [comment]
La cierro, de todos modos desde hace meses tiengo en mi todo list hacerlo, solo que he agregado/modificado otras cosas pero ya le toca al lockscreen.
