### ISSUE TITLE
App auto start 

### ISSUE THREAD

**Issue by mrstretch** [gh0stzk/dotfiles#287]
Hi, it’s possible to have an auto start for firefox ? (and more apps)

**Comment by gh0stzk** [comment]
yes, add at the bottom of bspwmrc.

For example add `firefox` at bottom of bspwmrc

But need to be carefull, if u add a daemon you need to add & at the end, for example `sxhkd &` why?

for example if you do something like this:

```
whatever daemon
firefox
```

That will give u errors, must be:

```
whatever daemon &
firefox
```

but if u only wanna add firefox or apps that doenst run in background or demonize, just add it to bottom of file.

firefox
geany
ranger 
etc

**Comment by mrstretch** [comment]
thanks you it’s fixed
