### ISSUE TITLE
How to uninstall

### ISSUE THREAD

**Issue by Gamma195** [gh0stzk/dotfiles#290]
Hello!

I'd like to revert back to my own, I am kinda new to linux, so i'm not entirely sure how I would remove this theme?

**Comment by gh0stzk** [comment]
Hello, in the install process, a backup dir was created .RiceBackup, is in your home, you need to activate see hidden files in your filemanager. Then if you have a prev config, thre are your config files, just delete the actual ones and paste yours again.
