### ISSUE TITLE
Lazy - Plugins

### ISSUE THREAD

**Issue by LuiBi10** [gh0stzk/dotfiles#291]
Hey bro, 

Vengo utilizando tu coniguracion hace tiempo y esta excelente, sin embargo tengo un problema con Nvim, al revisar a traves del comando :Lazy me doy cuenta que hay unos plugins que aparecen como Not Loaded.  He revisado el init.lua y la confiiguracion es tal como la tienes (lazy  =  false,), lo que segun tengo entendido, deberia cargarlos todos. En este caso lo que me toca hacer es cargarlos manualmente (Lazy load plugin), cada vez que abro Nvim.  Sabes que puede estar afectando la carga? Cabe aclarar que el problema me esta sucediendo con los mismos plugins en mis dos pcs, ambos con la misma confguracion.

Muchas gracias por tus aportes y tu excelente trabajo

**Comment by gh0stzk** [comment]
![Shot-2024-08-14-154843](https://github.com/user-attachments/assets/8f01c57b-91b7-46fb-8b98-9e1c3f94879b)

Se parece algo asi????

**Comment by LuiBi10** [comment]
Si exactamente asi. 

> ![Shot-2024-08-14-154843](https://private-user-images.githubusercontent.com/67278339/358020011-8f01c57b-91b7-46fb-8b98-9e1c3f94879b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2NzI2MjEsIm5iZiI6MTcyMzY3MjMyMSwicGF0aCI6Ii82NzI3ODMzOS8zNTgwMjAwMTEtOGYwMWM1N2ItOTFiNy00NmZiLThiOTgtOWUxYzNmOTQ4NzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDIxNTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwODEwMWY4MTQwMTZiZmU0MjZkYjczOGNmM2EzNGZkOWQyNmY3ZThiYjRkZDMxOWRjZWIyZmE1MzM5NWE5ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7e8C1pxCdbPs7pkBtBd8GW7RYvC-P40JHgHSY94dIqY)
> 
> Se parece algo asi????

Si exactamente asi. Es porque lo tienes configurado asi? Disculpa, soy nueva en nvim

**Comment by gh0stzk** [comment]
Claro es normal y por eso nvim carga rapido, el lazy false, es como por default, pero dentro de cada plugin no en todos de hecho, aun me falta depurar, cada plugin tiene su configuracion, por ejemplo, si tu abres nvim asi simple, te muestra un documento en blanco por asi decirlo, entonces por ejemplo el plugin nvim-treesitter no se carga por que no tiene caso cargarlo cuando no estas en un documento que requiera treesitter que es "la sintaxis" solo se carga cuando abres un documento, o por ejemplo neo-tree, no se carga el plugin hasta que tu explicitamente abras neo-tree "ctrl + n"

Solo se cargan algunos plugins cuando se requieren. Esa es la magia de lazy, y si ahora abres un documento, un script bash por ejemplo, y vuelves a ejecutar :Lazy, veras que nvim-treesitter ya se cargo.

No tienes que cargarlos manualmente, solito el pluging, con alguna accion, o interaccion o cuando se necesite cargara el plugin.

**Comment by gh0stzk** [comment]
Pero ya que me recordaste, lo hare en estos dias, tengo tiempo de no pulir la configuracion de nvim, por telescope y spectre tampoco tienen caso que se carguen cuando abres nvim, si no hasta que los usas, y yo rara vez uso telescope, uso mas neo-tree, entonces tampcoo tiene caso que se carguen al inicio.

**Comment by LuiBi10** [comment]
Entiendo totalmente, en mi caso si uso  mucho el tree-sitter y me tocaba cargarlo manualmente, es decir no se como se activa por default. De todas formas tienes razon,  no uso la mayoria de los plugins no cargados, como te comentaba lo hago por tree-sitter y los highlights colors ppalmente y telescope aunque como mencionas se puede cargar con el shortcut.  Hice la prueba con nvim-ranger y ese si me toca que cargarlo porque bajor el shortcut asignado no me funciona, entonces lo cargo y luego apliico <leader> r y para que pueda funcionar.

**Comment by gh0stzk** [comment]
Treesitter deberia cargarte siempre que abras un documento o crees uno nuevo, no se en que tipo de archivo no te carga automaticamente, no es necesario cargarlo manualmente, usa :checkhealth nvim-treesitter pero siempre deberia cargarte e incluso si es un lenguaje de programacion que abres por primera vez, deberia instalarse automaticamente.

Acerca de ranger, en mi configuracion local, ya no lo tengo, se me hacia un exceso, tener tres filemanagers o navegadores de archivos, con telescope y neo-tree creo que es sufuciente.

Pero si quieres estar seguro que siempre se cargara abre el archivo de nvim-treesitter.lua

```lua
return {
	{
		"nvim-treesitter/nvim-treesitter",
		event = { "BufReadPre", "BufNewFile" }, -- load when a buffer is opened or created
		build = ":TSUpdate",
		config = function()
			local config = require("nvim-treesitter.configs")
			config.setup({
				auto_install = true,
				highlight = { enable = true },
				indent = { enable = true },
			})
		end,
	},
}
```
Y borra esta linea 
`event = { "BufReadPre", "BufNewFile" }, -- load when a buffer is opened or created`

Asi no deberias tener problemas, si aun falla, actualiza el plugin :Lazy y sobre el plugin de treesitter aprieta "u" y se actualizara.

**Comment by LuiBi10** [comment]
En efecto corri el checkhealth y tenia problemas con tree-sitter.  Gracias por aclarar mi duda, no tenia muy claro que algunos plugins se cargan automaticamente y los keybinds que los ejecutaban. 

Muchas gracias, duda solucionada.

**Comment by gh0stzk** [comment]
Genial, cierro el issue.
