### ISSUE TITLE
On uninstall removes ability to open neovim

### ISSUE THREAD

**Issue by rozodru** [gh0stzk/dotfiles#292]
regardless of replacing the config neovim no longer opens via launchers (rofi, ulauncher, kde launcher, etc) on uninstall of theme package. tested several times on reinstall and uninstall.

**Comment by gh0stzk** [comment]
Open a terminal, and launch nvim, whats the output?

**Comment by rozodru** [comment]
launches via terminal but no longer launches via any terminal and gives error "could not find program 'openapps'"

**Comment by gh0stzk** [comment]
oh i see, openapps, is my script to open apps like nvim, Let me understand, you removed my configuration, but you are using something from my config? It is the only reason I can find for opening nvim to call openapps first, are you still in bspwm? I don't understand why openapps is still being called, mmmm open the file ~/.config/mimeapps.list is there any reference to openapps there??? what rofi launcher are you using?

**Comment by rozodru** [comment]
not using anything from your config. everything went back to my previous configs. not using bspwm went back to plasma and nothing for openapps in mimeapps. as far as launchers go i'm using Ulauncher and the KDE launcher, not using rofi.

**Comment by gh0stzk** [comment]
Oh sorry i already know whats happening, delete file ~/.local/share/applications/nvim.desktop
