### ISSUE TITLE
¡Mejora construcción de atajos de teclado neovim!

### ISSUE THREAD

**Issue by AlvinPix** [gh0stzk/dotfiles#295]
# Atajos de teclado nvim

Hola @gh0stzk un placer saludarte, he estado probando tu configuración de nvim y si es bastante rápida y me gusta, lo único malo o inconformidad que le encuentro es que no tienes un archivo explicativo de los atajos de teclado para tu configuración.

Me gustaría que la construcción de atajos de teclado sea algo parecida a como lo es [Nvchad](https://nvchad.com/) , simplemente con teclear en "espacio" te muestra los atajos de teclado.

![Shot-2024-08-15-184036](https://github.com/user-attachments/assets/a9115029-110e-4168-b6c5-fd41431b0813)

**Comment by gh0stzk** [comment]
Hola, si ese es el plugin nvim-which creo que se llama, si, en su momento lo quise poner pero algo no andaba.. no recuerdo que, ahora tengo mas conocimiento, igual lo puedo hechar a andar, y aunque no muestra todas las shortcuts, el archivo keymaps.lua solo muestra unas. aunque he dejado las nativas para nvim y los plugins, pero si supongo para los nuevos necesitan algo asi como la imagen que muestras. Desde hace dias quiero subir unos nuevos shortcuts que le tome a primigean muy buenos pero no me ha dado tiempo. igual ya termine de actualizar las cosas de bspwm, solo me falta agregar un modulo de el layout del keyboard y un applet para cambiar entre layouts. Pero ya me pondre de nuevo con nvim, justo hoy hice unos cambios a unos scripts para que se carguen solo cuando se necesitan y pum el doble de rapido a como estan los del repo, en fin, si, en eso andare proximamente gracias.

**Comment by AlvinPix** [comment]
Excelente, que bueno que tenías pensado de antemano eso, tranquilo tómate el tiempo que sea necesario para hacer todas estas mejoras, ya que realmente son muchas cosas y no se como anda tu agenda en cuestión con el tiempo que le dedicas estos increibles [dotfiles](https://github.com/gh0stzk/dotfiles), con el tiempo si puedes me gustaria colaborar más en estos [dotfiles](https://github.com/gh0stzk/dotfiles), pero ya veremos en un futuro, saludos.
