### ISSUE TITLE
hi..

### ISSUE THREAD

**Issue by ekremx25** [gh0stzk/dotfiles#296]
i am new .. how change keyborad lang.. also how i can swish other windows...

**Comment by AlvinPix** [comment]
Hi, to change the keyboard language permanently edit the configuration file `/etc/vconsole.conf`

![image](https://github.com/user-attachments/assets/40079122-d099-409d-b697-d5fe0d07ce00)

To change windows very easily, press the "Win" key plus the "window number", which would be from 1 to 6. Regards.
