### ISSUE TITLE
Ncmpcpp Error

### ISSUE THREAD

**Issue by thatshab29** [gh0stzk/dotfiles#297]
I am getting the following error when i run ncmpcpp command in the terminal:
![image](https://github.com/user-attachments/assets/bf20668f-ebc1-4345-8297-1494988f18bf)
Also the shortcut doesnt work too..
I am new and i am sorry if the issue is dumb

**Comment by gh0stzk** [comment]
yep the problem is that you have already a ncmpcpp config in your home dir, and now  you have 2 ncmpcpp configs, remove the one in home folder, /home/thatshab/.ncmpcpp
