### ISSUE TITLE
error al ejecutar ./RiceInstaller

### ISSUE THREAD

**Issue by jorgesnz** [gh0stzk/dotfiles#299]
Hola, que tal? Cuando ejecuto ./RiceInstaller recibo el siguiente error:

![image](https://github.com/user-attachments/assets/7334536f-09e6-4a9e-a89a-8358ca75c6f2)

Agradeceria vuestra ayuda:)

**Comment by gh0stzk** [comment]
Hola, al parecer el archivo se descargo mal, o hubo un error al poner la direccion y envio a una pagina de error y esa fue la que se descargo, acabo de probar y funciona con normalidad. intenta descargarlo de nuevo.

`curl https://raw.githubusercontent.com/gh0stzk/dotfiles/master/RiceInstaller -o $HOME/RiceInstaller`

**Comment by jorgesnz** [comment]
Hola, ejecuto ese comando me da el siguiente error:
![image](https://github.com/user-attachments/assets/b5da8f4d-58d7-4a61-b6f9-bd1cc0f8859a)
Por eso probe este comando 
curl -k https://raw.githubusercontent.com/gh0stzk/dotfiles/master/RiceInstaller -o $HOME/RiceInstaller
 y me hizo una descarga pero al parecer lo la correcta.

**Comment by jorgesnz** [comment]
Ups excuse me! thank you so much! :)
