### ISSUE TITLE
how to change polbar position and height in z0mbi3 theme

### ISSUE THREAD

**Issue by expandpi** [gh0stzk/dotfiles#3]
Hello!

First I want to say it's really awesome work and thanks for the dot files.

How can I change the position of polybar in z0mbi3 theme? I want to increase the height of it to 90% and change to position to the more left side because it is taking space.

Thanks

**Comment by gh0stzk** [comment]
You need to edit eww.yuck from ./config/bspwm/rices/z0mbi3/bar/ 
from line 231 to 234

**Comment by expandpi** [comment]
Hey! thanks for your reply.

I change it but now all applications still can't occupy all space. As u can see in the image I want to reduce the distance between the bar and the application. Can u please help me with that?
Sorry, I am new to tilling-wm and this is my first ricing.
![image](https://user-images.githubusercontent.com/39010717/191205779-1c8b1d8a-4f05-49eb-8dc0-c9bf6a5921cc.png)

**Comment by gh0stzk** [comment]
Sure no problem. In .config/bspwm/scripts/LaunchWorld in line 160 you will find this line;

`SetBspwmConf 0 5 5 "#161616" "#161616" "#161616" "#4f4f5b" 95 5`

You need to change the 95 value, you need to decrease it.

And if some day u need to use the "Super + h" to hide and unhide the bar, when u unhide it the result will be like in your image, so you need to edit file .config/bspwm/scripts/hu-polybar in line 54 you need to change again the 95 for the number you edit above.

**Comment by expandpi** [comment]
Thanks and you are really helpful.
It's awesome rice.
