### ISSUE TITLE
La terminal no me muestra correctamente el texto

### ISSUE THREAD

**Issue by jorgesnz** [gh0stzk/dotfiles#300]
![image](https://github.com/user-attachments/assets/f574c7cb-96d9-4696-bc2c-371012335f96)
Hola cuando abro la terminal, se ve asi. Al limpiarla y escribir igual, he probado ctrl+c y nada

**Comment by gh0stzk** [comment]
wow, nunca alguien habia venido con ese problema, y nunca me ha pasado, lo primero que se me puede ocurrir es si la fuente que usa la terminal se instalo correctamente, puedes escribir `pacman -Qi ttf-jetbrains-mono-nerd` si no puedes escribir en la terminal, oprime `ctrl + alt + f4` te llevara a una tty, ingresa tu usurio y password y pon el comando, para regresar al entorno solo oprime `ctrl + alt + f7` f7 en el caso que estes usando lightdm como login manager, si no puede ser F1  si no estara entre el F1-7

**Comment by jorgesnz** [comment]
He hecho lo que me has dicho, pero sigue viendose igual. He reiniciado y se sigue viendo igual. Que mas puedo hacer?
![image](https://github.com/user-attachments/assets/516e1911-dbcb-40d8-be93-961cf7821529)

**Comment by gh0stzk** [comment]
Ok, me puedes decir que sistema estas usando, arch o derivadas? y si estas en una maquina virtual.

me puedes poner tu archivo de configuracion de alacritty, ~/.config/alacritty/alacritty.toml

**Comment by jorgesnz** [comment]
Estoy usando un sistema arch en virtualbox

![image](https://github.com/user-attachments/assets/d46fe27b-4072-4385-aaaf-0f1b8edf9e52)

**Comment by gh0stzk** [comment]
Mmmmm, me equivoque, era el archivo fonts.toml no alacritty.toml, pero la fuente deberia estar seteada a 10.

La verdas es que nunca habian llegado con este problema, casi seguro es por algo de la maquina virtual, ahorita que tengo tiempo, buscare algo al respecto, si encuentro algo te aviso aqui.

**Comment by jorgesnz** [comment]
Justo acabo de hacer edit en el post anterior. Okay, muchas gracias!

**Comment by gh0stzk** [comment]
Intenta desactivando la aceleracion HW acceleration en virtualbox e intenta de nuevo iniciando tu maquina virtual.

**Comment by jorgesnz** [comment]
que deshabilitado la aceleracion 3d pero me esta funcionando mas lento  y no me carga nada. Cuando intento abrir algun ventana se congela

**Comment by gh0stzk** [comment]
Haber si es esto: escribe el la terminal `locale` y ponme que te aparece

**Comment by gh0stzk** [comment]
Otra pregunta, ademas de bspwm tienes plasma instalado??

**Comment by jorgesnz** [comment]
No tengo plasma instalado. Me aparece esto:
![image](https://github.com/user-attachments/assets/11f4f9b2-15e2-4ab9-bc95-bddf9dbef5bf)

**Comment by gh0stzk** [comment]
Mmmmm pues tus locales tambien estan bien.. lo otro que he encontrado es referente al escalado en virtualbox, modificar el escalado, solo te pasa con las terminales que son aceleradas con gpu y eww o con todo?? veo que la barra muestra bien la fuente, si abres firefox u otra aplicacion se muestra bien???

si instalas xterm, se muestra correctamente el texto?

Yo creo que es algo referente a la aceleracion de hardware de virtualbox, puedes abrir el archivo picom.conf en el directorio bspwm y cambiar donde dice backend = "glx" por backend = "xrender" solo por saber... si cambia algo.

**Comment by jorgesnz** [comment]
Todo lo demas eexceptuando a los widgets y las terminales parece que funciona correctamente.
![image](https://github.com/user-attachments/assets/960cf92e-8c26-4588-ab22-8f6a7857b993)

![image](https://github.com/user-attachments/assets/8dddea29-e87e-4129-89dc-28b04520b6d4)

He probado a instalar xterm y modificar el archivo picom.conf y nada. He reiniciado y nada sigue igualHe probado a instalar xterm y modificar el archivo picom.conf y nada. He reiniciado y nada sigue igual. Tmbien he probado volviendo a instalar eww pero nada :(

**Comment by gh0stzk** [comment]
Instala la terminal tilix, `sudo pacman -S tilix` una vez instalada, abrela, esperando que muestre el texto bien, y desde tilix, escribe `alacritty` para lanzar alacritty, y a ver que errores muestra ahi si es que los muestra o si los hay.

La verdad es que nunca habia lidiado con un problema asi, varios usan mis dots en maquinas virtuales y el problema mas recurrente es que es lento pero cambiando de glx a xrender se soluciona. Pero este problema me agarra sin una solucion.

**Comment by jorgesnz** [comment]
Okay justo acabo de actualizar el anterior post

**Comment by jorgesnz** [comment]
![image](https://github.com/user-attachments/assets/de624f71-a144-480f-b400-818503945a88)
![image](https://github.com/user-attachments/assets/a4cab252-7263-4cff-98a7-37c859c0508a)

**Comment by gh0stzk** [comment]
La verdad es que no sabria decirte, en hardware real, he probado mis dots en mis 5 pcs incluyendo laptops y con graficos amd, intel, nvidia, funcionan bien y mas que eso, nunca he tenido el error que tu tienes. Por supuesto que es un mundo enorme y hay gente que tiene todo tipo de problemas, como que rofi no les abre y en el 100% de los casos es por que no generaron sus locales, cosas asi.. y diria que en el 95% de los casos es error en el os de parte de el usuario, errores como el que te menciono de rofi, al final mis dots solo son archivos de configuracion, agarran en todos lados, pero tu error nunca lo habia tenido por aqui, posiblemente sea por la maquina virtual, por que en hardware real si que funciona todo sin problemas.

**Comment by gh0stzk** [comment]
lanza alacritty con estas flags se me olvido decirte `alacritty -vv`

**Comment by jorgesnz** [comment]
![image](https://github.com/user-attachments/assets/181b0111-58f7-47b0-a4b9-f6899fbf7bfa)

**Comment by gh0stzk** [comment]
Uhmmm pues no muestra ningun error, lo ultimo que me quedaria por pensar seria si en tu arch tienes todos los paquetes necesarios para la correcta ejecucion de la aceleracion grafica, no se que paquetes se instalen en arch para graficos de visrtualbox svga3d, ademas de mesa, o si instalaste las guest additions, https://wiki.archlinux.org/title/VirtualBox , no se la verdad no uso virtualbox, yo uso qemu/virt-manager dentro de arch. Tu maquina host es windows?

**Comment by jorgesnz** [comment]
Si es windows

**Comment by gh0stzk** [comment]
Si, con graficos spice y el render xrender funciona sin problemas, igual no es que haya pasado muchos dias en la vm, genralmente instalo una para probar algo antes de probarlo en hardware real, pero las terminales abren sin problema.

**Comment by gh0stzk** [comment]
Y windows solo lo uso para jugar, la verdad tampoco podria ayudarte mucho con virtualbox y windows.

**Comment by jorgesnz** [comment]
Sigue igual :( Muchas gracias por la ayuda igualmente!

**Comment by gh0stzk** [comment]
Por ultimo, dentro de arch, abre tilix e instala `sudo pacman -S virtualbox-guest-utils` despues habilitalo, `sudo systemctl enable vboxservice` y reinicia.

**Comment by jorgesnz** [comment]
ahora puedo notar que va mas fluida y se ve bien en pantalla completa pero la termina sigue sin leerse bien
