### ISSUE TITLE
EWW profile widget and other widgets problem(solved)

### ISSUE THREAD

**Issue by Zapelmon** [gh0stzk/dotfiles#301]
Hello, it's me again, the person who couldn't set up and configure your script last time. Since then, I've installed the script several times, but I've been trying hyprland all this time. However, for a long time now, my choice has fallen on bspwm and your script. Overall, I figured out how to install it without any errors, but I still have some questions; however, some of them are more related to xorg than to bspwm.

The first question I'd like to ask:
-How do I remove tearing on the screen? The UFO test and visually I see terrible image tearing, and creating a config in picom doesn't work. I'm not asking you to figure it out; it's just that I can't find a working method. Even creating a config in x11 for an Intel graphics card doesn't help, or I am doing it wrong.

The second question I'd like to ask:
-How do I change the avatar in menu that shows when I click on the "user" icon?

The third question I'd like to ask:
-How do I remove "Images" when launching the terminal? I respect the creativity of those who made them, but they interfere a bit and slow down work.

And the fourth question:
-I want to create my own theme; however, I want to modify one theme that I like the most (change text, color scheme), make backups of it, and remove other themes from the selection list. This also applies to desktop photos.
I read the wiki and will figure it out for sure; however, I'm particularly interested in this point. 
I'm also curious how to change the language of the text displayed in the bar (Ram, NET, VOL, date etc.) to my preferred language. I'll be grateful for any guidance!
If these issues have already been addressed in other inquiries and I haven't found them, please send those to me for reading instead of writing everything anew and wasting your time.
^-^

**Comment by gh0stzk** [comment]
Hello!!

1. What graphics you have? amd? intel? other? in x11 to get rid of tearing you must create a file in /etc/X!!/xorg.conf.d/ with the name 20-intel.conf or 20-amd.conf

20-intel.conf : 
```
Section "Device"
	Identifier	"Intel Graphics"
	Driver		"Intel"
	Option		"AccelMethod"	"sna"
	Option		"DRI"		"3"
	Option		"TearFree"	"true"
	Option 		"TripleBuffer" "true"
EndSection
```

20-amd.conf : 
```
Section "OutputClass"
     Identifier "AMD"
     MatchDriver "amdgpu"
     Driver "amdgpu"
    Option "TearFree" "true"
EndSection
```
Reboot and your are done.

2. The image is located in ~/.config/bspwm/assets/profile.png  just overwritte the profile.png with your image, try to the new image have the same or similar size, the size is 260x260

3. To remove the ascii art from the terminal you only need to delete the last line in ~/.zshrc 
`$HOME/.local/bin/colorscript -r`

4. To modify or create your own theme, basically edit the Theme.sh inside every rice, and edit the color variables at the beggining of the file, bg, fg, black, blackb, red, redb etc.. you only need to edit that, for the colors in terminals, rofi, eww. And to change the image of rofi launcher, just create your own one with the name rofi.webp inside rice dir.

To change the bar text, just open the modules.ini, and edit the modules.

**Comment by Zapelmon** [comment]
Thank you! I tried removing tearing, but in ehat i founded there was no 
Option	"AccelMethod" "sna"
Option	"DRI" "3"
That helped!
Regarding themes, I practically understood everything. The only thing left is to understand how to back up and remove other themes except the one I create, since I am not a fan of changing themes that often.
Closing the "issue" so it doesn't stay open, but if you see this and add information on how to change the displayed themes in the theme selector and wallpaper selector, I would be very grateful! Looking forward to any advice, as I have little knowledge about bspwm and your config, but I really liked everything.
^-^

**Comment by Zapelmon** [comment]
Unfortunately, I have to reopen the ticket. Something goes wrong at the stage of changing the picture. It happened on the system where I initially opened the ticket and on the current reinstalled one as well. In short, I change the profile picture to an image that I exported from GIMP, resized to 260x260 as instructed. After that, strange things happen with the profile menu. Sometimes it works correctly, but most often it doesn't. Even though I haven't set up the weather, it sometimes appears and then disappears completely. The same goes for my name and host name — they appear and disappear randomly. After changing the image, the backlighting of keys (WiFi, Bluetooth, airplane mode, night mode, etc.) breaks completely, although they still function correctly. It looks something like this:
![image](https://github.com/user-attachments/assets/96033d51-2f1d-4a14-a73f-8a767e9764d2)
This might be caused by the fact that I am installing a different driver than the one that comes with the system installation, as without it, tearoff doesn't work:

```bash
sudo pacman -Syu
sudo pacman -S xf86-video-intel
sudo mkdir -p /etc/X11/xorg.conf.d/
sudo nano /etc/X11/xorg.conf.d/20-intel.conf
```

Where I insert:

```
Section "Device"
 Identifier "Intel Graphics"
 Driver "intel"
 Option "TearFree" "true"
EndSection
```

And yes, sometimes monitoring the CPU and RAM states works, sometimes it doesn't. As far as I understand, it's a matter of chance.

**Comment by Zapelmon** [comment]
Changing intel config to 
```
Section "Device"
	Identifier	"Intel Graphics"
	Driver		"Intel"
	Option		"AccelMethod"	"sna"
	Option		"DRI"		"3"
	Option		"TearFree"	"true"
	Option 		"TripleBuffer" "true"
EndSection

```
don't do anything

**Comment by Zapelmon** [comment]
I think I should also clarify something else. It could very well be an incompatibility between the graphics card driver and the graphics card itself:
![image](https://github.com/user-attachments/assets/4448b5aa-076d-4e62-814c-486076ac29f0)
Just in case it might be caused by the graphics card driver or something like that.

**Comment by gh0stzk** [comment]
1. check if scripts have execution permission in ~/.config/bspwm/eww/profilecard/scripts/ all of them.
2. try changing the picom backend, open ~/.config/bspwm/picom.conf and in backend option, change glx to xrender. kill picom `pkill picom` and reload bspwm `super + alt + r` check if that fix the issue.

About your graphics yes maybe related, if graphics doesnt work well, picom could be inestable. you have an 6th generation card, sandy bridge, i dont remember but you dont need xfs86-video-intel, check the arch and gentoo wiki, gentoo wiki have a generation table, did you install the hardware acceleration packeges?

**Comment by gh0stzk** [comment]
and check in logs dir, ~/.cache/eww   there are logs for eww.

**Comment by Zapelmon** [comment]
So, I double-checked if hardware acceleration is enabled and made sure that video and input are in the user groups. I followed all the suggested actions, and changing the backend led to a slightly lower RAM consumption (to my surprise), which made me happy. However, the problem remains. In the eww logs, there are only 3 files, and when viewed through nano, they are all empty.

What I can say based on the outcome:
I would like to ask you to think of something based on the current picture.
Namely, the panel behavior is absolutely random. And it's different every time after pressing `super+alt+r`.
Sometimes the menu appears immediately upon pressing and either works correctly or not; sometimes it opens after multiple presses (since without spamming it doesn't open even if pressed many times with long intervals) in a faulty state; and sometimes it opens after spamming in a fully functional state. Sometimes when it opens in a faulty state, after some time (around 5 minutes), there's a kind of lottery, and it might fix itself and work as expected.
In case this might be a hardware issue, is there any way to further reduce the shell's consumption?
I'm willing to sacrifice smoothness for stability and possibly degrade visuals and "squarize" windows and bars.
I can also give up transparency if that could help. Once again, I apologize for reaching out with minimal knowledge about bspwm and Arch Linux in general. I will also try to find a solution myself but **kindly** ask you to review this case once more and possibly request specific logs or videos showing how this menu behaves.

**Comment by Zapelmon** [comment]
btw, killing picom don't solving this, even when picom is gone, menu is still having a bad times

**Comment by Zapelmon** [comment]
A little update. It seems that if I wait for a sufficient amount of time (more than a minute), the frequency of successful menu activations increases significantly. However, when entering the browser and other applications, it often breaks down. The worst case is trying to launch with the browser already running.

**Comment by 0xN1nja** [comment]
@Zapelmon did you try setting `vsync = true` in `picom.conf`?

**Comment by Zapelmon** [comment]
> @Zapelmon did you try setting `vsync = true` in `picom.conf`?

I installed it; on average, it increases the number of partially successful launches. That is, most of the information is displayed, but the CPU loading icons remain static and wifi and etc too (it seems to me that the degree of completely fatal launches has decreased)
It is dependent on the music widget, and if most of the information is displayed but the icons are static, theme switching stops working(even after super+esc). If the launch was completely fatal (almost nothing is displayed), the ability to change themes and the image in the music widget remain functional. The "shutdown" widget, etc., correctly displays uptime, whereas in the profile widget, everything stays at the values from the first launch. (Restarting bspwm doesn't always work; maybe it's an issue with eww?)

**Comment by Zapelmon** [comment]
And, when everything launches fine, other widgets and etc. wokring fine too...
I just can't understand why is it sometimes bugging so bad, but sometimes working fine.

**Comment by gh0stzk** [comment]
Try compiling eww from source, maybe that will fix, the eww in my dots its a pre compiled binary.
remove the the actual one in /usr/bin/ `sudo rm /usr/bin/eww`

`git clone https://github.com/elkowar/eww`

`cd eww`

`cargo build --release --no-default-features --features x11`

once it finished 

`cd target/release`

`chmod +x eww`

`sudo install -Dm755 eww /usr/bin/eww`
