### ISSUE TITLE
Extraño error neovim

### ISSUE THREAD

**Issue by AlvinPix** [gh0stzk/dotfiles#302]
![image](https://github.com/user-attachments/assets/d93a5f85-f0a3-49e5-8807-edc0d9cc9a5f)

Hola @gh0stzk tengo un error algo extraño con el neovim, no se el porque se marcan esas líneas espaciadas a lante, te dejare una imagen para que puedas ver.

**Comment by gh0stzk** [comment]
Te refieres a la linea vertical y a la linea que esta sobre el puntero??

la primera es la opcion colorcolum que raro, pense que desde hace mucho estaba habilitada en la config de los dots.. bueno si no la quieres, entra al archivo vim-options.lua y comenda la linea `opt.colorcolumn = "80"` o borrala.

la otra es cursorline `opt.cursorline = true` solo cambiala a false.

Pero eso no la deshabilitara, ya que me acabo de dar cuenta que tambien esta seteada en el plugin del tema, abre onedarkpro.lua y la linea que duce cursorline = true, eliminala. esta debajo de lualine_transparency.

**Comment by AlvinPix** [comment]
Gracias comentando la linea, `opt.colorcolumn = "80"` y cambiando la opción de true a false `opt.cursorline = true` se soluciona esas cuestiones.
