### ISSUE TITLE
How to change the cheatsheet keybind?

### ISSUE THREAD

**Issue by safe049** [gh0stzk/dotfiles#303]
I was playing Battlefield 1 and trying to switch my seat in vehicles to first one so i need to use F1
But it jump out a keybind cheatsheet for me
How can i change the cheatsheet keybind to something like "Ctrl+F1"?

**Comment by safe049** [comment]
Already solved,just change the sxhkdrc file under ~/.config/bspwm

**Comment by Maty1ek** [comment]
i tried it, saved the file, reloaded that thing with wm, restarted my laptop, but nothing works( i mean nothng changes and everything works only with old shortcuts

**Comment by 0xN1nja** [comment]
@Maty1ek try changing the keybinding to `super + shift + F1`
