### ISSUE TITLE
No Sound on minimal arch 

### ISSUE THREAD

**Issue by KingStan0** [gh0stzk/dotfiles#305]

**Comment by 0xN1nja** [comment]
Install an audio server like `pipewire` (and some other dependencies):

`sudo pacman -S pipewire pipewire-pulse sof-firmware alsa-utils`

**Comment by KingStan0** [comment]
> Install an audio server like `pipewire` (and some other dependencies):
> 
> `sudo pacman -S pipewire pipewire-pulse sof-firmware alsa-utils`

**Comment by gh0stzk** [comment]
yeah but this not a probelam with dotfiles, yo need to already have your setup.
