### ISSUE TITLE
Customize Question:How do i add a round corner?

### ISSUE THREAD

**Issue by safe049** [gh0stzk/dotfiles#309]
i'm using my customized Karla rice,that's my favorite,but i think if it could have a round corner to the windows it will be better

maybe just like something like this:
![图片](https://github.com/user-attachments/assets/551bd8e7-e257-40f7-9915-3e19e11be13b)
I found this on reddit:
[Can I somehow get rounded corners? I have set it in picom but bspwm still tries to be square
](https://www.reddit.com/r/bspwm/comments/umfcye/can_i_somehow_get_rounded_corners_i_have_set_it/)

And that image above there is from this comment:

 > Phopaa

> I've been able to achieve rounded corners using the base picom and bspwm applications.
> 
> [Here's a link to some images verifying it.](https://imgur.com/a/ZAyMDTk)
> 
> It's not perfect by any means; there is a tiny shadow on the edges where the 'point' still is, but it's faint. Make sure you're starting picom in your .xinitrc or .xprofile if you're using a DM.
> 
> picom --config $HOME/.config/picom/picom.conf --experimental-backends -b &
> 
> The process might be starting as a root command; I believe you can kill it with a sudo killall picom command

So,how do i add a round corner like that?

**Comment by safe049** [comment]
BTW,where should i config the weather now? there is no script file

**Comment by gh0stzk** [comment]
Hello the weather script is in ~/.config/bspwm/src/ Weather file.

About rounded corners, in theme.sh inside karla directory modify the variable `P_CORNER_R="0"` on line 21, change 0 for whatever you want.

**Comment by safe049** [comment]
@gh0stzk Solved!
Looks pretty cool!
![图片](https://github.com/user-attachments/assets/95d04f3a-8841-4fa9-9ed8-4fc1debc7ef9)
Thanks
