### ISSUE TITLE
How to change cards?

### ISSUE THREAD

**Issue by vmxt** [gh0stzk/dotfiles#311]
Hi serious question, after installing the setup. how to change the card and weather location?

![Shot-2024-09-03-181938](https://github.com/user-attachments/assets/23c0f747-a7b8-4bda-b426-6bb29c0af928)

**Comment by 0xN1nja** [comment]
Open `~/.config/bspwm/src/Weather` on line 13, change city to your desired value

**Comment by vmxt** [comment]
works fine. and what about the card icon? where I can locate?

**Comment by 0xN1nja** [comment]
The profile picture is located at `~/.config/bspwm/assets/profile.png`.

**Comment by vmxt** [comment]
Thank you @0xN1nja
