### ISSUE TITLE
Missing music player at the top right corner

### ISSUE THREAD

**Issue by vmxt** [gh0stzk/dotfiles#312]
![image](https://github.com/user-attachments/assets/cd67466c-564f-472a-a624-2de01fe66021)

What went missing? I just do a plain installation is there any aur package for music player to install? there is no player display at the top right

**Comment by gh0stzk** [comment]
what is missing? i dont understand? a control buttoms? like play , stop, next etc??

**Comment by vmxt** [comment]
@gh0stzk yes it looks like it's missing

**Comment by 0xN1nja** [comment]
@vmxt have you added songs to playlist (in ncmpcpp)?

**Comment by gh0stzk** [comment]
You need to configure mpd https://github.com/gh0stzk/dotfiles/wiki/MPD-Configuration

**Comment by vmxt** [comment]
thanks for the guide works on my end
