### ISSUE TITLE
Configure two monitors

### ISSUE THREAD

**Issue by PapuchoX2X** [gh0stzk/dotfiles#314]
I paste the code in ~/.config/bspwm/bspwmrc in line 26
'''
	# change these values according to your system
	# you can use `xrandr -q` to get the names of monitors
	INTERNAL_MONITOR="eDP"
	EXTERNAL_MONITOR="HDMI-A-0"
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$EXTERNAL_MONITOR" -d '' '' '' ''
		bspc monitor "$INTERNAL_MONITOR" -d '' '' '' ''
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	else
		bspc monitor "$INTERNAL_MONITOR" -d '' '' '' '' '' '' '' ''
	fi
'''
and change de values of INTERNAL_MONITOR and EXTERNAL_MONITOR
and nothing happens.
can you help me please?

**Comment by guidamiao** [comment]
I don't know if this helps you, but I did it this way... and then with xrandr I defined the positions of the monitors, however, every time I turn it on I start autorandr to get the configuration I made with the correct guidelines.

![image](https://github.com/user-attachments/assets/b3d205fb-872c-4799-bf6a-344147c19187)

 change these values according to your system

	# you can use `xrandr -q` to get the names of monitors
	INTERNAL_MONITOR="HDMI-0"
	EXTERNAL_MONITOR="DP-1"
	if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
		bspc monitor "$EXTERNAL_MONITOR" -d '1' '2' '3' '4'
		bspc monitor "$INTERNAL_MONITOR" -d '5' '6' '7' '8'
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
	else
		bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8'
	fi

**Comment by vmxt** [comment]
> I don't know if this helps you, but I did it this way... and then with xrandr I defined the positions of the monitors, however, every time I turn it on I start autorandr to get the configuration I made with the correct guidelines.
> 
> ![image](https://private-user-images.githubusercontent.com/75124156/366446555-b3d205fb-872c-4799-bf6a-344147c19187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTEzNzQsIm5iZiI6MTcyNjMxMTA3NCwicGF0aCI6Ii83NTEyNDE1Ni8zNjY0NDY1NTUtYjNkMjA1ZmItODcyYy00Nzk5LWJmNmEtMzQ0MTQ3YzE5MTg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDEwNTExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5YzBhMTBiZjJlNmE4OWQ2OTczMzVlMjk1YWI0NmE3OWExNWQyZmY2NDI3OTk1YzQ4YWMxMzdjZmRlNjRlYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H61F4pf3tgvwKuUDaYV9gkgAInM0TAUmRFhBnwI21ZE)
> 
> change these values according to your system
> 
> ```
> # you can use `xrandr -q` to get the names of monitors
> INTERNAL_MONITOR="HDMI-0"
> EXTERNAL_MONITOR="DP-1"
> if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
> 	bspc monitor "$EXTERNAL_MONITOR" -d '1' '2' '3' '4'
> 	bspc monitor "$INTERNAL_MONITOR" -d '5' '6' '7' '8'
> 	bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
> else
> 	bspc monitor "$INTERNAL_MONITOR" -d '1' '2' '3' '4' '5' '6' '7' '8'
> fi
> ```

[+1] this one works on my end
