### ISSUE TITLE
Lo siento, no es un issue

### ISSUE THREAD

**Issue by Ramdonx** [gh0stzk/dotfiles#316]
Hola quisiera pedirte ayuda para configurar el poder moverse entre espacios de trabajo usando Super + Tecla numerica (Pero del teclado numerico) Actualmente está configurado para funcionar con la linea numerica. He intentado y no logro hacer que funcione como quiero, mi configuracion es esta: 

# focus or send to the given desktop (La normal de siempre)
super + {_,alt + }{1-9,0}
        bspc {desktop -f,node -d} '^{1-9,10}'

super + {_,alt + }KP_{1-9,0}  (Con el teclado numerico)
    bspc {desktop -f,node -d} '^{1-9,10}'

Funcionan ambas, pero para el teclado numerico necesito usar Super + Shift + Numero, lo cual se me hace extraño.

**Comment by gh0stzk** [comment]
Tendre que buscas y desempolvar mi teclado viejo, actualmente uso uno de 75% pero si no mal recuerdo deberia funcionar, hoy sabado no podre por falta de tiempo pero mañana saco el teclado viejo y pruebo.

**Comment by Ramdonx** [comment]
Hola, conseguiste hacerlo funcionar?

**Comment by gh0stzk** [comment]
Hola, justo ando en eso, modifica KP por KP_ reinicia sxhkd con super + esc y ve si funciona asi.

**Comment by Ramdonx** [comment]
Nada, no me funciona.
Ya que estamos, hay alguna forma de abrir el lanzador de aplicaciones solo con la tecla Super?

**Comment by gh0stzk** [comment]
Puedes abrir una terminal y poner el comando `xev` en la ventana que se te abre oprime los numeros del teclado numerico y mira que valor tienen por ejemplo en el teclado viejo que conecte es KP_, tal vez el tuyo sea diferente por eso no funciona.

Solo modifica el shortcut del lanzador dejandolo solo como super, pero eso te traera muchos problemas, ya que super se usa con casi todos los shortcuts, y cada que oprimas super se te abrira el lanzador rofi y ya no te dejara oprimir mas teclas y quedara casi inutilizable todo.

**Comment by Ramdonx** [comment]
Para la tecla 1 obtengo:
KeyPress event, serial 33, synthetic NO, window 0x1c00001,
    root 0x1dc, subw 0x0, time 141088, (192,112), root:(1173,644),
    state 0x10, keycode 87 (keysym 0xffb1, KP_1), same_screen YES,
    XLookupString gives 1 bytes: (31) "1"
    XmbLookupString gives 1 bytes: (31) "1"
    XFilterEvent returns: False
