### ISSUE TITLE
Bspwm doesn't work 

### ISSUE THREAD

**Issue by N-Nm** [gh0stzk/dotfiles#317]
I start bspwm with sudo startx. Then black screen, but keybildings don't work

**Comment by gh0stzk** [comment]
You need to provide more info. post your .xinitrc file or try a login manager.

**Comment by N-Nm** [comment]
`#!/bin/sh
   2   │ 
   3   │ userresources=$HOME/.Xresources
   4   │ usermodmap=$HOME/.Xmodmap
   5   │ sysresources=/etc/X11/xinit/.Xresources
   6   │ sysmodmap=/etc/X11/xinit/.Xmodmap
   7   │ 
   8   │ # merge in defaults and keymaps
   9   │ 
  10   │ if [ -f $sysresources ]; then
  11   │ 
  12   │ 
  13   │ 
  14   │ 
  15   │ 
  16   │ 
  17   │ 
  18   │     xrdb -merge $sysresources
  19   │ 
  20   │ fi
  21   │ 
  22   │ if [ -f $sysmodmap ]; then
  23   │     xmodmap $sysmodmap
  24   │ fi
  25   │ 
  26   │ if [ -f "$userresources" ]; then
  27   │ 
  28   │ 
  29   │ 
  30   │ 
  31   │ 
  32   │ 
  33   │ 
  34   │     xrdb -merge "$userresources"
  35   │ 
  36   │ fi
  37   │ 
  38   │ if [ -f "$usermodmap" ]; then
  39   │     xmodmap "$usermodmap"
  40   │ fi
  41   │ 
  42   │ # start some nice programs
  43   │ 
  44   │ if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  45   │  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  46   │   [ -x "$f" ] && . "$f"
  47   │  done
  48   │  unset f
  49   │ fi
  50   │ 
  51   │ twm &
  52   │ #xclock -geometry 50x50-1+1 &
  53   │ #xterm -geometry 80x50+494+51 &
  54   │ #xterm -geometry 80x20+494-0 &
  55   │ #exec xterm -geometry 80x66+0+0 -name login
  56   │ exec dwm   `

**Comment by N-Nm** [comment]
#!/bin/sh
   2   │ 
   3   │ userresources=$HOME/.Xresources
   4   │ usermodmap=$HOME/.Xmodmap
   5   │ sysresources=/etc/X11/xinit/.Xresources
   6   │ sysmodmap=/etc/X11/xinit/.Xmodmap
   7   │ 
   8   │ # merge in defaults and keymaps
   9   │ 
  10   │ if [ -f $sysresources ]; then
  11   │ 
  12   │ 
  13   │ 
  14   │ 
  15   │ 
  16   │ 
  17   │ 
  18   │     xrdb -merge $sysresources
  19   │ 
  20   │ fi
  21   │ 
  22   │ if [ -f $sysmodmap ]; then
  23   │     xmodmap $sysmodmap
  24   │ fi
  25   │ 
  26   │ if [ -f "$userresources" ]; then
  27   │ 
  28   │ 
  29   │ 
  30   │ 
  31   │ 
  32   │ 
  33   │ 
  34   │     xrdb -merge "$userresources"
  35   │ 
  36   │ fi
  37   │ 
  38   │ if [ -f "$usermodmap" ]; then
  39   │     xmodmap "$usermodmap"
  40   │ fi
  41   │ 
  42   │ # start some nice programs
  43   │ 
  44   │ if [ -d /etc/X11/xinit/xinitrc.d ] ; then
  45   │  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  46   │   [ -x "$f" ] && . "$f"
  47   │  done
  48   │  unset f
  49   │ fi
  50   │ 
  51   │ twm &
  52   │ #xclock -geometry 50x50-1+1 &
  53   │ #xterm -geometry 80x50+494+51 &
  54   │ #xterm -geometry 80x20+494-0 &
  55   │ #exec xterm -geometry 80x66+0+0 -name login
  56   │ exec dwm

**Comment by gh0stzk** [comment]
Yep your xinitrc is wrong, you are starting twm which is the xorg wm before bspwm. try a login manager 
`sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings`

then activate the loginmanager

`sudo systemctl enable lightdm.service`

the reboot, after reboot in the login manager just select bspwm as session and you are done.

if you dont want a login manager and you prefer your xinitrc, you just need to fix it. Mine is simple jsut few lines for my bspwm session.

```sh
#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
   [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec bspwm
```

**Comment by N-Nm** [comment]
Sorry but it still doesn't work, black screen and no keybildings. I will with login manager.
Btw my monitor 1920 x 1080, maybe it problem

**Comment by N-Nm** [comment]
Sorry but it still doesn't work, black screen and no keybildings. I will with login manager.
Btw my monitor 1920 x 1080, maybe it problem

**Comment by gh0stzk** [comment]
Try login manager. if still dont work maybe something goes wrong with riceinstaller. no the resolution is not the problem.

**Comment by vmxt** [comment]
> I start bspwm with sudo startx. Then black screen, but keybildings don't work

@N-Nm , I'm assuming you installed a clean bspwm de in arch, resulting in a black screen and no keybindings.

You can press `Alt + F3`1 to access the terminal, then login and follow the [installation](https://github.com/gh0stzk/dotfiles?tab=readme-ov-file#-installation) and after the installation you can reboot
