### ISSUE TITLE
How to change rices names.

### ISSUE THREAD

**Issue by joelwoel** [gh0stzk/dotfiles#32]
hi, i forked this and want to customize it my way. im a noob and not a developer or anything but the scripts are really readable so i think i can manage it. what i need help with is a few things:
1. removing a few programs from the list that it installs like termite and mpd
2. removing the terminal switcher. since i will only install alacritty, i dont need the thing that lets me change terminals.
3. renaming the themes
which files do i have to go through to do this. any help will be appreciated

**Comment by gh0stzk** [comment]
Ok!

- To remove mpd and termite. First remove mpd, mpc, ncmpcpp and termite from riceinstaller, line 57.
Then you need to remove the mpd module from all the rices in polybar, in the modules.ini file of all the rices.
- To remove the switcher terminal and leave just alacritty.
Same in all the rices in the modules.ini file look for the code "Term --**"
for example in Emilia Rice, in ~/.config/bspwm/rices/emilia/polybar/modules.ini line 163 and 164 change it for
```
alacritty --hold -t updating -e yay -Syyuu --devel
alacritty --hold -t updating -e checkupdates
```
The idea is to remove Term --** by the corresponding alacritty command.

Important you should also remove Term --** by the corresponding code in the file ~/.config/bspwm/sxhkdrc

And of course in the rices with eww as "z0mbi3, karla"
also remove Term --** for the corresponding code to launch alacritty.

You can see what is the corresponding command for alacritty in the file ~/.config/bspwm/scripts/Term
Once you did all, you can remove from that dir scripts the files, Term and TermSelector.rasi.
- To change the rice names, first raname the dirs in ~/.config/bspwm/rices/.
Then edit in ~/.config/bspwm/scripts/RiceSelector change all the names for the new ones. The same work in file LaunchWorld, stating in line 55, change the names. Finally "i guess" in file HideBar change the names too.

Possibly i forgot something.

**Comment by joelwoel** [comment]
I didn't expect such a well written response. It explains everything. Thank you for this. I hope you have an amazing day. 
Also i just want to say that these rices are really amazing and in a way helped me stick with linux because i didn't know how to customize and it looked ugly so i wanted to switch back to windows so thank you for that too

**Comment by gh0stzk** [comment]
Its important to leave the **-t updating** in the command alacritty --hold -t updating -e yay -Syyuu --devel if you wanna have the open rules, but you can modify it in ExternalRules files. because for sure you have another resolution, mine is 1600x900

No problem im glad you liked my themes. I will rename the issue title, for the future other people can do this.
