### ISSUE TITLE
Steps to fix paru error

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#320]
So if you're getting this error:

![image](https://github.com/user-attachments/assets/4294ed6e-c773-45e9-ad7e-1412c9bfaa7c)

it's happening because pacman 7.0.0 broke paru. You can run these commands to fix the error:

```bash
git clone --depth 1 https://aur.archlinux.org/paru-git
cd paru-git
makepkg -si
sudo cp /usr/lib/libalpm.so.15 /usr/lib/libalpm.so.14
```

**Comment by gh0stzk** [comment]
paru and paru-bin was updated today in aur, so this no longer needed, but will keep the issue locked some more days.

paru-bin is used in the dotfiles.
