### ISSUE TITLE
Problemas con al actualizacion de tdrop-git

### ISSUE THREAD

**Issue by jalejotorresm** [gh0stzk/dotfiles#321]
Hola! espero que estes bien. Queria confirmar algo contigo, ya que veo que en los dotfiles se hace menion de la instalacion y uso de tdrop.

Hace unos minutos hice mi rutina de actualiacion a traves de la herramienta topgrade y me arrojo una situacion inusual: en la actualizacion del sistema, yay intento actualizar tdrop a la version tdrop-last-commit.

Pero debido a problemas con la descarga del repositorio, no se puede realizar la "actualizacion" (de donde tomo yay la idea de actualizar un repo que no se toca hace dos años? ni idea)

Queria preguntarte si en el proceso de creacion de los dotfiles, se tenia en mente usar el paquete tdrop-git del AUR o solo el paquete tdrop sencillo? Es para saber si hago una transicion limpia de tdrop-git a tdrop y asi poder seguir mi vida sin el tema de "actualizaciones" pendientes.

**Comment by gh0stzk** [comment]
Hola, si mi instalador busca tdrop-git la cual actualiza al ultimo commit, justo hace unos dias me salto la actualizacion, pero no tuve problemas al actualizar, viendo tu issue, busque el pkgbuild de tdrop-git del aur y parece que no hubo cambios, la reinstale incluso por algun error pero no me dio ningun problema. tdrop-git siempre actualiza busca o instala el ultimo commit del repositorio. Si estas teniendo problemas habra que ver si tienes otros repositorios agregados como chaotic-aur o alguno de esos. pero en si, no debes tener problemas, aunque el paquete aur muestre que no se ha actualizado en mucho tiempo, igual te instala el ultimo commit.

![Shot-2024-09-26-080547](https://github.com/user-attachments/assets/03e86ed9-0f39-4e61-8f4f-b76f118c0ac9)

**Comment by gh0stzk** [comment]
Los paquetes *-git generalmente actualizan a el ultimo commit, si vez que no se actualiza desde el 2022 es el pkgbuild del aur que no se ha necesitado actualizar desde ese año, pero siempre te instalara la ultima version.

**Comment by jalejotorresm** [comment]
Entiendo. Creo que el problema esta en el commit que Arch intentaba descargar (0.5.0.r17.ge7d0cc9-1) ya que comparandolo con el tuyo, este ya no estaba al momento de siquiera descargar el commit. De todos modos, en mi caso funciono el cambio de tdrop-git a tdrop (empezando que esta en version 0.5.1). Gracias por la aclaracion!

**Comment by gh0stzk** [comment]
Excelente, aunque si tuviste ese problema, tal vez solucionarlo borrando el cache o los temporales de paru ~/.cache/paru/ lo solucione.
