### ISSUE TITLE
Picom 12 with animations already released!

### ISSUE THREAD

**Issue by gh0stzk** [gh0stzk/dotfiles#322]
Hello, yshui already release the picom v12 https://github.com/yshui/picom/releases/tag/v12, that comes with animations and another system rules, in arch is now in Extra-testing and possibly they will move to Extra in 3-5-7 days, meanwhile i already start working with the new configuation, if u already have an awesome config, or a link, pls share, these days i not have much time and a little help will be nice. The main idea is keeping all as how is now but integrating the new rules for animation.

If u wanna test or start with the new conf and then share here/or not, 🥹  follow these steps:

Unistall your actual picom, `sudo pacman -Rns picom`
clone the yshui repo: `git clone https://github.com/yshui/picom.git`
`cd picom`
`meson setup --buildtype=release build`
of course if that gives to you errors, install neede deps, meson, libev, uthash etc..
`ninja -C build`
`
ninja -C build install`

**or just do a** `paru -S picom-git`
From here u already have the picom 12 but need to reboot, in my case i need to reboot.

**Important**
There are many deprecated/new options, you need to copy the new conf file from https://github.com/yshui/picom/blob/next/picom.sample.conf .

Copy it and make a copy of the current one, ~/.config/bspwm/picom.conf  remember my config is in bspwm dir. now copy the new picom.conf file to ~/.config/bspwm/ 

and you are done, now you can play with the new conf.
The user @prateekshukla1108 send a pr some weeks ago, you can start with his config as an example, https://github.com/prateekshukla1108/dotfiles/blob/master/config/bspwm/picom.conf
Thre are sections than no longer works like wintype: section etc.

**Comment by gh0stzk** [comment]
Ohh i forgot, for now, if you install the new picom and leave my conf as is now, it works, the rounded corners, the opacity or transparency in certain windows, but shadows and the fade effect is gone.

**Comment by prateekshukla1108** [comment]
It would be exceptionally better if you add chaotic aur in you RiceInstaller and install eww clipboard, some fonts, paru and picom-git from it
that will help you to significantly reduce the installation time of the dotfiles because you are skipping the build process entirely
