### ISSUE TITLE
Cannot sync remote repo mirror

### ISSUE THREAD

**Issue by CuB3y0nd** [gh0stzk/dotfiles#324]
Hi, i might got some proxy problem im not sure. I can open `http://gh0stzk.github.io/pkgs/x86_64/gh0stzk-dotfiles.db` in browser, but cant use `pacman` or `yay` to download. I tired use proxy but its not help.

Note: Other terminal apps and local proxy works fine for me, and i can use `wget` or `curl` to download the file from `gh0stzk.github.io`

```plain-text
λ ~/ sudo pacman -Syy
:: Synchronizing package databases...
 core                           117.7 KiB   499 KiB/s 00:00 [################################] 100%
 extra                            7.5 MiB  7.94 MiB/s 00:01 [################################] 100%
 multilib                       133.6 KiB  1590 KiB/s 00:00 [################################] 100%
 gh0stzk-dotfiles.db failed to download
error: failed retrieving file 'gh0stzk-dotfiles.db' from gh0stzk.github.io : Recv failure: Connection reset by peer
error: failed to synchronize all databases (download library error)
```

I also tired use `curl` or `wget` instead of pacman's default settings in `/etc/pacman.conf`, but not help. They return following errors:

```plain-text
# XferCommand = /usr/bin/curl -L -C - -f -o %o %u
# XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
```

```plain-text
curl: (22) The requested URL returned error: 404
curl: (56) Recv failure: Connection reset by peer
``` 

```plain-text
--2024-09-28 17:39:18--  (try: 2)  http://gh0stzk.github.io/pkgs/x86_64/gh0stzk-dotfiles.db
Connecting to gh0stzk.github.io (gh0stzk.github.io)|2606:50c0:8000::153|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
```

**Comment by gh0stzk** [comment]
Yep possible is your proxy, i just checked on my desktop and 2 laptops and sync is fine.

![Shot-2024-09-28-091942](https://github.com/user-attachments/assets/8beca712-379d-4242-9657-489392d3d6b8)

**Comment by CuB3y0nd** [comment]
Fixed by using curl.

**Comment by Sandesh2007** [comment]
I am getting 404 error from pacman 

sudo pacman -Syy
:: Synchronizing package databases...
 endeavouros            14.2 KiB  5.02 KiB/s 00:03 [---------------] 100%
 edz-linux-repo       1005.0   B   402   B/s 00:03 [---------------] 100%
 gh0stzk-dotfiles.db failed to download
 core                  116.8 KiB   146 KiB/s 00:01 [---------------] 100%
 extra                   7.5 MiB   760 KiB/s 00:10 [---------------] 100%
error: failed retrieving file 'gh0stzk-dotfiles.db' from gh0stzk.github.io : The requested URL returned error: 404
error: failed to synchronize all databases (unexpected error)

**Comment by CuB3y0nd** [comment]
> I am getting 404 error from pacman
> 
> sudo pacman -Syy :: Synchronizing package databases... endeavouros 14.2 KiB 5.02 KiB/s 00:03 [---------------] 100% edz-linux-repo 1005.0 B 402 B/s 00:03 [---------------] 100% gh0stzk-dotfiles.db failed to download core 116.8 KiB 146 KiB/s 00:01 [---------------] 100% extra 7.5 MiB 760 KiB/s 00:10 [---------------] 100% error: failed retrieving file 'gh0stzk-dotfiles.db' from gh0stzk.github.io : The requested URL returned error: 404 error: failed to synchronize all databases (unexpected error)

Can u share your `/etc/pacman.conf`. Please make sure your mirror address configuration is correct and you can visit `http://gh0stzk.github.io/pkgs/x86_64/gh0stzk-dotfiles.db` in your browser.

Here is a correct mirror configuration:

```
[gh0stzk-dotfiles]
SigLevel = Optional TrustAll
Server = http://gh0stzk.github.io/pkgs/x86_64
```

Then try use `sudo pacman -Syyu` again.

If you're using proxy, make sure your proxy is working well first. Then you can try uncomment curl's `XferCommand` in `/etc/pacman.conf` to let `curl` instead default downloader. Don't forget set proxy arguments:

```
XferCommand = /usr/bin/curl -L -C - -f -o %o %u -x "http://127.0.0.1:2080"
```

By the way, you should try `http` proxy not `socks` proxy address if you're using proxy.

**Comment by Sandesh2007** [comment]
Thank you for your help :)

### I have a another question 

i have some custom builds of some packages and i want to make a repo 
can you help or guide how do  i create one ??
it would be great of you :)

**Comment by CuB3y0nd** [comment]
> Thank you for your help :)
> ### I have a another question
> 
> i have some custom builds of some packages and i want to make a repo can you help or guide how do i create one ?? it would be great of you :)

Just upload your custom packages to a public repo and use `github pages` function to make a public site mirror let people can visit and download your packages. Or you can try to deploy a ftp server to implement the same function.

**Comment by Sandesh2007** [comment]
**Thank you for helping again :)**

**Comment by ferkaua** [comment]
I have the same problem, during installation the Script downloads all the necessary files and dependencies, but when it reaches the repository it all fails.

**Comment by Sandesh2007** [comment]
Add this to your /etc/pacman.conf 

`
[gh0stzk-dotfiles]
SigLevel = Optional TrustAll
Server = http://gh0stzk.github.io/pkgs/x86_64
`

**Comment by ferkaua** [comment]
> Add this to your /etc/pacman.conf
> 
> `[gh0stzk-dotfiles] SigLevel = Optional TrustAll Server = http://gh0stzk.github.io/pkgs/x86_64`

It's already added, I removed it and added it again and the same error remains, I've already done the procedures indicated here but it didn't solve it.

**Comment by CuB3y0nd** [comment]
> > Add this to your /etc/pacman.conf
> > `[gh0stzk-dotfiles] SigLevel = Optional TrustAll Server = http://gh0stzk.github.io/pkgs/x86_64`
> 
> It's already added, I removed it and added it again and the same error remains, I've already done the procedures indicated here but it didn't solve it.

have you tried using curl instead pacman's default downloader

**Comment by gh0stzk** [comment]
Whats the output from `sudo pacman -Syy` ?

**Comment by gh0stzk** [comment]
i just tried to download a package from repo http://gh0stzk.github.io/pkgs/x86_64/gh0stzk-gtk-themes-1.0-1-any.pkg.tar.zst and downloads fine...

**Comment by ferkaua** [comment]
> Qual é a saída de `sudo pacman -Syy`?

Connecting to gh0stzk.github.io (gh0stzk.github.io) and then it says that the network is out of range. I reinstalled the system and started the Script again, but in the repository it still doesn't download.

**Comment by ferkaua** [comment]
> > > Adicione isso ao seu /etc/pacman.conf
> > > `[gh0stzk-dotfiles] SigLevel = Optional TrustAll Server = http://gh0stzk.github.io/pkgs/x86_64`
> > 
> > 
> > Já foi adicionado, removi e adicionei novamente e continua o mesmo erro, já fiz os procedimentos indicados aqui mas não resolveu.
> 
> você já tentou usar `curl`o downloader padrão do pacman

Yes, but the error continues, I'm doing some tests to see if I can find out.

**Comment by CuB3y0nd** [comment]
> > Qual é a saída de `sudo pacman -Syy`?
> 
> Connecting to gh0stzk.github.io (gh0stzk.github.io) and then it says that the network is out of range. I reinstalled the system and started the Script again, but in the repository it still doesn't download.

its your network problem, please check your network/dns configuration. if your network configuration is correct, then maybe you should try to use proxy
