### ISSUE TITLE
Ranger Editor 

### ISSUE THREAD

**Issue by LuiBi10** [gh0stzk/dotfiles#327]
Hola espero te encuentres muy bien. He tomado como referencia tus dotfiles y hasta ahora me han servido mucho siguiendo las instrucciones que comentas. Solo tengo una duda, cuando yo abro ranger desde el shortcut (no abrir terminal y luego ejecutar ranger), el editor de texto que tengo por defecto cambia de neovim a nano. Esto solo pasa cuano lo abro desde el shortcut que asigne en bspwm.  Podrias indicarme por favor, a que se debe y como lo puedo solucionar. Se que a ti te paso y en una actualizacion lo acomodaste, pero no tengo claro como? Muchas gracias, has hecho un trabajo genial.

**Comment by gh0stzk** [comment]
Ok y el  editor que que quieres por defecto cuando lo abres shortcut debe de ser neovim no?
Otra pregunta, tienes exportada o definida la variable EDITOR="" en alguna parte? si usas mis dots deberia estar exportada en .zshrc y cual es el valor de esta?

**Comment by gh0stzk** [comment]
Bueno, independientemente, resulta que si abres ranger por medio de abriendo la terminal y escribiendo ranger ó ejecutando ranger desde una aplicacion launcher como rofi, abrira tu documento con la variable global que se definio en EDITOR="".

Pero si la abres mediante shortcut por alguna razon no le importa esa variable y abre el documento con la aplicacion que tienes definida como predetermina en mimeapps.list

Una manera de corregir esto, en mi caso uso thunar, dale boton derecho sobre el archivo y dale abrir con, despues dale configurar aplicacion predeterminada, deberia ahi estar seleccionada por defecto nano, en algun momento abriste ese tipo de archivo con nano, y por eso quedo por defecto, solo elige neovim y listo. si te sale un error que no encontro la terminal, es por que thunar busca la terminal de xfce, pero cierra la ventana de todos modos los cambios ya fueron hechos.

Si no supongo los demas filemanagers deben tener una opcion similar.

Por que no respeta la variable global si lo abres por shortcut? No lo se.. debe de tener una explicacion y debe ser algo muy sencillo, pero la desconozco.

**Comment by gh0stzk** [comment]
Posiblemente mimeapps.list tenga mas gerarquia que la variable EDITOR.

**Comment by LuiBi10** [comment]
Hola amigo. La verdad si me he guiado a partir de tus dotfiles, sin embargo tambien le he dado mi toque personal adaptando algunas cosas a mi gusto. Para el caso que te comentaba, he revisado cuidadosamente, y en zshrc el editor que tengo por defecto es nvim. Y funciona a la perfeccion mientras no uso el shortcut. Recuerdo que hace un tiempo tu corregiste un problema similar cuando ranger se habria por el shortcut. Para ese caso, modificaste el mimeapps.list? He seguido tu recomendacion de abrir como y establecer la app por defecto pero sigue molestando y abriendo con nano. 

Muchas gracias por tu ayuda!  Saludos

**Comment by gh0stzk** [comment]
Si hace tiempo se toco el tema, y funcionaba.. pero en realidad hoy al leer tu issue, lo he intentado abriendo por shortcut y por rofi y terminal, y me pasaba exactamente lo que a ti, lo solucione haciendo lo que te comente arriba y se corrigio. 

Pero fijate en ~/.local/share/applications, si tienes  los archivos .deskopt de ranger eliminalo, de hecho hace como 3 commits lo elimine de los dotfiles, y cual es el shortcut en sxhkdrc? ponlo aqui.

**Comment by gh0stzk** [comment]
Y en /usr/share/doc/config/ esta el archivo scope.sh copialo y pegalo en tu directorio ~/.config/ranger checa que tenga permiso de ejecusion. salte de tu sesion y vuelve a entrar y mira si se soluciona tu problema. El scope.sh de mis dots es diferente al default.

**Comment by LuiBi10** [comment]
El shortcut lo tengo asignado de esta manera:

ctrl + alt + {v,r,h}
	alacritty --config-file ~/.config/bspwm/alacritty/alacritty.toml -e {nvim,ranger,htop}

Un amigo de aqui de la comunidad tenia el mismo problema y lo soluciono moviendo el scope.sh como tu sugeriste.  Yo modifique el mimeapps y pude solucionar el problema aunque fue un poquito tedioso jajaja.

Muchas gracias por tu ayuda. Tus dots son la base principal para personalizar mi sistema. 
Saludos
