### ISSUE TITLE
How can i change the resolution (or display thing)? + network question

### ISSUE THREAD

**Issue by Maty1ek** [gh0stzk/dotfiles#329]
Hey, how can I change resolution configurations? I installed the dotfiles and now every app is too small for my monitor, cuz resolution is different, i guess. So how can I change it?

Also another question: when i press wi-fi button, choose a connection and press enter, i see a notification "networkName activated" but nothing changes and i can't connect with wi-fi. And every time i have to launch connection manager, activate a connection, write the password, and do it every time when i turn on my laptop. How can I fix it?

**Comment by gh0stzk** [comment]
you can change your resolution with xrandr or with a gui with arandr `sudo pacman -S arandr`

**Comment by gh0stzk** [comment]
about your connection, next time you turn off your computer, open a terminal and execute `nmtui` connect to your wifi and thats must save your pass

**Comment by Maty1ek** [comment]
well, i changed my resolution but turned out i didn't need it... But, the problem is, that everything in every app is too small, i mean, ithe resolution of every app and web-site is too small (if i can say so), and i always need to zoom it. Can I fix it?

**Comment by gh0stzk** [comment]
You probably need to change your DPI `xrandr --dpi 96`

**Comment by gh0stzk** [comment]
adjust dpi to your needs but probably when your reboot you will need to apply again so in ~/.config/bspwm/bspwmrc add to the bottom of file the comand xrandr --dpi 96

**Comment by gh0stzk** [comment]
to known whats your ideal dpi run this command `xdpyinfo | grep dots` in my case is 96

**Comment by Maty1ek** [comment]
> You probably need to change your DPI `xrandr --dpi 96`

nope, nothing changed...

xrandr --output "LVDS-1" --scale 1x1  

i tried this, but it just made everything bigger and messed everything..

the problem is, that every app's scale is not as i need

**Comment by gh0stzk** [comment]
if the problem are the gtk applications, use export GDK_SCALE=2  i dont know whats your setup, but you could add in ~/.zshrc that line `export GDK_SCALE=2` at the top where other exports are. and test, probably you need to log out and enter again to bspw,

before that step open a terminal and paste export GDK_SCALE=2 to test but i dont know if the changes take effect without logout

**Comment by spacewonderers** [comment]
Simple way

xrandr --output eDP-1 --primary --mode 2048x1152 --output HDMI-2 --mode 1920x1080 --above eDP-1

Just define your own resolution, "--above" command just to define which position your monitor are. mine is above.

put in bspwmrc file and reload.
