### ISSUE TITLE
on running script timeout error

### ISSUE THREAD

**Issue by shubpanda** [gh0stzk/dotfiles#33]
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 129247 ms: Couldn't connect to server

pls solve this issue

**Comment by gh0stzk** [comment]
![15-febrero-23-003827](https://user-images.githubusercontent.com/67278339/218951698-fac7f507-3625-4a0e-be3e-e09d4d679b31.png)

Im trying to download and everything looks fine.

**Comment by shubpanda** [comment]
![Screenshot_2023-02-15_14-56-22](https://user-images.githubusercontent.com/125433545/218987708-68ab35c5-6c74-42b3-a80a-803f2efbd227.png)

**Comment by shubpanda** [comment]
can u help me my frnd
