### ISSUE TITLE
[BUG] EWW right click menu - Widgets & BSPWM F1 Keybinds

### ISSUE THREAD

**Issue by CipherCryptic** [gh0stzk/dotfiles#331]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

After a recent update to Arch via the updater , the above options no longer work 
Do you have any recomendations on where to look?

### Reproducing the issue

Install ARCH, install DOT files then Syyu. The above then no longer work
OpenApps --KeyHelp >> WARN  eww > Failed to connect to daemon: Failed to connect to daemon

### System information

EndevourOS

**Comment by gh0stzk** [comment]
Could you pls install eww-git and give me feedback if that eww works? im confused, i updated the eww binary 2 days ago, and in some of my pcs works and not in others..

**Comment by gh0stzk** [comment]
paru -S eww-git

**Comment by CipherCryptic** [comment]
Tried  to install it , got the following error: error: failed to commit transaction (conflicting files)
eww-git: /usr/bin/eww exists in filesystem
Errors occurred, no packages were upgraded.

With root access , i deleted the file then tried  paru again ,, this time  worked but this has not restored F1 key binding menu. Also the Widgets >usercard  wont do anything. Ill keep digging

**Comment by CipherCryptic** [comment]
OK i figured it out i think.
I tried to reinstall eww from AUR using Yay.. thought ill give it a try,  it installed but that did not fix above issue.
When trying : `eww -c "${HOME}"/.config/bspwm/eww daemon,` it would complain  with >>
`error_handling_ctx > second time provided was later than self`
the event tries to save to a log file in /home/user/.cache/eww/ however the file is empty
I deleted the log file and then re-tried to issue the eww command above. It worked and now F1 works and right click Widgets>User card/Calendar or Music Player all pop up as intended.
A corrupted log file can cause so much problem ??

**Comment by CipherCryptic** [comment]
cheatsheet.yuck >>
`
;; Window cheatsheet ;;
(defwindow csheet
    :geometry (geometry :x "0%"
                        :y "0%"
                        :width "90%"
                        :anchor "center")`

I added width parameter 

regards

**Comment by gh0stzk** [comment]
Yes i had to recompile in the other laptops eww and it works. I need to investigate why the precompiled binary isnt working, its easy if you only download the binary from my repo and move it to PATH, as my installer did but now new people installing my dots will need to compile it, I will close the issue now :)

**Comment by depocoder** [comment]
On Manjaro works good

**Comment by CipherCryptic** [comment]
FYI - Happened again when a recent update had run. So seems every time a System update gets executed the `/home/user/.cache/eww/log` file gets corrupted. Deleting it restores functionality
