### ISSUE TITLE
[BUG] Font problem with CJK (HIragana in Japanese and Korean)

### ISSUE THREAD

**Issue by CesarCruzUtec** [gh0stzk/dotfiles#332]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] #333

### Description of the bug

I recently encountered an issue with displaying Japanese and Korean characters in my terminal. After downloading some music files with Japanese characters in their filenames, I noticed that:

- Katakana and Kanji characters display correctly.
- Hiragana characters and Korean alphabet (Hangul) are not displayed.

I have not installed any additional fonts on my system, aside from those set in my dotfiles. I am using the default themes for both Alacritty and Kitty. After some research, I suspect the issue might be related to the JetBrains NerdFont, as it doesn't explicitly mention support for Japanese or Korean characters on its official page. However, it does seem to display some Japanese characters (like Katakana and Kanji), which adds to the confusion.

### Reproducing the issue

1. Use JetBrains NerdFont as the terminal font in either Alacritty or Kitty.
2. Display text containing a mix of Japanese characters (Katakana, Kanji, and Hiragana) and Korean alphabet. [hiragana](https://en.wikipedia.org/wiki/Hiragana#Writing_system) [katakana](https://en.wikipedia.org/wiki/Katakana#Writing_system) [kanji](https://en.wikipedia.org/wiki/List_of_j%C5%8Dy%C5%8D_kanji#List_of_characters) [korean](https://en.wikipedia.org/wiki/Hangul_Syllables#Block)
3. Notice that only Katakana and Kanji characters display, while Hiragana and Korean characters do not.

![image](https://github.com/user-attachments/assets/c10ec989-65ea-46c0-b75c-bbf4495fd5c7)

### Expected behaviour

All Japanese characters (Kanji, Katakana, Hiragana) and Korean characters (Hangul) should be displayed correctly.

### System information

- OS: Arch Linux (almost clean installation with dotfiles)
- Terminal Emulators: Alacritty, Kitty
- Font: JetBrains NerdFont (default font used in terminal themes)

**Comment by gh0stzk** [comment]
I'm pretty sure it's the lack of support for the characters you mention in the jetbrainsmono nerd font. You can check this by installing the font-manager package `sudo pacman -S font-manager` and searching the jetbrainsmono nerd font for the available characters. 

Searching the nerdfonts page https://www.nerdfonts.com/font-downloadsenand find this: **D2CodingLigature NerdFont** apparently supports korean.

you need to download and put in ~/.local/share/fonts then modify ~/.config/alacritty/fonts.toml to make it your default font.

Additionally you can install the package noto-fonts-cjk `sudo pacman -S noto-fonts-cjk` for global support in your system.

And yes, it is a problem with the font and its lack of support for the characters you need, I can't do much in that case.

Even if the jetbrains nerd font had support and it still doesn't show up in alacritty or kitty, it would also be a terminal problem, maybe you could check it by installing another terminal like tilix, or something else, and set the font to jetbrainsmono nerd font , and see if it shows the characters or not.
