### ISSUE TITLE
How can i change ASCII art in terminal?

### ISSUE THREAD

**Issue by SStov** [gh0stzk/dotfiles#334]
I don't want to delete it completely, just change to my own. Or maybe do it an image, not ASCII art. I am pretty new in arch, so i would appreciate any advice. Thanks.

**Comment by SStov** [comment]
Many thanks! Also wanted to ask, why does powermenu don't change after changing themes? i would assume it is because i use 1080p monitor. 
![Shot-2024-10-16-004804](https://github.com/user-attachments/assets/d2637b81-88ca-4a5e-a9d8-df223431f8a6)

Thank you again!

**Comment by gh0stzk** [comment]
Change in size or colors?

**Comment by SStov** [comment]
Colors, form, because in themes preview it looks different than what i get after switching themes

**Comment by gh0stzk** [comment]
The size of the powermenu is set in % you can change it in ~/.config/bspwm/src/rofi-themes/PowerMenu.rasi  on line 16

About the colors.. is strange... i just install the dots in one of my laptops to test and i dont have that problem, did you change something in Theme.sh or something??

**Comment by SStov** [comment]
Yes, i found it. Just added border-rounding in ro-fi menus, it just confused me because on screens of themes you had rounding, neither me. Thank you a lot!  I also wanted to ask if it is possible to add current keyboard language identifier on topbar?

**Comment by gh0stzk** [comment]
Yes its on my to-do list add that module and other in polybar.

**Comment by SStov** [comment]
Thanks for your help! I am really enjoying your themes. Will be looking forward to getting next updates!
