### ISSUE TITLE
How can i hide empty workspaces?? 

### ISSUE THREAD

**Issue by MeOwlei** [gh0stzk/dotfiles#335]
![Shot-2024-10-17-013154](https://github.com/user-attachments/assets/38ab6706-237a-45e3-9ec6-5bfb5fc7236d)
it looks like so much is going on . i just want hide them unless something is on them

**Comment by gh0stzk** [comment]
Yes, is cristina rice so, open ~/.config/bspwm/rices/cristina/modules.ini sear for bspwm module and search for this code:

```ini
label-empty = %icon%
label-empty-foreground = ${color.fg}
label-empty-padding = 1
```

replace with this:

```ini
label-empty = 
label-empty-foreground = ${color.fg}
label-empty-padding = 
```

**Comment by MeOwlei** [comment]
Thank you 
can also tell how can i change ♟ to workspace number?

**Comment by gh0stzk** [comment]
Yes in that module too, you have this code:

```ini
ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-default = "♟ "
```

Add the number of workspaces you have:

```ini
ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;icon you want
ws-icon-7 = 8;icon 
ws-icon-8 = 9;icon
ws-icon-default = "♟ "
```

that icons are font awesome font, you can get it from https://fontawesome.com/
