### ISSUE TITLE
RiceEditor and picom animations app missing

### ISSUE THREAD

**Issue by a-iken** [gh0stzk/dotfiles#337]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

The RiceEditor command doesn't exist and the RiceEditor app is missing, the gh0stzk-dotfiles are up to date.

### System information

I'm on arch with picom v12.3

**Comment by gh0stzk** [comment]
Open your filemanager and navigate to ~/.config/bspwm/src/ confirm that there is a RiceEditor file.

gh0stzk-dotfiles is the repo that contains the packages for gtk and icon themes. But it has nothing to do with dotfiles, you may have an outdated version of my dotfiles.

To update, you can download RiceInstaller again 

`curl https://raw.githubusercontent.com/gh0stzk/dotfiles/master/RiceInstaller -o $HOME/RiceInstaller` 
and run the file again, don't forget to give it execution permissions.

This will create a copy of your current configuration in case you have already made modifications and will put the new and updated dotfiles, but you will have to make your modifications again if you have already made some.

**Comment by a-iken** [comment]
Many thanks, that worked!
