### ISSUE TITLE
[BUG] MusicPlayer title not changed

### ISSUE THREAD

**Issue by Luiso9** [gh0stzk/dotfiles#338]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

Sorry, it might be dumb question, but i couldnt get the music player to get to work. Im playing some music both from local and spotify and its showing properly in polybar, like the title and artist. But when i check the MusicPlayer it doesnt show anything, the title and album. Sorry for my bad English. Thankyou.

![image](https://github.com/user-attachments/assets/8d44be89-0987-4745-8778-57aa6990d026)

### System information

Im installing this Rice after fresh installation of Endeavour OS. So i think i might missing something.

**Comment by gh0stzk** [comment]
Ok whats your native language?? if u speaks spanish, write in spanish.

About the problem, could you open the log, is in ~/.cache/eww/ and/or if you have a .xsession-error file in your home. and paste here.

Be sure MediaPlayer file in ~/.config/bspwm/src/ have execute permissions.

**Comment by Luiso9** [comment]
Its fine, i can still understand english... i tried to open log in ~/.cache/eww/ but when i open the .log file its just empty, and i cant find .xsession-error. And yes MediaPlayer does have execute permissions.

**Comment by Luiso9** [comment]
I checked the MediaPlayer file and it should cache the last song i played on tmp/, i checked the txt file and nothing popup, only blank file.

**Comment by gh0stzk** [comment]
could you confirm that playerctl and mpc are installed? My script installs it but maybe something fail.
`
pacman -Qq playerctl mpc`

**Comment by Luiso9** [comment]
is there any configuration should i do? tried to `playerctl status`, and said `no players found`

**Comment by Luiso9** [comment]
Oh, it works for spotify music but not local, at least i get it work. Thanks anyway.

**Comment by gh0stzk** [comment]
for local you need to follow these https://github.com/gh0stzk/dotfiles/wiki/Firsts-steps-after-installing#the-album-covers-in-notifications-and-widgets
