### ISSUE TITLE
Issue in bar

### ISSUE THREAD

**Issue by encryptionspidy** [gh0stzk/dotfiles#339]
Some error occured in some json file i think which shows up in polybar near the time like 
“5:00 pm jq: parse error: Invalid numeric literal at line 2, column 0”
I didn't modified anything recently suddenly it appeared idk why i tried to solve it but i didn't find any json file in .config section 

And it wont appear in all rices only in few rices  it may be because of the design 
  But still i mention the name of rices which i got this message 
  Aline, cynthia , karla , marisol ,silvia.

Yes, ik iam a noob  . please help meee..

  
(If possible update your wiki which explains every config you made , you can make like section for a feature eg: how i can do that random pictures or shapes when opening the terminal , do it please it would be help full for people like me  )

**Comment by gh0stzk** [comment]
Probably the weather module, I assume you edited your location, what is your location? and how did you put it???

**Comment by encryptionspidy** [comment]
Yeah i edited it to my location

**Comment by encryptionspidy** [comment]
> Probably the weather module, I assume you edited your location, what is your location? and how did you put it???
> 
> yeah , its weather module. now solved  :)
   Thankyou
