### ISSUE TITLE
[BUG] Brightness polybar module does not appear in any theme

### ISSUE THREAD

**Issue by kmeaw01** [gh0stzk/dotfiles#343]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

Brightness polybar module does not appear in any theme.My system uses intel_backlight

### Reproducing the issue

default config

### Expected behaviour

polybar has brightness module

### System information

Arch Linux latest,Clean dotfiles installation

**Comment by gh0stzk** [comment]
Yes in all themes brightness  module is available but not active, if you want to show it just add it, in all themes there is a message with the disabled modules.

For example in emilia theme, in **config.ini** looks like this:
![Shot-2024-10-28-075323](https://github.com/user-attachments/assets/367d0404-28a9-479e-8ead-3ea915c7fa25)

Just add `brightness` in whatever location you want, modules-center or modules-right or modules-left

**Comment by kmeaw01** [comment]
how to fix this 
![image](https://github.com/user-attachments/assets/be88992f-8ae5-4bf7-b88b-cb85feeca426)

**Comment by gh0stzk** [comment]
oh yes that module is created to be alone like the bluetooth one, but if you want to add it inside a blubble like wifi icon you need to edit the module:

```ini
[module/brightness]
type = internal/backlight
card = ${system.sys_graphics_card}

enable-scroll = false

format = <ramp><label>
label = %percentage%%
label-padding-left = 3pt

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-font = 2
ramp-foreground = ${color.yellow}
```
Im at work in a desktop that doesnt have brightness i cant test if is fine but the module should be like this:

```ini
[module/brightness]
type = internal/backlight
card = ${system.sys_graphics_card}

enable-scroll = false

format = <ramp><label>
label = %percentage%%
label-background = ${color.mb}
label-padding-right = 3pt

ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-font = 2

ramp-foreground = ${color.yellow}
ramp-background = ${color.mb}
```

i added background to label and ramp properties.
