### ISSUE TITLE
[BUG] No system tray in andrea and z0mbi3 theme

### ISSUE THREAD

**Issue by kmeaw01** [gh0stzk/dotfiles#346]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

No system tray in andrea and z0mbi3 theme.Its using eww is suppose.

### System information

arch linux

**Comment by gh0stzk** [comment]
Ok first of all, did you already have eww installed before using my dotfiles? possibly you have old version if that is the case.

**Comment by kmeaw01** [comment]
No its is a clean arch install with your dotfiles

**Comment by gh0stzk** [comment]
Could you share your logs here?? ~/.cache/eww
