### ISSUE TITLE
How do I change keyboard layout

### ISSUE THREAD

**Issue by Gribovoy29** [gh0stzk/dotfiles#348]
Hello, 
Love the config, extremely pretty. 
The only problem that I've encountered is that I cannot figure out how to change the kb layout.
I use 4 different layouts: Polish QWERTZ, English DVORAK, Russian and Ukrainian. 
I saw a closed issue where someone was trying to add Spanish, but it didn't work for me. I tried adding more else if statements.
```
#! /bin/bash

CURRENT_LAYOUT=$(setxkbmap -query|awk -F : 'NR==3{print $2}'|sed 's/ //g')
if [ "$CURRENT_LAYOUT" = "dvorak"]; then
    setxkbmap "pl"
else if [ "$CURRENT_LAYOUT" = "pl"]; then
    setxkbmap "ru"
else if [ "$CURRENT_LAYOUT" = "dvorak"]; then
    setxkbmap "ua"
else   
    setxkbmap "dvorak"
fi
 

```
I want to set the QWERTZ as the default layout

**Comment by gh0stzk** [comment]
Hello, the syntax in bash is elif

```bash
#! /bin/bash

CURRENT_LAYOUT=$(setxkbmap -query|awk -F : 'NR==3{print $2}'|sed 's/ //g')
if [ "$CURRENT_LAYOUT" = "dvorak"]; then
    setxkbmap "pl"
elif [ "$CURRENT_LAYOUT" = "pl"]; then
    setxkbmap "ru"
elif [ "$CURRENT_LAYOUT" = "dvorak"]; then
    setxkbmap "ua"
else   
    setxkbmap "dvorak"
fi
```
 The universe always tells me what to do, I just thought these days that I needed to add an applet to change the keyboard layout. In a few days I will do it.

The menu will let you choose which layout to use and will add the module to the polybars.

**Comment by Gribovoy29** [comment]
I don't know. Didn't work for me. I think I'm gonna wait until you implement it. Thank you

Also, do you know if I can use 2 different Wallpapers on different screens?
