### ISSUE TITLE
What's wrong with my monitor config?

### ISSUE THREAD

**Issue by Gribovoy29** [gh0stzk/dotfiles#349]
Hello, 
It's me again. This time I can't seem to understand what did I do wrong in the monitor config. DP-2 is primary and DP-0 is secondary.

```
MONITOR1="DP-2"
MONITOR2="DP-0"
xrandr --output DP-2 --primary --mode 2560x1440@164.96 --rotate normal
	if [[ $(xrandr -q | grep "${MONITOR2} connected") ]]; then
		xrandr --output DP-0 --mode 1920x1200@59.95 --rotate right --right-of DP-2
		bspc monitor "$MONITOR1" -d '1' '2' '3' '4'
		bspc monitor "$MONITOR2" -d '5' '6' '7' '8'
		bspc wm -O "$MONITOR2" "$MONITOR1"
	else
		bspc monitor "$MONITOR1" -d '1' '2' '3' '4' '5' '6' '7' '8'
	fi
done
```
It works fine when I apply it in system, but when I reboot the system it just shows black screen. The only option is to run RiceInstaller to reset bspwmrc

**Comment by kmeaw01** [comment]
x11 is just bad with multimonitor configs

**Comment by gh0stzk** [comment]
Yep looks like is nothing wrong with your conf, imposible to know, check logs, journal and dmesg. I read about this on reddit some time ago, could be good if you post there in bspwm subreddit, someone for sure will have answers.

**Comment by Gribovoy29** [comment]
I've found the solution. You just have to remove the `done` in the last like of the monitor config. That makes so much sense that I feel dump for missing it.

`MONITOR1="DP-2"
MONITOR2="DP-0"
xrandr --output DP-2 --primary --mode 2560x1440@164.96 --rotate normal
	if [[ $(xrandr -q | grep "${MONITOR2} connected") ]]; then
		xrandr --output DP-0 --mode 1920x1200@59.95 --rotate right --right-of DP-2
		bspc monitor "$MONITOR1" -d '1' '2' '3' '4'
		bspc monitor "$MONITOR2" -d '5' '6' '7' '8'
		bspc wm -O "$MONITOR2" "$MONITOR1"
	else
		bspc monitor "$MONITOR1" -d '1' '2' '3' '4' '5' '6' '7' '8'
fi`
