### ISSUE TITLE
Configurations missing

### ISSUE THREAD

**Issue by Yhuot** [gh0stzk/dotfiles#350]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

[BUG] I tried using your installation file, but little to no changes were made, a few configurations got in, a few didn't, i'm still unsure what i missed here, the rice editor doesn't start, the files aren't even in the correct directory, how am i supposed to go around this? am i am faily new to linux so forgive please if i missed something important

### Reproducing the issue

i have no idea what went wrong.

### Expected behaviour

after installation, my system would look different and with your keybindings installed, and eww widgets too, unfortunately, none of that happened and the only things that look different are kitty, which no longer tells me which folder i'm on and it's slightly denting my head, and rofi, which i very much like now

### System information

Arch, hyprland, tried installing ml4w, but didn't go exactly as it should, then i tried your dotfiles

**Comment by gh0stzk** [comment]
Imposible to know without logs, there is a RiceError.log file on your home, paste here. You can clone de repo manually and move the different dirs to theirs respective location.
