### ISSUE TITLE
Battery low notification showing endlessly in z0mbi3 theme

### ISSUE THREAD

**Issue by Momen-MKadry** [gh0stzk/dotfiles#351]
Hey, I added the battery script in the z0mbi3 theme as in #197 and now when the battery hits 20% it keeps spamming the battery low notification

![image](https://github.com/user-attachments/assets/f5a923de-f9cb-46c7-aca1-5faa78064f03)

I clear the notifications and they keep showing, I looked at the script but there seems to be nothing causing the issue there.

**Comment by gh0stzk** [comment]
I'm sure it's because of the interval of seconds in which the script is executed, every second it is executed. You should change the defpoll interval from 1s to 5m for example.

**Comment by Momen-MKadry** [comment]
change it in the eww.yuck file?

![image](https://github.com/user-attachments/assets/345c7d01-8f1d-4ffc-bebf-27ad6a488b68)

Doesn't the "1s" here means the battery level in eww will update every second?

**Comment by gh0stzk** [comment]
I would do it, directly in the yuck code without using any bash script, so I take advantage of the internal eww function EWW_BATTERY.

**Comment by Momen-MKadry** [comment]
Ok I changed to 5 minutes and will wait till my laptop discharge to 20%, sth weird I noticed tho, the battery script doesn't send notifications at 20% but at 10%, why did it send the notifications at 20% then?

**Comment by Momen-MKadry** [comment]
Oh, didn't notice the indentation my bad, thanks.

I will comment any updates when my battery reaches the threshold again

**Comment by Momen-MKadry** [comment]
The notification is working correctly now and appears every 5 minutes, thanks a lot for the help

**Comment by gh0stzk** [comment]
You can add a new var in eww.yuck for example 

`(defpoll battery_notif    :interval "5m"    "scripts/battery notifications")`

and add a new function in the bash script

```
notifications () {
if [ "$per" -le "20" ]; then
       notify-send -u critical "Battery Low" "Connect Charger"
fi
}
```

Then call it, add, 
`[ "$1" = "notifications" ] && notifications && exit`

so now the icons and percentage will be 1s and just the notifications every 5 minutes.

**Comment by Momen-MKadry** [comment]
Ok thanks a lot

**Comment by Momen-MKadry** [comment]
Sorry if I'm being annoying but there is something wrong t=with the function call I think, I did as the previous comment but the notifications don't appear, I tried putting the function call in the conditions in the `icon` function and it worked, so the function is ok but sth is not right with call, I tried different conditions and ways to call the function but couldn't get it to work correctly, any ideas? 

```#!/usr/bin/env bash

bat=/sys/class/power_supply/BAT0/
per="$(cat "$bat/capacity")"

icon() {

    [ "$(cat "$bat/status")" = Charging ] && echo "" && exit

    if [ "$per" -gt "90" ]; then
        icon=""
    elif [ "$per" -gt "80" ]; then
        icon=""
    elif [ "$per" -gt "70" ]; then
        icon=""
    elif [ "$per" -gt "60" ]; then
        icon=""
    elif [ "$per" -gt "50" ]; then
        icon=""
    elif [ "$per" -gt "40" ]; then
        icon=""
    elif [ "$per" -gt "30" ]; then
        icon=""
    elif [ "$per" -gt "20" ]; then
        icon=""
    elif [ "$per" -gt "10" ]; then
        icon=""
    elif [ "$per" -gt "0" ]; then
        icon=""
    else
        echo  && exit
    fi
    echo "$icon"
}

percent() {
    echo "$per"
}


notifications() {
    if [ "$per" -le "20" ]; then
        notify-send -u critical "Battery Low" "Connect Charger"
    fi
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
[ "$1" = "notifications" ] && notifications && exit
exit

```
