### ISSUE TITLE
[BUG] Error de fuentes en powermenu

### ISSUE THREAD

**Issue by Ramdonx** [gh0stzk/dotfiles#352]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

Instale ttf-google-fonts-git y ttf-ms-fonts, luego de hacerlo así luce el menu: 
![Shot-2024-11-06-144636](https://github.com/user-attachments/assets/a7ec822c-15f0-4e13-b5b4-5e90fa58ac07)

### Reproducing the issue

Pacman -S ttf-google-fonts-git ttf-ms-fonts

Open Powermenu
Super+Alt+p

### System information

Estoy usando ArchLinux y una instalacion limpia desde el script

**Comment by gh0stzk** [comment]
Esos paquetes son del aur? intente descargarlos, pero me da error 404, y asi con calquier paquete de aur, creo que por ayer lei que habia un problema, lo resuelvo en el transcurso del dia y tratare de replicar tu problema.

**Comment by gh0stzk** [comment]
Si ya los pude instalar, y en efecto la fuente se arruina, en el transcurso del dia lo resuelvo.

**Comment by gh0stzk** [comment]
Ok ya lo solucione, puedes descargar o copiar a mano el contenido del archivo. https://github.com/gh0stzk/dotfiles/blob/master/config/bspwm/src/PowerMenu

Si lo descargas, asegurate de volver a darle permisos de ejecucion, ya que se perdera ese permiso.

**Comment by Ramdonx** [comment]
Funciona, gracias!!
