### ISSUE TITLE
[help wanted] Quiero usar stalonetray

### ISSUE THREAD

**Issue by Ramdonx** [gh0stzk/dotfiles#353]
Ya edite Theme.sh de Pamela

# Set stalonetray config
set_stalonetray_config () {
	sed -i "$HOME"/.config/bspwm/stalonetrayrc \
	    -e "s/background .*/background \"#1D1F28\"/" \
	    -e "s/vertial .*/vertial true/" \
	    -e "s/geometry .*/geometry 1x1-990+54/" \
	    -e "s/grow_gravity .*/grow_gravity NE/" \
	    -e "s/icon_gravity .*/icon_gravity NE/"
}

y

### Apply Configurations

set_bspwm_config
set_term_config
set_picom_config
set_stalonetray_config
set_dunst_config
set_eww_colors
set_launchers
set_appearance
set_geany
launch_theme

No se que mas debo configurar
Aqui hace referencia a un archivo (creo) pero no existe ese archivo
sed -i "$HOME"/.config/bspwm/stalonetrayrc \

Se que esta configuracion ya no utiliza stalonetray, pero quisiera usarla, me parece mas elegante.

**Comment by gh0stzk** [comment]
Si te falta el archivo stalonetrayrc y dentro de bspwmrc agregar el comando para iniciar el proceso de stalonetray que era compuesto de varios comandos, no lo recuerdo la verdad, pero si navegas en el historial de los commits, donde aun exista, te metes a ese commit y le das browse files, y estaras nevegando en ese momento de la historia, y desberian aparecerte los archivos.
