### ISSUE TITLE
I got tired of trying to run mpd and ncmpcpp :c 

### ISSUE THREAD

**Issue by codeskin-r** [gh0stzk/dotfiles#355]
Hey! Hello! Really Nice config but..  hahah, I need your help.

I did everything I could, even tried using chatgpt help, I saw info on different pages and I couldn't solve the problem I have, when I run "mpd" in the terminal I get the following message "exception: Failed to bind to '127.0.0.1:6600'; Failed to bind socket: Address already in use"

I don't know what to do, can you help me?

Because of this the songs don't appear when I open "ncmpcpp"

![Shot-2024-11-10-090809](https://github.com/user-attachments/assets/fb5bd81f-e16a-42a9-95e9-7df4a51f1bd0)
![Shot-2024-11-10-101846](https://github.com/user-attachments/assets/8b35a05a-7531-4938-bada-29b39b2dc5c8)

**Comment by gh0stzk** [comment]
Ok first will check if mpd-service is loading in user mode, not system:

`sudo systemctl status mpd.service`
should be disable, inactive

Now check if is running in user:
`systemctl --user status mpd.service`
should be enabled and active

Now be sure you are not loading again mpd service like in bspwmrc, if you start mpd again with bspwm that message will appear. so if you starting mpd somewhere in bspwm, xinitrc or other, remove it.

Now check the config, if you are using my config everything should be ok.
Now kill the process
`pkill mpd`
and now start mpd again
`mpd`
if you see this message, is ok
*decoder: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg*

now open ncmpcpp
`ncmpcpp`

Press the "u" key should appear **database update finish**
Press the key "2"
Your songs should be listed now.

What sound server you use?? pipewire or pulseaudio???

**Comment by codeskin-r** [comment]
I was able to solve it, thank you very much!

**Comment by codeskin-r** [comment]
Thanksss

**Comment by gh0stzk** [comment]
The cheatsheet for ncmpcpp https://pkgbuild.com/~jelle/ncmpcpp/

from 1 to 9 keys, you have different options, 8 is the equalizer i show in videos. 1 is your current playlist.

acerca del blur en picom.conf agrega la opcion:

blur-kern = "3x3box";

eso haria que las ventanas semitransparentes tengan blur.. todas.

si quieres especificar, abre picom-rules y agrega

blur-background = false;
o true a el tipo de ventanas que quieras con true por ejemplo:

```ini

{
	match = "window_type = 'tooltip'";
	shadow = false;
	corner-radius = 0;
	fade = false;
	opacity = 0.90;
	full-shadow = false;
        blur-background = true;
},
```

Porsupuesto que dependiendo el tipo de ventanas que quieras con blur tendras que tambien modificar la opaciadad, solo las ventanas con transparencia tendran el efecto blur, si no estoy equivocado todas las ventanas cons transparencia en los dotfiles se veran afectadas, las que noquieras soolo agregas blur-background = false;

**Comment by gh0stzk** [comment]
Para eso tienes varias formas de hacerlo, primero tendrias que establecer que todas las ventanas tengan transparencias, eso lo haces facil en picom.conf

frame-opacity = 1.0;

cambia eso por, 0.7 o el de tu gusto.

asi ya con la opcion blur-background activado todas tendran efecto blur. despues en picom-rules.conf a cada tipo de ventana puedes quitarlo o dejarlo como esta, con blur-background = false;

**Comment by codeskin-r** [comment]
> Para eso tienes varias formas de hacerlo, primero tendrias que establecer que todas las ventanas tengan transparencias, eso lo haces facil en picom.conf
> 
> frame-opacity = 1.0;
> 
> cambia eso por, 0.7 o el de tu gusto.
> 
> asi ya con la opcion blur-background activado todas tendran efecto blur. despues en picom-rules.conf a cada tipo de ventana puedes quitarlo o dejarlo como esta, con blur-background = false;

Gracias! Ahora si quedo mucho mejor todo con blur :D
