### ISSUE TITLE
Polybar customization

### ISSUE THREAD

**Issue by Aziz-Zahran** [gh0stzk/dotfiles#358]
I really like your polybars, however i havent really found a way to access them directly, could you possibly guide me?

**Comment by gh0stzk** [comment]
The configuration of the bar are in ~/.config/bspwm/rices/RICE/ in config and modules .ini files.
Of course except in andrea, z0mbi3 that bars are made with eww.

**Comment by Aziz-Zahran** [comment]
would it be possible to import them from into my own dot files? if so how so because I'm not familiar with your ways.

**Comment by gh0stzk** [comment]
Yes, it shouldn't be difficult.

**Comment by Aziz-Zahran** [comment]
Do i just copy the config.ini into my dot file directory or is that not sufficient?

**Comment by gh0stzk** [comment]
Mmmm no, you will need to change some things like the network interface, the update script location...
