### ISSUE TITLE
Cambiar tipo de font

### ISSUE THREAD

**Issue by IvanHapo** [gh0stzk/dotfiles#360]
Hola ghoszt, disculpa la molestia, me gusta mucho el dotfile en general pero he intentado cambiarle la tipografía al sistema en general y no tuve éxito, cambie de varios lugares pero no logro hacerlo correctamente.

Podrias guiarme para cambiar le font del sistema en general  o donde deberia ir para que se cambie en el navegador y tambien en el VSCode. Porque en la terminal por ejemplo si me gusta ese font.

Saludos, que andes bien.

**Comment by gh0stzk** [comment]
Hola, cuando instalas mis dotfiles, te instala una app llamada `lxappearance` ejecutala dese la terminal o buscala en el launcher de apps, desde ahi puedes cambiar la fuente entre otras cosas.

**Comment by IvanHapo** [comment]
Ohh perfecto, no se me habia instalado por lo visto. 

Muchas gracias, que tenga una buena semana :).
