### ISSUE TITLE
Change the key layout

### ISSUE THREAD

**Issue by sdslot** [gh0stzk/dotfiles#361]
Change the key layout.
How to change the layout, for example add ru,us ?

**Comment by gh0stzk** [comment]
If u wanna change from ru layout to us, press `super + alt + k`

**Comment by sdslot** [comment]
> Если вы хотите сменить раскладку с ру на нашу, нажмите `super + alt + k`

what is the best way to assign a quick switch, for example shift+ctrl ?

**Comment by gh0stzk** [comment]
Add it to sxhkdrc file.
