### ISSUE TITLE
[BUG] Neovim config is broken.

### ISSUE THREAD

**Issue by BIGGERSHOTLINUX** [gh0stzk/dotfiles#364]
### Checklist before submitting an issue

- [x] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

When i start nvim, i get this message:
Error detected while processing /home/name/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/name/.config/nvim/init.lua
:16: module 'lazy' not found:
        no field package.preload['lazy']
        no file './lazy.lua'
        no file '/usr/share/luajit-2.1/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy.lua'
        no file '/usr/local/share/lua/5.1/lazy/init.lua'
        no file '/usr/share/lua/5.1/lazy.lua'
        no file '/usr/share/lua/5.1/lazy/init.lua'
        no file './lazy.so'
        no file '/usr/local/lib/lua/5.1/lazy.so'
        no file '/usr/lib/lua/5.1/lazy.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/name/.config/nvim/init.lua:16: in main chunk
Press ENTER or type command to continue
and then its just barebones nvim.

### Expected behaviour

Expected behavior would be the one in the wiki and homepage

### System information

Arch Linux
Other Window managers:
Hyprland
Niri

**Comment by gh0stzk** [comment]
Mmmm if u enter nvim skip the error message and you can do `:Lazy` press "U" fixes the problem?? 

Be sure ~/.config/nvim/lua/ dir exists, should be, if u use my install script.

**Comment by BIGGERSHOTLINUX** [comment]
> nvim --version

NVIM v0.10.2
Build type: RelWithDebInfo
LuaJIT 2.1.1731601260

**Comment by BIGGERSHOTLINUX** [comment]
> Is my neovim config in ~/.config/neovim????

uhhhhh no
there is no .config/neovim

**Comment by BIGGERSHOTLINUX** [comment]
theres a nvim

**Comment by BIGGERSHOTLINUX** [comment]
i renamed it to neovim... it doesn't give me errors now but its still default nvim, even after running :Lazy

**Comment by gh0stzk** [comment]
Oh sorry bro, mi mistake, yes the dir must be nvim, ~/.config/nvim

lets do it manually, delete the dir ~/.config/nvim, now delete ~/.cache/nvim and delete ~/.local/share/nvim and ~/.local/state/nvim

Now clone my repo again in the dir you want, git clone --depth=1 https://github.com/gh0stzk/dotfiles.git

now enter my repo, cd dotfiles

now copy the .../dotfiles/config/nvim directory and paste in ~/.config/

Now open a terminal and execute nvim
