### ISSUE TITLE
[BUG] Firefox config

### ISSUE THREAD

**Issue by vmxt** [gh0stzk/dotfiles#366]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

After installing dotfiles on my new computer, the text in the Mozilla Configuration Search Bar is no longer display in the middle. I believe it covers up the extension manager and Firefox account in the upper right corner. Does anyone know where I can set this adjustment?

### Expected behaviour

Expecting that it should be displayed in the center.

### Additional context

![image](https://github.com/user-attachments/assets/b8b38ef8-6a44-4682-985d-86a72f6acf3c)

### System information

I am using Arch Linux clean installation and only in a bspwm DE.

**Comment by gh0stzk** [comment]
Of course i need to update more things but for now this solves the problem.

**Comment by vmxt** [comment]
yea thats the only second option is to add flexible space. but looks good at the moment. thanks
