### ISSUE TITLE
[BUG]  Terminales y ventanas no se ven ni puedo escribir en ellas

### ISSUE THREAD

**Issue by Miguel-Angel-Batres** [gh0stzk/dotfiles#367]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

al abrir una ventana no puedo escribir ni ver nada de ella, me pasa al abrir las terminales con super + enter,  super + alt + o, y tambien al abrir el reproductor con shift + alt + k, al abrir ranger tambien solo me sale un sonido pero no lo abre

![Shot-2024-11-28-170538](https://github.com/user-attachments/assets/5940d5ad-0f57-4352-8f3b-34cbfd625acd)

al abrir otra terminal como konsole si funciona la terminal, al abrir alacritty usando konsole obtengo el mismo bug

### System information

uso archlinux puro, tenia antes plasma y sobre plasma instale dotfiles, este error no me habia pasado pero por unas desisntalaciones que hice por conflictos de pipewire y pulseaudio desinstale plasma, y al volver a reinstalar doftiles me aparecio este error.

**Comment by gh0stzk** [comment]
Abre konsole que si te sirve y pega este comando: `Term --terminal`

y mira que errores lanza.

**Comment by Miguel-Angel-Batres** [comment]
Tuve que reinstalar el sistema, el error se extendio a muchas cosas, tambien se bugearon otras aplicaciones ajenas a este repositorio, pero ya esta todo bien, desconosco cual era el problema, igual gracias
