### ISSUE TITLE
[BUG] Skype window. 

### ISSUE THREAD

**Issue by guidamiao** [gh0stzk/dotfiles#368]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

Well, here's the thing, I tried everything and I couldn't find a solution.

I use Skype a lot for work, but Skype always opens a "second window" when I'm on a call, as in the example in the image (print_1).

However, in bspwm this window appears as if it were a normal screen that opens all the time. So it always opens a window showing the option to hang up, mute, etc.

I did a test in hyprland, and in it, the window opens normally like in print_1, and not as if it were another app opening.

Is there any way to configure this in these files? Because I always have to close this new window, and then if I go to another work area, this screen appears again.

print_1
![image](https://github.com/user-attachments/assets/de8c805b-e019-4d71-b093-6078c7f5d901)

### Reproducing the issue

Just install Skype, make a call and switch to another desktop, this second Skype screen will appear, showing the buttons to hang up, mute, share screen, etc.

### Expected behaviour

In hyprland, for example, this doesn't happen because it lets this other window float and stay in the correct size.

Is it possible to do the same thing in these files?

### System information

Clean installation with your files :)

**Comment by gh0stzk** [comment]
Ok let me check. for sure will be fixed with a rule, i only need to know the class or instance of that window.

**Comment by guidamiao** [comment]
Is there any way I can get that to help you? 

I think it is a window, because it always opens and overlays the other screens you have in the workspace, kind of forcing

If there's any way I can get this for you, let me know.

**Comment by guidamiao** [comment]
Example, 

I'm in connection at that moment, and then he gets like this since in fact serious only that little standard screen

![image](https://github.com/user-attachments/assets/eb7c9c8b-2802-40ea-bcd5-495e85d0ab3b)

**Comment by gh0stzk** [comment]
Ok i installed skype, but i have one problem, my 10 contacts are from 2018 xD no one can accept a call, mmm i need the class or instance of that window, when you have that window opened, pls open a terminal and execute `xprop` and click in the problematic window. and post here the output.

**Comment by guidamiao** [comment]
Here, I was on a call and I took it, I think that would be what I needed.

```
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_ABOVE
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_USER_TIME(CARDINAL) = 1651652
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified location: 857, 130
		program specified minimum size: 180 by 180
		program specified maximum size: 500 by 500
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
XdndAware(ATOM) = BITMAP
_NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 2
_GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED(CARDINAL) = 1
WM_NAME(UTF8_STRING) = "Skype"
_NET_WM_NAME(UTF8_STRING) = "Skype"
WM_WINDOW_ROLE(STRING) = "browser-window"
WM_CLASS(STRING) = "skype", "Skype"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_PID(CARDINAL) = 2336
WM_CLIENT_MACHINE(STRING) = "archlinux"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, _NET_WM_PING, _NET_WM_SYNC_REQUEST
```

**Comment by gh0stzk** [comment]
Ok i see that window have the sticky state thats why it follows you to another workspaces, i check in skype options, call options, there is an option called show window call when skype is on second plane, try disabling this option and check if thats what you want, if not, then i will help you creating a rule for that window.

![Shot-2024-11-30-081237](https://github.com/user-attachments/assets/ed313434-0baf-41fb-8709-c5ac17069e96)

**Comment by guidamiao** [comment]
OK, I'll try it this way today at work, if it works even better. If not, I accept the help of creating a rule.

**Comment by guidamiao** [comment]
I'm going to finish the issue, because this way you really answered what I needed. Thanks for the help! Have a good end of the year!

**Comment by gh0stzk** [comment]
I'm glad you solved your problem. Deducing your problem, hyprland is where it doesn't work as it should, that window should be kept in the background. But there are still many apps that do not work as they should in window managers.

**Comment by guidamiao** [comment]
In fact, hyprland doesn't work normally, but I prefer bspwm, anyway thanks for the help!
