### ISSUE TITLE
[BUG] The ~/.config/geany/geany.conf is partially in italian

### ISSUE THREAD

**Issue by kmeaw01** [gh0stzk/dotfiles#370]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

statusbar_template=línea: %l / %L	 col: %c	 sel: %s	 %w      %t      %mmode: %M      codificación: %e      tipo de archivo: %f      ámbito: %S

### Expected behaviour

statusbar_template=line: %l / %L	 col: %c	 sel: %s	 %w      %t      mode: %M      encoding: %e      file type: %f      scope: %S

### System information

Clean Install

**Comment by gh0stzk** [comment]
Ohh thank you i already modified. i will push it in next update.
