### ISSUE TITLE
[BUG] pressing super+l opens a blue block window after which nothing works

### ISSUE THREAD

**Issue by inodinwetrust10** [gh0stzk/dotfiles#372]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

A blue window opens after i press windows+l key and all other buttons malfunction and i have to restart the pc

### Reproducing the issue

press windows+l 
![Shot-2024-12-10-105028](https://github.com/user-attachments/assets/0040b6b0-15f0-415f-a386-0c883deca78a)

### System information

nvidia rtx 3050 mobile
amd ryzen 6800h
endevourOS

**Comment by inodinwetrust10** [comment]
Also the lockscreen doesnt work and after pressing suspend and turning it on again...the screen goes black but we're still able to perform operations

**Comment by 0xN1nja** [comment]
The blue block you're talking about is a selection window, which is completely normal and intended when you press `super + l`. To remove it, press the keybinding for deselection. This is the intended behavior.

About the lock screen, do you have `i3lock-color` installed? What's the output of `ScreenLocker`?

**Comment by gh0stzk** [comment]
Did you add more shortcuts???  that blue space is preselection. But is not binded to super + l , the preselection is binded to ctrl + super + (h,v) .

If you add more shortcuts that interfere with existing ones, thats the reason your system malfunction, be sure the shortcuts you add not interfere with the existing ones.

**Comment by gh0stzk** [comment]
When preselection window apears, its waiting for you, to open another app, in the preselection space, if you wanna cancel preselection just press `ctrl + super + q ` But as i said, another shortcut is interfering with the preselection one, that why your system freeze.
![Shot-2024-12-09-234715](https://github.com/user-attachments/assets/6532753f-c96e-4e05-b13f-6e3bded44a24)

**Comment by inodinwetrust10** [comment]
yeah reinstalling the config seems to fix that but the suspending problem still persists

**Comment by gh0stzk** [comment]
The suspending problem is more an OS config issue, do you have swap? zram? i read about that problem in more DEs or wms, well here are 11:55 pm and going to sleep now, tomorrow will try to help you with that.

But you can search about googling "black screen after suspend"

**Comment by inodinwetrust10** [comment]
okk thank you

**Comment by gh0stzk** [comment]
https://bbs.archlinux.org/viewtopic.php?id=290540
https://bbs.archlinux.org/viewtopic.php?id=290523
https://www.reddit.com/r/archlinux/comments/y5k0qn/need_help_to_wakeresume_from_suspend_only_see/

I just test and dont have the issue, try linux-zen kernel, just to test if resuming from suspend works in that kernel. I read linux-zen doesnt have that issue, and apparently that issue happends aaaalot, you will need to see what happend there. In second link, someone post the commands to see the errors, start with that, and try linux-zen kernel.

**Comment by inodinwetrust10** [comment]
also can you tell how to use the animated wallpaper please?
yeah changing it to zen fixed the issue
