### ISSUE TITLE
Display config 

### ISSUE THREAD

**Issue by Bitbrglr** [gh0stzk/dotfiles#373]
Brand new please help me find where to change to 1920x1080...
Awesome work btw I'm going to enjoy learning with your amazing setups.

**Comment by vmxt** [comment]
Option1: Try `xrandr` you can see all the details about your port and screen resolution and it can be configured like `xrandr --output DP-0 --mode 1920x1080 --rate 240`

 `DP-0` is my main display port. It depends upon your setup and the `--rate` is depending on the how many `Hz` supported in your monitor setup

Option2: you can also try `nvidia-settings` if you're in nvidia setup. basically easy setup GUI.

**Comment by gh0stzk** [comment]
or you can use arandr.

**Comment by Bitbrglr** [comment]
Bless your heart my friend 🙏
Total newbie but dedicated and so grateful to learn in an environment so
beautiful ❤️
Muchos Gracias 🙏
PlantsOnFire
