### ISSUE TITLE
[BUG]  polybar is not showing icons under themes

### ISSUE THREAD

**Issue by Only-Moon** [gh0stzk/dotfiles#374]
### Checklist before submitting an issue

- [X] I have searched through the existing closed and open issues and made sure this is not a duplicate
- [X] I have specifically verified that this bug is in the dotfiles and is not an error in my installation, configuration or operating system.

### Description of the bug

polybar is not showing any icons, only one theme is showing as seen in last screenshot attachted below 
![Shot-2024-12-13-213816](https://github.com/user-attachments/assets/6010ac4b-b5ae-457b-9d96-6711b07ee5ea)
![Shot-2024-12-13-213426](https://github.com/user-attachments/assets/30f51e38-213e-4f03-b2e0-d3bdba1d997c)
![Shot-2024-12-13-212821](https://github.com/user-attachments/assets/59ead1b7-3b81-4b0a-b291-1e4e46770311)

working theme
![Shot-2024-12-13-214021](https://github.com/user-attachments/assets/b10a6998-c2f8-42aa-969e-d3e63a45fc0e)

### System information

im on a vmware, neofetch below
![image](https://github.com/user-attachments/assets/e0b9048e-2c43-4a91-bfb3-cc388548a17b)

`xrandr --query`
![image](https://github.com/user-attachments/assets/8a8091a5-478f-4ff4-b564-ea19b510b4b2)

**Comment by gh0stzk** [comment]
Hello go to emilia theme. then open a terminal and kill polybar `pkill polybar` 
Now start it in the terminal with this command: `polybar --log=warning emi-bar -c $HOME/.config/bspwm/rices/emilia/config.ini`

And paste here the output.
Possibly someting went wrong when the fonts are moving from repo dir to fonts dir.

**Comment by Only-Moon** [comment]
here are the logs in a file 
[polybar.log](https://github.com/user-attachments/files/18137223/polybar.log)

**Comment by gh0stzk** [comment]
Could you check if in $HOME/.local/share/fonts/ you have MaterialDesignIconsDesktop.ttf font.

if not copy font dotfiles dir $HOME/dotfiles/misc/fonts to $HOME/.local/share/fonts/

**Comment by Only-Moon** [comment]
yes, that was the case. i did ran the RiceInstaller, not sure why it wasn't there
