### ISSUE TITLE
eww configs don't work !

### ISSUE THREAD

**Issue by AYehia0** [gh0stzk/dotfiles#4]
Can't run any eww widget for the themes that have eww.

```
~ ❯ eww daemon                                                
 2022-09-21T21:08:02.531Z ERROR eww > Failed to initialize eww paths

Caused by:
    Configuration directory /home/none/.config/eww does not exist
```
This is the first time I use eww, so fresh installation doesn't create a : `/.config/eww`
I also tried to run just the script : 
```
~ ❯ ~/.config/bspwm/rices/pamela/widgets/calendarlauncher     
eww > Trying to find server process at socket /run/user/1000/eww-server_L2hvbWUvbm9uZS8uY29uZmlnL2JzcHdtL3JpY2VzL3BhbWVsYS93aWRnZXRz
Failed to connect to the eww daemon.
Make sure to start the eww daemon process by running `eww daemon` first.
 2022-09-21T21:11:05.948Z INFO  eww > Trying to find server process at socket /run/user/1000/eww-server_L2hvbWUvbm9uZS8uY29uZmlnL2JzcHdtL3JpY2VzL3BhbWVsYS93aWRnZXRz
Failed to connect to the eww daemon.
Make sure to start the eww daemon process by running `eww daemon` first.
```
The problem is related to `eww` since eww moved to yuck but the installed one here still trying to find xml : 
```
━━━━━━━━━━━━━━━━━━━━━━━┓
┃Initializing eww daemon┃
┗━━━━━━━━━━━━━━━━━━━━━━━┛
    
 2022-09-21T21:53:29.712Z INFO  eww::server > Loading paths: config-dir: /home/none/.config/bspwm/rices/pamela/widgets, ipc-socket: /run/user/1000/eww-server_L2hvbWUvbm9uZS8uY29uZmlnL2JzcHdtL3JpY2VzL3BhbWVsYS93aWRnZXRz, log-file: /home/none/.cache/eww_L2hvbWUvbm9uZS8uY29uZmlnL2JzcHdtL3JpY2VzL3BhbWVsYS93aWRnZXRz.log
 2022-09-21T21:53:29.712Z ERROR eww         > Failed to load eww config file /home/none/.config/bspwm/rices/pamela/widgets/eww.xml
```

**Comment by gh0stzk** [comment]
Hello, ok then thats strange behavior so please, first confirm this;
type eww -V
what version you have installed? it must be eww 0.4.0
My eww configs are not linked to eww default config dir in ~/.config/eww/  please check if there is something there, if possible delete eww dir from /.config.
what version u installed? the one from my install instructions? must be yay -S eww
there are 3 in AUR, eww, eww-git and eww-wayland. must be the first one.

I try to recreate your error in pamela rice with 
❯ ~/.config/bspwm/rices/pamela/widgets/calendarlauncher     
but is succesfully launched;
  z0mbi3 ~ ❯❯ ~/.config/bspwm/rices/pamela/widgets/calendarlauncher
ok good!
please confirm that calendarlauncher have execute permissions. if not is a permission problem

**Comment by AYehia0** [comment]
Thank you @gh0stzk
The problem was I am on v0.1 lol, even though I installed using yay. Some how the installed bin was linked to `/.local/bin/eww` so I had to delete. and build from source again.
