### ISSUE TITLE
ncmpcpp can't open

### ISSUE THREAD

**Issue by vigiapriliansyah** [gh0stzk/dotfiles#40]
bro i have problem when i open ncmpcpp on terminal 
Error while processing option "lyrics_directory": option already set

**Comment by gh0stzk** [comment]
Try modifying the location of that directory, open ~/.config/ncmpcpp/config file, search for
lyrics_directory = ~/.config/ncmpcpp/lyrics and change it to any location. and try to open it again. make sure the directory exists.
