### ISSUE TITLE
error with ncmpcpp

### ISSUE THREAD

**Issue by AndersonVilela** [gh0stzk/dotfiles#44]
i'm a noob with rices bspwm so i installed it in dual boot windows with archcraft, and then i installed the script but it has widgets and some things that don't work for me, could you help me in any way? or create a video on youtube could be a series configuring each config and explaining then I would probably better understand what was happening and could solve the problems

**Comment by gh0stzk** [comment]
Sure, probably the battery, brightness, network modules are the one you have problems..

Open ~/.config/bspwm/scripts/system.ini

And edit it according to your hardware.
There, are the commands to use to know what to put, once you do that just restart bspwm with "super + alt + r" and you should no longer have problems.

**Comment by gh0stzk** [comment]
Ok so open a terminal and run ncmpcpp and see if it throws any errors.

Then check the configuration files of .config/mpd/mpd.conf and
.config/ncmpcpp/config

make sure the music directory is the same and point to where you have your music.

Finally in a terminal write "killall mpd" then write again "mpd" and see if it gives you any error.

**Comment by AndersonVilela** [comment]
bro how did you make the edges rounded in bspwm using bspwm and picom?
