### ISSUE TITLE
eww not installed from AUR

### ISSUE THREAD

**Issue by Pandoroz** [gh0stzk/dotfiles#47]
I have problems with the theme Andrea and z0mbi3, when I select them the tab-bar disappears

**Comment by gh0stzk** [comment]
Do you mean that the bars do not appear?

First make sure you have eww installed, open a terminal and type `which eww` the result should be **/usr/bin/eww** But if you get **eww not found** Possibly I failed to install eww from the installer and just install it, `yay-S eww`

**Comment by Pandoroz** [comment]
I try to install "eww" but I get botx_syntax error
![immagine_2023-03-24_162447142](https://user-images.githubusercontent.com/128830542/227584439-ff0264bf-fcea-438f-ab84-a8805aeb110b.png)

**Comment by gh0stzk** [comment]
Ah so that was the problem, I just investigated the eww and eww-git aur packages apparently for 3 days it has been giving problems.

What you can do is compile it manually, I leave you the steps:

`sudo pacman -S rustup cargo`

`git clone https://github.com/elkowar/eww`

`cd eww`

Then build:

`cargo build --release`

Once you've built it move the eww binary from **~/eww/target/release/eww** to **~/.local/bin/** then give execute permissions `chmod +x ~/.local/bin/eww`

If something fails because dependencies missing, here are all the necessary dependencies. to install, but probably already installed.
    gtk3 (libgdk-3, libgtk-3)
    pango (libpango)
    gdk-pixbuf2 (libgdk_pixbuf-2)
    cairo (libcairo, libcairo-gobject)
    glib2 (libgio, libglib-2, libgobject-2)
    gcc-libs (libgcc)
    glibc

**Comment by Pandoroz** [comment]
![immagine_2023-03-24_193111254](https://user-images.githubusercontent.com/128830542/227622409-24fed252-262b-429e-b347-f81aeaf4617d.png)

**Comment by gh0stzk** [comment]
Yeah, thats a normal error, u only start eww with out options. you dont need it, just change to andrea or z0mbi3 theme, now will display bars succesfully.

**Comment by Pandoroz** [comment]
Okay thank you very much! And nice work man :)

**Comment by Nathan-Shea** [comment]
I've got eww installed but am having the same problem as Pandoroz was having with the file not existing. Changing theme to andrea or z0mi3 doesn't do anything. Any ideas? Cheers heaps for the rice btw!

**Comment by gh0stzk** [comment]
> I've got eww installed but am having the same problem as Pandoroz was having with the file not existing. Changing theme to andrea or z0mi3 doesn't do anything. Any ideas? Cheers heaps for the rice btw!

same as above, open a termina and run `which eww` and `eww -V`
output must be **/usr/bin/eww** and **eww 0.4.0**

How you install  eww? from aur or manually compiling?

**Comment by gh0stzk** [comment]
if bars still not appearing just move eww binary to /usr/bin/ and will work.

**Comment by Nathan-Shea** [comment]
Cheers! Copying the eww binary from ~/.local/bin to /usr/bin/ did it for me.

**Comment by gh0stzk** [comment]
Now the installer download, compile and install eww. But today aur package was fixed. So i will keep this "manual" way to install without aur. I will close the issue as completed.
