### ISSUE TITLE
How i can add window animation

### ISSUE THREAD

**Issue by FatngatirBilek** [gh0stzk/dotfiles#50]
I want to add a window animation like fade when new app open. where is the picom configuration for that?

**Comment by gh0stzk** [comment]
My dotfiles uses picom from official repos, is the "stable" one from https://github.com/yshui/picom. without animations.

But if u wanna animations you have several options

https://github.com/FT-Labs/picom
https://github.com/dccsillag/picom
https://github.com/pijulius/picom

all are in AUR. Check the repos for the config.sample, to know what to add in picom config.

**Comment by gh0stzk** [comment]
If you only want a fade effect you can do it. modify file in /HOME/.config/bspwm/rices/RICE NAME/picom.conf

Fading options starts in line 44.

**Comment by FatngatirBilek** [comment]
thanks mate, that's really helped me
