### ISSUE TITLE
Installer script not working

### ISSUE THREAD

**Issue by 1ce-one** [gh0stzk/dotfiles#55]
Hello good sir , I have tried running your install script on two devices, but it still isn't working, there are two issues i have noticed
1. xdg-users-dirs-update
2. certain backup folders do not exist( i tried creating the folders but they just get deleted).
I'd really appreciate if you could help me out, I'm kinda new to this . 
Thank you in advance, I really like your setup and I'd really wanna have it on my pc .

**Comment by whenryweb** [comment]
1.
sudo pacman -S xdg-users-dirs
xdg-users-dirs-update

**Comment by gh0stzk** [comment]
Hello, thanks for your comment. I just ran the script and I noticed the error with the xdg package that you mention.

I already updated the script.

the correct package name is xdg-user-dirs.

Regarding the other error that you mention, it is not an error as such. It's just a message from the script.

At the end, you are in the rices, right?

**Comment by 1ce-one** [comment]
> 

no actually, only my shell and firefox changes to zsh , nothing else changes, the hotkeys also do not work(the alt+space to change rice). I am on endeavor os and running kde

**Comment by gh0stzk** [comment]
Exit kde and log into bspwm

**Comment by gh0stzk** [comment]
Yes kde login manager sometimes gives problems, I'm glad you were able to fix it.

I'm already considering the idea of ​​changing the default backend to "glx" but it's good that you fixed that too.

Could you tell me the name of the rice where you have the problem with the battery module. And if you can put a screenshot here. With `ctrl + Print` you can take the capture selecting the area.

To return firefox to how it was before just delete the "chrome" folder inside HOME/.mozilla/firefox/xxxx.default-release/

In the same folder also delete the file user.js.

**Comment by 1ce-one** [comment]
(https://user-images.githubusercontent.com/101406636/233133468-e40b3916-4d2a-4bb8-8afe-b9193a00176d.jpeg)
(https://user-images.githubusercontent.com/101406636/233133536-ad5be37e-5f2b-42d5-882f-2b4f8ff38cc1.jpeg)
(https://user-images.githubusercontent.com/101406636/233134529-db7b8b0d-9215-4320-8632-1adf8dba9026.jpeg)
-There is a small bubble on the rightmost side of the left segment , I'm thinking its the media control, is it supposed to be like that ?  -Emillia is the rice I am using.
-The firefox still has buttons on the right , I'm thinking its a KDE issue, I'll try the script once more on a more barebones install of arch
-The issue I'm having with firefox is , it tiles as a small window in the middle of the screen when opened. I'm thinking it's one of the issues that you stated about having 1600x900 res. I can't seem to find the bspwm config files , I feel kinda dumb , but I'd like to make some changes to the tiling and to make a few shortcuts to make managing tiles a little bit easier(and fix firefox).
Thank you

**Comment by gh0stzk** [comment]
ok first config files are in HOME/.config/bspwm/ the main one is bspwmrc

others like picom, dunst, polybar, alacrytty, bspwm specific options for the actual rice are in HOME/.config/bspwm/rices/RICE NAME/

binaries are in HOME/.config/bspwm/scripts/

for the battery module try this:

```
[module/battery]
type = internal/battery
full-at = 99
battery = ${system.sys_battery}
adapter = ${system.sys_adapter}
poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging><label-charging>
format-charging-prefix = " "
format-charging-prefix-font = 2
format-charging-prefix-foreground = ${emilia.red}
format-charging-background= ${emilia.mb}
label-charging = " %percentage%%"

format-discharging = <ramp-capacity><label-discharging>
format-discharging-background = ${emilia.mb}
label-discharging = " %percentage%%"

format-full = <label-full>
format-full-prefix = " "
format-full-prefix-font = 2
format-full-background = ${emilia.mb}
format-full-prefix-foreground = ${emilia.green}
label-full = "%percentage%%"

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${emilia.yellow}
ramp-capacity-background = ${emilia.mb}
ramp-capacity-font = 2

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${emilia.green}
animation-charging-bacground = ${emilia.mb}
animation-charging-font = 2
animation-charging-framerate = 700
```
copy it and replace it in the modules.ini file inside HOME/.config/bspwn/rices/emilia/

i just add the background options to the different prefixes.

**Comment by 1ce-one** [comment]
(https://user-images.githubusercontent.com/101406636/233376079-bb1868cc-1c7f-4900-b4ef-0a19d1636d37.jpeg)
The numbers still have the weird bg color

**Comment by gh0stzk** [comment]
```
[module/battery]
type = internal/battery
full-at = 99
battery = ${system.sys_battery}
adapter = ${system.sys_adapter}
poll-interval = 2
time-format = %H:%M

format-charging = <animation-charging><label-charging>
format-charging-prefix = " "
format-charging-prefix-font = 2
format-charging-prefix-foreground = ${emilia.red}
format-charging-background = ${emilia.mb}
label-charging = " %percentage%%"
label-charging-background = ${emilia.mb}

format-discharging = <ramp-capacity><label-discharging>
format-discharging-background = ${emilia.mb}
label-discharging = " %percentage%%"
label-discharging-background = ${emilia.rmb}

format-full = <label-full>
format-full-prefix = " "
format-full-prefix-font = 2
format-full-background = ${emilia.mb}
format-full-prefix-foreground = ${emilia.green}
label-full = "%percentage%%"
label-full-background = ${emilia.mb}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
ramp-capacity-foreground = ${emilia.yellow}
ramp-capacity-background = ${emilia.mb}
ramp-capacity-font = 2

animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
animation-charging-foreground = ${emilia.green}
animation-charging-background = ${emilia.mb}
animation-charging-font = 2
animation-charging-framerate = 700
```
Try this one,


whats the problem with mpd?? open a terminal and write "mpd" wats the output?

**Comment by gh0stzk** [comment]
open ncmpcpp with `shift + alt + k` and press the 2 key. Can you see your songs listed??

If not, configure the directory where they are found as in the following link https://github.com/gh0stzk/dotfiles/wiki/Firsts-steps-after-installing#the-album-covers-in-notifications-and-widgets

The mpd module in polybar will not show if there are no songs in the directory.

First make sure mpd is active with `systemctl --user status mpd.service`

It should appear active in green.

----

I'm sorry I wrote wrong, I added a letter "r" in
`label-discharging-background = ${emilia.rmb}`

must be

`label-discharging-background = ${emilia.mb}`

**Comment by 1ce-one** [comment]
Thank you so much , the battery now looks perfect, I think you might want to change it in the rep.
(https://user-images.githubusercontent.com/101406636/233436709-fc6e3160-b9c0-4bef-9c3d-0b56c3809b64.jpeg)
(https://user-images.githubusercontent.com/101406636/233436712-de33c9ba-ec4d-4784-b450-acf21873393a.jpeg)
I've copied the music to music files but shit+alt+k shows up as empty.
Also this module only shows local music files and not spotify?

**Comment by gh0stzk** [comment]
open ncmpcpp shift + alt + k then press 2 and then press "u" key. This will update the database and your music must be listed.

MPD only show local, if you wanna spotify you could try this https://github.com/gh0stzk/dotfiles/issues/46#issuecomment-1482161297

**Comment by 1ce-one** [comment]
Hey man I think all of my problems are solved but I have one last tiny issue, with thunar not being themed dark, do you whats up with that?

**Comment by 1ce-one** [comment]
Thank you so much all my problems have been solved. Is there anything you'd like me to do for you.
 I really love my setup thank you so much for helping me out. You are AMAZING.

**Comment by gh0stzk** [comment]
I'm glad you're comfortable and happy with your setup, that's enough for me.
