### ISSUE TITLE
unable to launch bspwm and sxkhd, no .xinitrc provided

### ISSUE THREAD

**Issue by akhxl** [gh0stzk/dotfiles#57]
how am i supposed to start everything after downloaded the dot files on a fresh install for arch. i don't see a .xinitrc file.

**Comment by gh0stzk** [comment]
That depends on how you choose to start your graphical environment.

with a login manager or with xinitrc.

With a login manager I leave you the option of lightdm.

`sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings`

`sudo systemctl enable lightdm`

`sudo systemctl start lightdm`

**Comment by akhxl** [comment]
Thank You!! Is there any way i can donate to support more of your work?

**Comment by gh0stzk** [comment]
> Thank You!! Is there any way i can donate to support more of your work?

It is not necessary to donate, but thanks, as long as you like my themes it's fine for me
