### ISSUE TITLE
Is it possible to add only one rice ?

### ISSUE THREAD

**Issue by Saeed-Paris** [gh0stzk/dotfiles#58]

**Comment by gh0stzk** [comment]
Hello first, yes tou can disable de ascii stuff, just delete the last line in .zshrc file `$HOME/.local/bin/colorscript -r`

Second I'm working on an update to make the configuration more modular and easier to add or remove themes. But I don't think being able to install only the themes you want is going to be a feature.

Third thank you i will check that in the installer script.
