### ISSUE TITLE
Rofi cannot launch

### ISSUE THREAD

**Issue by pratikneupane** [gh0stzk/dotfiles#59]
I have checked with permissions and everything, when i launch the RiceSelector Script i get this error:

(process:3667): Rofi-WARNING **: 06:15:51.860: Failed to set locale.

**Comment by gh0stzk** [comment]
That is an error regarding your language setting. 
https://bbs.archlinux.org/viewtopic.php?id=253251

you need to set locale properly,

**Comment by pratikneupane** [comment]
it's launched properly thanks
