### ISSUE TITLE
screen resolution

### ISSUE THREAD

**Issue by DarkninOF** [gh0stzk/dotfiles#6]
Hello, I am not a programmer, I love your work is very good; I thank you for creating this content. I have been looking for a way to adapt it to my screen configuration and I could not find it, could you give me a hand on what files I have to change to adjust it to 1920x1080; thank you in advance.

**Comment by gh0stzk** [comment]
Hello, of course yes, please first tell me what is the theme you want to modify. all rices are polybar except 2, z0mbi3 and karla (karla will be upload in this week) in polybar rices you need to configure config.ini inside polybar dir.

**Comment by gh0stzk** [comment]
you wanna try to modify the bar? or what? emilias bar is set to be 90% of your screen. mmm maybe the position you said? in line 28 and 29 
offset-x = 5%
offset-y = 10

play with these values.

**Comment by gh0stzk** [comment]
if you send a screenshot would be better. whats you wanna try to do.

**Comment by DarkninOF** [comment]
Thank you if I have been playing with these values and the bar appears more centered, because it had a deviation to the right; thank you very much.

**Comment by DarkninOF** [comment]
thank you very much for your support and for your great work.
