### ISSUE TITLE
Extensions button missing in firefox theme

### ISSUE THREAD

**Issue by joelschmol** [gh0stzk/dotfiles#61]
I copied your firefox theme and i love it. but it removes the extensions button from the top. how would add that back?
![image](https://github.com/gh0stzk/dotfiles/assets/88237375/9a766fc3-f910-4e1c-b221-ddc130209326)

**Comment by gh0stzk** [comment]
Allright you need to open ~/.mozilla/firefox/xxxx.default-release/chrome/userChrome.css
_The xxxx are random numbers_
Search for 

```
#unified-extensions-button {
	display: none;
}
```
Is in line 180

Delete or comment these 3 lines and save it, open again firefox and you are done.

**Comment by joelschmol** [comment]
it worked. thank you
