### ISSUE TITLE
some assets or Icons or stuff Idk just weird

### ISSUE THREAD

**Issue by vbtab** [gh0stzk/dotfiles#65]
I can't see anything on z0mbi3 theme
on karla theme I can't see middle part and some other icons are missing
andrea theme fully invisible

other themes are working fine but Idk
1920x1080

**Comment by vbtab** [comment]
![Screenshot_2023-05-16-20-10-35_1920x1080](https://github.com/gh0stzk/dotfiles/assets/133824037/31504973-7047-4ae1-9303-64fd248bc536)

![Screenshot_2023-05-16-20-11-42_1920x1080](https://github.com/gh0stzk/dotfiles/assets/133824037/5a641b1b-0c1e-48e2-82c1-f07c88fc67e4)

**Comment by gh0stzk** [comment]
The second image shows errors retrieving rustup, its your mirrors. update your mirrors if u have reflector do it with reflector.

**Comment by gh0stzk** [comment]
`sudo reflector --verbose --latest 5 --country 'United States' --age 6 --sort rate --save /etc/pacman.d/mirrorlist`

**Comment by gh0stzk** [comment]
If u dont have reflector install it with `sudo pacman -Syyu reflector`

**Comment by vbtab** [comment]
![2023-05-16_20-48](https://github.com/gh0stzk/dotfiles/assets/133824037/fedb715c-f32d-4e2f-a25a-b575437c2467)

**Comment by gh0stzk** [comment]
The picom version used in my dotfiles is the official one form arch repos, its https://github.com/yshui/picom/blob/next/picom.sample.conf
There is the config file, you can copy the blur section and paste into ~/.config/bspwm/picom.conf
there u can play and test with direfferents backends see the general section

```
# Available backends "xrender" "glx" "egl" "xr_glx_hybrid"
backend = "glx";
```
The most stable is glx the one most people use without problems, try egl and xrender and see witch fixes your cpu usage.

**Comment by gh0stzk** [comment]
if that doesnt help u, maybe is a graphic drivers issue, check for the proper config of hardware acceleration.

**Comment by vbtab** [comment]
okay thanks

**Comment by gh0stzk** [comment]
ah for the icons in polybar, in all rices there is a file called modules.ini, there u can modify the icons, text, etc.. maybe you will need a font manager to see the fonts, u can use `sudo pacman -S font-manager`
