### ISSUE TITLE
App search and themes menu don't work

### ISSUE THREAD

**Issue by BaptouDev** [gh0stzk/dotfiles#69]
I press super + space and it doesn't open the app search menu. Same thing for the app search. The commands work with other functions.

**Comment by gh0stzk** [comment]
Hello, I do not fully understand your question, does it work or not? or in which functions do you say that it works?

open a terminal and paste this:
`rofi -show drun -theme $HOME/.config/bspwm/rices/${RICETHEME}/launcher.rasi`

Does it open rofi menu? shows errors in terminal?
