### ISSUE TITLE
list of anime wallpapers

### ISSUE THREAD

**Issue by SamIsOnMC** [gh0stzk/dotfiles#7]
hey u got a list of anime wallpapers i can remove? parents momento. i dont know every anime wallpaper in the assets folder and i cant view them cuz parents

**Comment by gh0stzk** [comment]
Wallpapers are in bspwm/rices/ricename/ you can remove or add from there.

bspwm/assets there are the rofi images for all the rices.

**Comment by SamIsOnMC** [comment]
thanks
