### ISSUE TITLE
enable battery indicator on all themes

### ISSUE THREAD

**Issue by Jacky2001** [gh0stzk/dotfiles#70]
I noticed that the battery indicator is only on some themes, how do I enable it on the rest of the themes as well?

**Comment by gh0stzk** [comment]
What you have to do is add the module. To do it inside each themes folder ~/.config/bspwm/rices/rice name/
There is a file called config.ini that is the polybar configuration file.

Inside you will find a section that looks like this:

```
modules-left = launcher sep2 bspwm sep2 title
modules-center = module module2
modules-right = mpd_control sep2 battery 
```
add **battery** in the place you want, left center or right and thats it. You need to do it in all themes. except z0mbi3, andrea. that are made with eww
