### ISSUE TITLE
Remove the area close button (Firefox)

### ISSUE THREAD

**Issue by levantu2003** [gh0stzk/dotfiles#72]
When i use 
".titlebar-buttonbox-container {
  display: none !important;
}" in my userChrome.css, it gives me a black area like the image below, do you know how to fix it ?
![Screenshot_2023-05-24-09-00-31_27693](https://github.com/gh0stzk/dotfiles/assets/107534756/e8915bbb-adcd-4334-9d63-b7f3ca30ffda)

**Comment by gh0stzk** [comment]
Mmmm no i dont know but you can try in https://www.reddit.com/r/FirefoxCSS/

**Comment by levantu2003** [comment]
after few hours finding the solutions on reddit, i finally found the way to fix it. Just add those code:
.titlebar-spacer {
  display: none !important;
}
