### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by aminejaamoum** [gh0stzk/dotfiles#74]
Hi bro, 

I already follow your steps, but after installing the destop is black and i have this error message in the bar:

> Status_command not found or is missing a library dependency (exit 127)

i already check the .xsession_error file:
 
> /bin/sh: ligne 1: /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1: Aucun fichier ou dossier de ce type
>   /bin/sh: ligne 1: /home/atlas/bin/thelauncher/tray-icon/thelauncher-trayicon: Aucun fichier ou dossier de ce type
>   unable to connect to the rxvt-unicode daemon: Connection refused
>   /bin/sh: ligne 1: eyecandy : commande introuvable
>   xrdb: No such file or directory
>   xrdb: can't open file '/home/atlas/.Xresources'
>   /bin/sh: ligne 1: /home/atlas/.config/i3/i3conkybar: Aucun fichier ou dossier de ce type
>   [../i3bar/src/child.c:506] ERROR: Child (pid: 886) unexpectedly exited with status 127
>   
>   (pcmanfm:840): Gtk-WARNING **: 00:10:59.718: Impossible de trouver le moteur de thème dans module_path : « murrine »
>   
>   (pcmanfm:840): Gtk-WARNING **: 00:10:59.719: Impossible de trouver le moteur de thème dans module_path : « murrine »
>   
>   (pcmanfm:840): Gtk-WARNING **: 00:10:59.722: Impossible de trouver le moteur de thème dans module_path : « murrine »
>   
>   (xfce4-power-manager:836): xfce4-power-manager-WARNING **: 00:10:59.725: Unable to connect to session manager : Impossible de se connecter au gestionnaire de session : SESSION_MANAGER environment variable not defined
>   
>   (xfce4-power-manager:836): xfce4-power-manager-WARNING **: 00:10:59.868: could not map keysym 1008ffa8 to keycode
>   
>   
>   ** (xfce4-power-manager:836): WARNING **: 00:10:59.897: No outputs have backlight property
>   
>   (xfce4-power-manager:836): xfce4-power-manager-WARNING **: 00:10:59.905: It seems the kernel brightness switch handling value was not restored properly on exit last time, xfce4-power-manager will try to restore it this time.
>   xfce4-power-manager-Message: 00:10:59.936: Set kernel brightness switch to 0
>   
>   (xfce4-power-manager:836): xfconf-WARNING **: 00:10:59.987: Failed to set property "xfce4-power-manager::/xfce4-power-manager/brightness-switch": L’opération a été annulée
>   xfce4-power-manager-Message: 00:11:00.044: Set kernel brightness switch to 0
>   ATTENTION: default value of option mesa_glthread overridden by environment.
>   ATTENTION: default value of option mesa_glthread overridden by environment.
>   ATTENTION: default value of option mesa_glthread overridden by environment.
>   ATTENTION: default value of option mesa_glthread overridden by environment.
>   ATTENTION: default value of option mesa_glthread overridden by environment.
>   ATTENTION: default value of option mesa_glthread overridden by environment.
>   
>   [ERROR glean_core] Error setting metrics feature config: Json(Error("EOF while parsing a value", line: 1, column: 0))
>   /bin/sh: ligne 1: /usr/local/bin/touchpadtap: Aucun fichier ou dossier de ce type
>   [1501:1501:0531/001107.135141:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
>   ATTENTION: default value of option mesa_glthread overridden by environment.
>   ATTENTION: default value of option mesa_glthread overridden by environment.
>   [...]

Any idea to fix it please ?

**Comment by aminejaamoum** [comment]
Thank u for your answer ! 
I get it, so the installation was good. I just do not start  the bspwm session

**Comment by gh0stzk** [comment]
Nice!
