### ISSUE TITLE
no output in terminal

### ISSUE THREAD

**Issue by 0xN1nja** [gh0stzk/dotfiles#75]
everything works fine except terminal (in vm) but works perfectly on bare metal tho

![image](https://github.com/gh0stzk/dotfiles/assets/71812498/62853ce3-e8c4-4bf5-9e24-4ab951868a6c)

**Comment by gh0stzk** [comment]
There is an error on logs?? in ~/xsession-errors file?

**Comment by 0xN1nja** [comment]
polybar|error: module/mpd_control: Connection refused
polybar|error: module/mpd: Connection refused

(process:512): GLib-CRITICAL **: 10:10:19.633: g_string_insert_len: assertion 'len==0 || val != NULL' failed

**Comment by gh0stzk** [comment]
If you install a terminal that is not gpu-accelerated such as xterm, tilix, do they open normally? try that.

If they open normally, it means that in your vm the graphic acceleration is not properly configured or the graphic driver you use is not correct. Can you watch youtube videos on your vm?

It's one of the few things I can think of about your problem.

**Comment by 0xN1nja** [comment]
![image](https://github.com/gh0stzk/dotfiles/assets/71812498/2def3f46-238c-4d30-8484-348b638a78a9)

**Comment by 0xN1nja** [comment]
I believe that the issue lies with VirtualBox and not with your dotfiles. Hence, I am closing this issue. Thank you.
