### ISSUE TITLE
Errors when starting rofi

### ISSUE THREAD

**Issue by Mareczek1311** [gh0stzk/dotfiles#77]
I just installed and got this error:
failed to open theme /home/username/.config/bspwm/rices//launcher.rasi

Also keybindigs like alt + @space doesnt work

**Comment by gh0stzk** [comment]
After reboot, you have the same problem? 
open a terminal and wite cat ~/.config/bspwm/.rice
whats the output?

**Comment by Mareczek1311** [comment]
displaying only aline

**Comment by gh0stzk** [comment]
if you write in a terminal, `echo "$RICETHEME"` is aline? 

You can check if all the files were copied successfully.
For example, see if you have the file ~/.config/bspwm/rices/**aline/launcher.rasi** is there..

could you send here the output from ~/.xsession-errors file, after trying to launch rofi with windows + space

**Comment by gh0stzk** [comment]
Ok, that's very strange, it's like the global variable isn't being applied.

Try this, edit the file ~/.config/bspwm/.rice

change `aline` for `emilia`

Then press `Super + Alt + r` to reload bspwm

and see if it works.

Other things:

1. Verify that the ~/.config/bspwm/bspwmrc file has execute permissions.
2. Everything else works except rofi?

**Comment by gh0stzk** [comment]
> after changing aline for emilia its still not working. bspwmrc has execute permissions
> 
> I don't know if i done everything correctly. I only followed the steps that are showed on repo and installed everything on newly installed system.

It is very strange, I have never received this error from people, there are no errors in the logs.
But without the necessary information I can't help you anymore, you didn't answer me if launching rofi is the only thing that fails. If the bars are displayed correctly, etc. If launching the rofi menu to change the theme doesn't work for you, how did you end up in the Aline theme? bspwm works?
