### ISSUE TITLE
eww building error

### ISSUE THREAD

**Issue by mnuddindev** [gh0stzk/dotfiles#80]
i am tried to install the dotfiles in my endevaour os, end of the installing process its showing 4 error while building eww. the errors said

Compiling unescape v0.1.0
error[E0635]: unknown feature `hash_drain_filter`
 --> crates/eww/src/main.rs:6:12
  |
6 | #![feature(hash_drain_filter)]
  |            ^^^^^^^^^^^^^^^^^

error[E0635]: unknown feature `drain_filter`
 --> crates/eww/src/main.rs:2:12
  |
2 | #![feature(drain_filter)]
  |            ^^^^^^^^^^^^

error[E0599]: no method named `drain_filter` found for struct `Vec<codespan_reporting::diagnostic::Label<usize>>` in the current scope
  --> crates/eww/src/error_handling_ctx.rs:55:23
   |
55 |     diagnostic.labels.drain_filter(|label| Span(label.range.start, label.range.end, label.f...
   |                       ^^^^^^^^^^^^ method not found in `Vec<Label<usize>>`

error[E0599]: no method named `drain_filter` found for struct `std::collections::HashMap` in the current scope
   --> crates/eww/src/widgets/widget_definitions.rs:130:62
    |
130 | ...ndled_attrs.drain_filter(|a, _| deprecated.contains(&a.0 as &str)).collect();
    |                ^^^^^^^^^^^^ method not found in `HashMap<AttrName, AttrEntry>`

Some errors have detailed explanations: E0599, E0635.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `eww` (bin "eww") due to 4 previous errors
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'eww-0.4.0-2':
error: packages failed to build: eww-0.4.0-2

**Comment by gh0stzk** [comment]
During today AUR was down for a few hours, maybe that was it, but it seems that it is already restored.

try manually

`paru -S eww --skipreview --noconfirm`

**Comment by gh0stzk** [comment]
Ok i just try to compile, and the seme error. 

Try `paru -S eww-bin --skipreview --noconfirm`

**Comment by mnuddindev** [comment]
>thanks for the reply but its generating another error.

curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading https://github.com/TheBearodactyl/eww-bin/releases/download/0.4.0/eww
    Aborting...
error: failed to download sources for 'eww-bin-0.4.0-1':
error: packages failed to build: eww-bin-0.4.0-1

**Comment by mnuddindev** [comment]
generating error

curl: (22) The requested URL returned error: 404
==> ERROR: Failure while downloading
https://github.com/TheBearodactyl/eww-bin/releases/download/0.4.0/eww
Aborting...
error: failed to download sources for 'eww-bin-0.4.0-1':
error: packages failed to build: eww-bin-0.4.0-1

**Comment by mnuddindev** [comment]
i think the eww-bin repo isnot exist anymore. that's why its generating a error. a person already commented on aur website about it

**Comment by gh0stzk** [comment]
I just tried to manually compile it from source and it keeps giving me the same error.

It is a development error, I will create an issue on the eww page. At the moment nothing can be done, it is not a problem or an error in my dotfiles.

**Comment by gh0stzk** [comment]
Someone already open an issue, https://github.com/elkowar/eww/issues/810

**Comment by mnuddindev** [comment]
i tried to fix it. what i did is i run the following command
`yay -G eww-bin`
it will download a folder called `eww-bin` then i edited the `PKGBUILD` and `.SRCINFO` file and updated the source of eww-bin (replaced with `https://github.com/Eidwood/eww-bin/raw/master/eww`) and tried to run another command `updpkgsums` then `makepkg -si`

successfully it's installed a binary of eww and i can acceess through terminal the eww is working fine but the problem is your code is not working i mean the bar is not responding while i am click on user or power menu or in calender.

do you can fix now?

**Comment by gh0stzk** [comment]
The problem must be the version you have installed please open a terminal and type, `eww -V`
i thought you have an older version, the repo from where you downloaded the binary is from 2021 the actual one is
**eww 0.4.0**

Let me upload my binary.

**Comment by gh0stzk** [comment]
https://www.mediafire.com/file/hxc0ydvqc2so8ob/eww/file

Put it on /usr/bin/
with execute permissions of course.

**Comment by gh0stzk** [comment]
That must work, but you have to wait some days until developers fix the problem and compile it again for your machine.

**Comment by mnuddindev** [comment]
thanks. it works.
