### ISSUE TITLE
Unable to install eww-x11-git when executing RiceInstaller

### ISSUE THREAD

**Issue by mycpphurts** [gh0stzk/dotfiles#82]
Attempting to install eww-x11-git gives a gpg key error due to the public keys on PKGBUILD in the AUR not being updated.

I haven't found a solution yet, but, maybe manually building the eww package from their GitHub could work

**Comment by gh0stzk** [comment]
Yes, it's not a problem with the AUR packages, eww and eww-x11-git are fine.

Compiling eww from source, from its main page gives the same error, it's a rust change.

I leave you my binary compiled on my machine, it should work for now.

https://www.mediafire.com/file/hxc0ydvqc2so8ob/eww/file

Links:
https://github.com/elkowar/eww/issues/810

The solution:
https://github.com/elkowar/eww/pull/815/commits/4f0943fdb07cbeaa061b7a9e1af2a49674446b83

**Comment by mycpphurts** [comment]
I'll give it a go in a VM for now, I'll let you know if anything :)

**Comment by MardOrange** [comment]
I installed Arch linux and I tried those commands he provided in his github page

1, curl "https://raw.githubusercontent.com/gh0stzk/dotfiles/master/RiceInstaller" -o $HOME/RiceInstaller

2,chmod +x RiceInstaller

3,./RiceInstaller

But whenever I use the third command nothing else happening.(I'm using VMware to run Arch in a windows 11 machine).
(I know it's not a problem from developer side it's just that I don't know how to install it and run so If you make a video about that it's gonna be usefull🙂)
