### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by SussyBakkaBirb** [gh0stzk/dotfiles#83]
Hi there! I just wanted to say thank you to you and all the contributors for creating these amazing Arch Linux Rices! However, I'm having an issue and I was wondering if you could help me out. I want to uninstall it, but I'm not quite sure how to go about doing that. Would you be able to provide me with some guidance on how to uninstall it? Thanks so much!

**Comment by gh0stzk** [comment]
Sure, no problem, just delete the configuration folders located inside ~/.config/ obvbiously only the bspwm ones.

If you also want to delete the installed packages, this is the list of packages that are installed with my dotfiles.

bspwm polybar sxhkd \
alacritty brightnessctl dunst rofi lsd \
jq polkit-gnome git playerctl mpd \
ncmpcpp geany ranger mpc picom xdotool \
feh ueberzug maim pamixer libwebp xdg-user-dirs \
webp-pixbuf-loader xorg-xprop xorg-xkill physlock papirus-icon-theme \
ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-terminus-nerd ttf-inconsolata ttf-joypixels \
zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting xorg-xsetroot xorg-xwininfo xorg-xrandr

**Comment by SussyBakkaBirb** [comment]
Thank you!
