### ISSUE TITLE
Failed to install eww and Polybar works wrong

### ISSUE THREAD

**Issue by sofpixaol** [gh0stzk/dotfiles#85]
1. failed to install eww
![ShoT_2023-07-03-10-27-22_1920x1080](https://github.com/gh0stzk/dotfiles/assets/81808405/b51dcd74-de4a-4a60-952d-a8ccc6a70fe2)
2. Polybar works wrong
![ShoT_2023-07-03-10-32-23_1920x1080](https://github.com/gh0stzk/dotfiles/assets/81808405/2e2c2ec0-6d5c-49d1-af6c-861d0c634f6a)

**Comment by gh0stzk** [comment]
Unfortunately about eww is a rust issue, which the eww developers haven't patched. from aur, nor downloading the source directly from the eww page can be compiled satisfactorily.
But here is my binary compiled just drop in /usr/bin/ https://www.mediafire.com/file/hxc0ydvqc2so8ob/eww/file

The polybar problem, possibly some error occurred when the fonts were copied.

Just manually copy them from ~/dotfiles/misc/fonts/ to ~/.local/share/fonts/

and then run in a terminal fc-cache -rv

**Comment by sofpixaol** [comment]
I tried to solve the polybar problem first. I've manually copied the fonts and run fc-cache -rv, but when I started bspwm, I found nothing changed.
In addition, my first installation was successful. But I want to customize it, so I forked your repo, modified it, and then installed it about 5 times. And it went wrong. Even when I re-clone your repo and run your RiceInstaller, my polybar still doesn't work well.

**Comment by gh0stzk** [comment]
To rule out errors, you should follow these steps in this order.

1. Clean your cache, all the cache, you can do it with stacer. Or manually if you know where the cache and font cache are located.

2. Once clear the cache, To be extremely sure that the files and folders are overwritten by the new ones, you can manually copy them from HOME/dotfiles to ~/.config/ and all other folders. this is not mandatory but you will be sure that everything is in place. Clone my repository, the default settings work fine so it should work fine for you.

3. Once you have verified that everything works with my configuration, make your modifications, but make sure that the name of the fonts is correct in the file ~/.config/bspwm/rices/ricename/config.ini, which is the polybar one.

To see the correct name of the font you can do `fc-list | grep JetBrains`  for example.

**Comment by sofpixaol** [comment]
I tried, and nothing changed. But when I ran `fc-list | grep Material`, it output nothing. Then I copied all the fonts in ~/.local/share/fonts to /usr/share/fonts, and it worked. But I dont know why I have to do this to make it work well.

**Comment by gh0stzk** [comment]
> I tried, and nothing changed. But when I ran `fc-list | grep Material`, it output nothing. Then I copied all the fonts in ~/.local/share/fonts to /usr/share/fonts, and it worked. But I dont know why I have to do this to make it work well.

What distro do you use?

**Comment by sofpixaol** [comment]
Arch Linux

**Comment by gh0stzk** [comment]
> Arch Linux

Well thats weird.. but if it works now..
