### ISSUE TITLE
Eww can't be compiled! try this!

### ISSUE THREAD

**Issue by gh0stzk** [gh0stzk/dotfiles#86]
At the moment the eww package cannot be compiled successfully. It's a rust problem, which the eww developers haven't patched.

Neither the AUR nor downloading the source directly from the eww page can be successfully compiled.

At the moment the only solution is to share you my compiled binary and you have to put it in the /usr/bin/ folder and give it execution permissions. `chmod +x eww`

https://www.mediafire.com/file/hxc0ydvqc2so8ob/eww/file

**Comment by Cstrp** [comment]
Now work this - https://elkowar.github.io/eww/
