### ISSUE TITLE
Battery notifications for laptops

### ISSUE THREAD

**Issue by ayushvyas-1** [gh0stzk/dotfiles#87]
My Laptop keeps shutting down and its getting annoying, 
could you please suggest me a way to get notified when my battery is low ? ( other than running those scripts to fetch BAT1 values every minute..) 

* I tried  whole day to to sort this out. and searched through whole archwiki. but nothing worked !
 
> I tried to make udev rules also installed  [batify](https://github.com/Ventto/batify) but didn't work.
>This is the ONLY issue i have in this rice.
>your rices are awesome btw.
>Please give me a good solution.(sorry for the rant)

**Comment by gh0stzk** [comment]
there are many bash scripts to notify you about battery charge. Search for **dunstify script warning low battery**
Here is one https://github.com/KHZ-INTL/low_battery_notification_cron

Although you can also simply look at the module in polybar to see the level of your battery, it is true that it is not active in all rices, what is the name of the rice you are in? If it's not active in that one, just enable it, go to ~/.config/bspwm/rices/ricename/config.ini and add it to the active modules, either left, center or right.

If the module is active but does not show it, then it is taking the wrong values ​​from your battery, edit the correct values ​​following this link https://github.com/gh0stzk/dotfiles/wiki/Firsts-steps-after-installing
