### ISSUE TITLE
Nothing after installation success

### ISSUE THREAD

**Issue by rogue-agent** [gh0stzk/dotfiles#89]
Hello,
I've fresh installed and wanted to try this out. Never used BSPWM before so I don't know if this is basic behaviour or what is. *it also overwrote my zshconfig*.

I ran the installer and it completes successfully. But when I reboot I get back into the tty1 on Arch-zen 6.4.2 and Efistub+refind configuration. When I run exec bspwm it throws me back into the start screen of tty1 to login.

What should I do, I need to get some work done...

**Comment by gh0stzk** [comment]
You need a login manager, such as lightdm or ssd.

`sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings`

Then activate it, `sudo systemctl enable lightdm` and then reboot.

if you only have bspwm it will be by default, if you use more DE or Wms just choose bspwm

**Comment by rogue-agent** [comment]
That was the issue. Also please finish the first steps on the wiki please.
