### ISSUE TITLE
Zombi theme does not work

### ISSUE THREAD

**Issue by rogue-agent** [gh0stzk/dotfiles#90]
Hello,
Now after the other issue, I installed the lightdm. The Zombi theme does not work sadly. And my keyboard layout got changed.

The taskbar just doesn't load for half od the themes and I made sure to reboot multiple times and re run the installer.

**Comment by gh0stzk** [comment]
Pls read https://github.com/gh0stzk/dotfiles/issues/86

**Comment by rogue-agent** [comment]
> Pls read #86

That solved that part, what about the Keyboard layout_

**Comment by gh0stzk** [comment]
How you configure your keyboard layout? My dotfiles doesnt change any of your system configuration.

**Comment by gh0stzk** [comment]
https://wiki.archlinux.org/title/Xorg/Keyboard_configuration#Setting_keyboard_layout

You can use some of these methods to set your x11 keyboard layout
