### ISSUE TITLE
Make themes available individually.

### ISSUE THREAD

**Issue by Reun85** [gh0stzk/dotfiles#93]
Hi! The whole "switcher" thing is a nice idea on paper, but I believe most of us aren't looking for a complete replacement of our own dots. I don't want to install this whole project, only to "extract" one theme from it or even just a configuration file for one of the tools you use. I don't plan on using many of the tools you use.
 I have never used polybar and eww before. I really like how they look in your "emilia" theme. I would like to take a look at them and learn from it. Could you make each theme available just by themselves(or atleast emilia for me :3 )? Just pure .config files?

**Comment by gh0stzk** [comment]
It is easy to implement, there are several ways to do it,
The simplest, just delete the themes you don't want from the rices folder.

The other basically you would have to edit the bspwmrc file
