### ISSUE TITLE
Long application startup times

### ISSUE THREAD

**Issue by Delitel-WEB** [gh0stzk/dotfiles#94]
I've encountered a rather unusual issue, and perhaps you can help me with it. When transitioning to BSPWM, the initial launch of any application takes from 30 seconds to 1 minute, and all subsequent launches of these applications also take the same amount of time. In contrast, in GNOME, the first launch of applications, like Firefox, takes 10-30 seconds, but all subsequent launches take no more than a second.

These extended startup times on BSPWM do not apply to the terminal or the geany editor.

I thought maybe you could assist me in resolving this problem.

**Comment by Delitel-WEB** [comment]
Yes, it worked, now the applications open without delays, but I have encountered a few more issues. The MediaPlayer doesn't appear on the polybar, and multimedia keys are not working in sxhkd. As I understood from the previous issues, this is related to using pulseaudio instead of pipewire, but I might be mistaken, so please correct me if I'm wrong.
![ShoT_2023-08-03-07-08-53_1366x768](https://github.com/gh0stzk/dotfiles/assets/57365921/e5a4756f-29c7-4861-8dfd-903c59ec9f04)



Also, on some themes like z0mbi3 and andrea, polybar is completely missing.

![ShoT_2023-08-03-07-14-15_1366x768](https://github.com/gh0stzk/dotfiles/assets/57365921/f3683b84-3edd-461b-b429-39699c4ac4b5)
![ShoT_2023-08-03-07-14-28_1366x768](https://github.com/gh0stzk/dotfiles/assets/57365921/9585913b-97eb-47cf-a6b0-a65b2142b575)

**Comment by gh0stzk** [comment]
About the themes with eww like z0mbi3 and andrea, possibly something went wrong in the installer and eww was not installed.

just do it manually

`paru -S eww-x11`

if you get gpg keys error just run these commands before paru
```

curl -sS https://github.com/elkowar.gpg | gpg --import -i -
curl -sS https://github.com/web-flow.gpg | gpg --import -i -
```

**Comment by gh0stzk** [comment]
About mpd in polybar, first you need to configure it setting your music location, follow this link https://github.com/gh0stzk/dotfiles/wiki/Firsts-steps-after-installing#the-album-covers-in-notifications-and-widgets

Then open ncmpcpp with `shift + alt + k` or write `ncmpcpp` in a terminal press the `u` key, that will update the mpd database, then press the `2` key you must see your songs, play someone and the media player will appear in polybar.

About sxhkd media keys... mmm here it works.. but try this.. open a terminal and write 

`Volume --inc` This should increase a volume and you must see a notification.

Pamixer is needed, be sure you have it installed, if not `sudo pacman -S pamixer` but my installer must install it for you, so must be on your system.

Well about pulseaudio and pipewire, must work with pulseaudio and pipewire, i have pipewire, if you use pipewire be sure you have pipewire-pulse package

for the next, previous, pause etc keys, open spotify or ncmpcpp play a song and write in a terminal

`MediaControl --toggle` this must play and pause a song.

if nothing happens, the terminal throws an error????? if not go to your home directory and open .xsessions-errors file and see if there are an error log related to mediakeys

Be sure you dont have another sxhkdrc file in ~/.config/sxhkd/   Mine is located in ~/.config/bspwm/

**Comment by Delitel-WEB** [comment]
My volume increase/decrease works as it should, but MediaControl refuses to work, and there are no errors in .xsessions-errors. As a result, I simply replaced MediaControl with playerctl in sxhkd, which works perfectly for me.

Regarding the music widget, is it mandatory to use it only with local tracks? Can't I control media that is playing, for example, in the browser?

**Comment by gh0stzk** [comment]
The music module in polybar, is the default one from polybar source, only works with mpd. But, there are several third party modules, a lot of people use this for spotify, https://github.com/mihirlad55/polybar-spotify-module

Another good one is this, you can control spotify, playerctl and firefox media. https://github.com/d093w1z/polybar-now-playing

**Comment by Delitel-WEB** [comment]
ok, thanks
