### ISSUE TITLE
Screenshots in the clipboard

### ISSUE THREAD

**Issue by Delitel-WEB** [gh0stzk/dotfiles#95]
Is it possible to save screenshots both to disk and to the clipboard simultaneously?

**Comment by gh0stzk** [comment]
Yes sr! i updated the script right now is better optimized and copy to clipboard as you want. Copy the new content and paste in the script.

https://github.com/gh0stzk/dotfiles/blob/master/config/bspwm/scripts/ScreenShoTer

**Comment by Delitel-WEB** [comment]
The script does not put the screenshot into the clipboard. It shows the notifications, but it does not go into the clipboard.

**Comment by Delitel-WEB** [comment]
> The script does not put the screenshot into the clipboard. It shows the notifications, but it does not go into the clipboard.

I solved the problem. It was related to the fact that I didn't have `xclip` installed.
